import { IMG } from "./seed-data";

export interface ProductSeed {
  title: string;
  slug: string;
  sku: string;
  barcode: string;
  price: number;
  salePrice?: number;
  discount?: number;
  costPrice?: number;
  stock: number;
  category: string;
  subCategory?: string;
  childCategory?: string;
  collection?: string;
  brand: string;
  vendor: string;
  supplier: string;
  countryOfOrigin?: string;
  warranty?: string;
  tags?: string[];
  features?: string[];
  weight?: string;
  images: string[];
  sizes?: string[];
  colors?: { name: string; value?: string; image?: string }[];
  emiAvailable?: boolean;
  isFeatured?: boolean;
  isTrending?: boolean;
  isNewArrival?: boolean;
  isBestSeller?: boolean;
  isFlashSale?: boolean;
  isLimitedEdition?: boolean;
  isOfficial?: boolean;
  isHotDeal?: boolean;
  shippingCharge?: number;
  daysAgo?: number;
  description?: string;
}

const daysAgo = (d: number) => d;

export const productSeeds: ProductSeed[] = [
  {
    title: "Samsung Galaxy S24 Ultra (12/512GB)",
    slug: "samsung-galaxy-s24-ultra",
    sku: "SAM-S24U-512",
    barcode: "8806094050419",
    price: 159999, salePrice: 144999, discount: 10, costPrice: 138000,
    stock: 25, category: "electronics", subCategory: "mobile-tablets", childCategory: "smartphones",
    collection: "tech-deals", brand: "Samsung", vendor: "dhaka-tech-hub", supplier: "global-electronics-supply",
    countryOfOrigin: "South Korea", warranty: "1 Year Official Warranty",
    tags: ["smartphone", "flagship", "galaxy"], emiAvailable: true,
    features: ["6.8\" QHD+ AMOLED 120Hz", "200MP main camera", "S Pen included", "5000mAh battery"],
    weight: "232g", images: [IMG.phone, IMG.phone2, IMG.watch],
    colors: [{ name: "Titanium Gray", value: "#808080" }, { name: "Deep Blue", value: "#2b6cb0" }],
    isFeatured: true, isTrending: true, isHotDeal: true, isOfficial: true, isNewArrival: true, daysAgo: 2,
    description: "The Galaxy S24 Ultra pairs the fastest Snapdragon processor with a legendary 200MP camera and built-in S Pen.",
  },
  {
    title: "Apple iPhone 15 (128GB)",
    slug: "apple-iphone-15",
    sku: "APP-IP15-128",
    barcode: "1942536260042",
    price: 98999, salePrice: 92999, discount: 6, costPrice: 91000,
    stock: 12, category: "electronics", subCategory: "mobile-tablets", childCategory: "smartphones",
    collection: "tech-deals", brand: "Apple", vendor: "digital-world-bd", supplier: "global-electronics-supply",
    countryOfOrigin: "China", warranty: "1 Year Official Warranty",
    tags: ["apple", "smartphone", "iphone"], emiAvailable: true,
    features: ["6.1\" Super Retina XDR", "48MP main camera", "USB-C port", "A16 Bionic"],
    weight: "171g", images: [IMG.phone2, IMG.phone],
    colors: [{ name: "Black", value: "#1a1a1a" }, { name: "Blue", value: "#2b6cb0" }],
    isFlashSale: true, isOfficial: true, isLimitedEdition: false, daysAgo: 4,
    description: "Dynamic Island, a 48MP camera, and USB-C — the iPhone 15 is the everyday powerhouse.",
  },
  {
    title: "Xiaomi Redmi Note 13 Pro (8/256GB)",
    slug: "xiaomi-redmi-note-13-pro",
    sku: "XIA-RN13P-256",
    barcode: "6941812748723",
    price: 34999, salePrice: 31999, discount: 9, costPrice: 30000,
    stock: 40, category: "electronics", subCategory: "mobile-tablets", childCategory: "smartphones",
    collection: "best-sellers", brand: "Xiaomi", vendor: "smart-living-bd", supplier: "tech-source-bd",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["xiaomi", "smartphone", "redmi"], emiAvailable: true,
    features: ["200MP OIS camera", "6.67\" 120Hz AMOLED", "67W turbo charging"],
    weight: "187g", images: [IMG.phone, IMG.phone2],
    colors: [{ name: "Midnight Black", value: "#1a1a1a" }, { name: "Lavender", value: "#a78bfa" }],
    isFeatured: true, isBestSeller: true, isNewArrival: true, daysAgo: 6,
    description: "A 200MP camera and 67W charging make the Note 13 Pro the value flagship.",
  },
  {
    title: "Apple iPad 10th Gen (Wi-Fi 64GB)",
    slug: "apple-ipad-10th-gen",
    sku: "APP-IPAD10-64",
    barcode: "1942536260043",
    price: 54999, salePrice: 52999, discount: 4, costPrice: 51000,
    stock: 15, category: "electronics", subCategory: "mobile-tablets", childCategory: "tablets",
    collection: "new-arrivals", brand: "Apple", vendor: "digital-world-bd", supplier: "global-electronics-supply",
    countryOfOrigin: "China", warranty: "1 Year Official Warranty",
    tags: ["apple", "tablet", "ipad"],
    weight: "477g", images: [IMG.tablet, IMG.laptop],
    isNewArrival: true, daysAgo: 8,
    description: "The iPad 10th gen brings a 10.9\" Liquid Retina display, USB-C and the A14 chip.",
  },
  {
    title: "Samsung Galaxy Tab S9 FE (8/128GB)",
    slug: "samsung-galaxy-tab-s9-fe",
    sku: "SAM-TABS9FE-128",
    barcode: "8806094700451",
    price: 56999, salePrice: 52999, discount: 7, costPrice: 50500,
    stock: 18, category: "electronics", subCategory: "mobile-tablets", childCategory: "tablets",
    collection: "new-arrivals", brand: "Samsung", vendor: "dhaka-tech-hub", supplier: "global-electronics-supply",
    countryOfOrigin: "South Korea", warranty: "1 Year Official Warranty",
    tags: ["samsung", "tablet"],
    weight: "523g", images: [IMG.tablet],
    isNewArrival: true, isTrending: true, daysAgo: 5,
    description: "S Pen included — the Tab S9 FE is made for notes, sketches and streaming.",
  },
  {
    title: "JBL Tune 510BT Wireless Headphones",
    slug: "jbl-tune-510bt-headphones",
    sku: "JBL-510BT-BLK",
    barcode: "6925281942124",
    price: 4990, salePrice: 3990, discount: 20, costPrice: 3400,
    stock: 60, category: "electronics", subCategory: "audio-wearables", childCategory: "headphones-earbuds",
    collection: "best-sellers", brand: "JBL", vendor: "gadget-house-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["headphone", "jbl", "wireless"], emiAvailable: false,
    features: ["Pure Bass sound", "40h battery life", "Multipoint connection"],
    weight: "160g", images: [IMG.headphones],
    colors: [{ name: "Black", value: "#1a1a1a" }, { name: "Blue", value: "#2b6cb0" }, { name: "Red", value: "#c53030" }],
    isBestSeller: true, isTrending: true, daysAgo: 20,
    description: "JBL Pure Bass with an incredible 40 hours of battery life.",
  },
  {
    title: "Anker Soundcore R50i Earbuds",
    slug: "anker-soundcore-r50i-earbuds",
    sku: "ANK-R50I-WHT",
    barcode: "8480610309119",
    price: 2990, salePrice: 2490, discount: 17, costPrice: 2100,
    stock: 80, category: "electronics", subCategory: "audio-wearables", childCategory: "headphones-earbuds",
    collection: "best-sellers", brand: "Anker", vendor: "gadget-house-bd", supplier: "tech-source-bd",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["earbuds", "anker", "tws"],
    weight: "48g", images: [IMG.earbuds, IMG.headphones],
    isBestSeller: true, daysAgo: 30,
    description: "Rich sound, comfortable fit and reliable battery in a pocketable case.",
  },
  {
    title: "JBL Go 4 Bluetooth Speaker",
    slug: "jbl-go-4-speaker",
    sku: "JBL-GO4-BLK",
    barcode: "6925281942449",
    price: 3490, salePrice: 2790, discount: 20, costPrice: 2350,
    stock: 4, category: "electronics", subCategory: "audio-wearables", childCategory: "bluetooth-speakers",
    collection: "tech-deals", brand: "JBL", vendor: "gadget-house-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["speaker", "jbl", "bluetooth"],
    weight: "190g", images: [IMG.speaker],
    colors: [{ name: "Black", value: "#1a1a1a" }, { name: "Green", value: "#2f855a" }, { name: "Blue", value: "#2b6cb0" }],
    isFlashSale: true, isTrending: true, daysAgo: 3,
    description: "Pro sound in your pocket — waterproof, compact and JBL Pro quality.",
  },
  {
    title: "Sony Extra Bass Wireless Speaker",
    slug: "sony-extra-bass-speaker",
    sku: "SNY-XB23-BLK",
    barcode: "4548736078022",
    price: 8990, salePrice: 7490, discount: 17, costPrice: 6800,
    stock: 22, category: "electronics", subCategory: "audio-wearables", childCategory: "bluetooth-speakers",
    collection: "tech-deals", brand: "Sony", vendor: "digital-world-bd", supplier: "global-electronics-supply",
    countryOfOrigin: "Japan", warranty: "1 Year Warranty",
    tags: ["sony", "speaker", "bass"],
    weight: "580g", images: [IMG.speaker, IMG.headphones],
    isTrending: true, daysAgo: 12,
    description: "Extra Bass, 12-hour battery and IP67 water resistance.",
  },
  {
    title: "Xiaomi Smart Band 9",
    slug: "xiaomi-smart-band-9",
    sku: "XIA-BAND9-BLK",
    barcode: "6941812799105",
    price: 3990, salePrice: 3490, discount: 13, costPrice: 3000,
    stock: 55, category: "electronics", subCategory: "audio-wearables", childCategory: "smartwatches",
    collection: "best-sellers", brand: "Xiaomi", vendor: "smart-living-bd", supplier: "tech-source-bd",
    countryOfOrigin: "China", warranty: "6 Months Warranty",
    tags: ["band", "xiaomi", "fitness"],
    weight: "27g", images: [IMG.watch],
    isFeatured: true, isBestSeller: true, daysAgo: 15,
    description: "1.62\" AMOLED display, 21-day battery and 150+ sport modes.",
  },
  {
    title: "Samsung Galaxy Watch 7 (44mm)",
    slug: "samsung-galaxy-watch-7",
    sku: "SAM-GW7-44",
    barcode: "8806094944762",
    price: 38999, salePrice: 35999, discount: 8, costPrice: 34000,
    stock: 10, category: "electronics", subCategory: "audio-wearables", childCategory: "smartwatches",
    collection: "new-arrivals", brand: "Samsung", vendor: "dhaka-tech-hub", supplier: "global-electronics-supply",
    countryOfOrigin: "South Korea", warranty: "1 Year Official Warranty", emiAvailable: true,
    tags: ["watch", "samsung", "smartwatch"],
    weight: "33g", images: [IMG.watch, IMG.phone],
    colors: [{ name: "Black", value: "#1a1a1a" }, { name: "Silver", value: "#c0c0c0" }],
    isFeatured: true, isOfficial: true, isNewArrival: true, daysAgo: 7,
    description: "Advanced sleep insights, body composition and Galaxy AI — on your wrist.",
  },
  {
    title: "Baseus 65W GaN Fast Charger",
    slug: "baseus-65w-gan-charger",
    sku: "BAS-65W-BLK",
    barcode: "6931796909142",
    price: 2790, salePrice: 2190, discount: 21, costPrice: 1800,
    stock: 35, category: "electronics", subCategory: "computers-accessories", childCategory: "chargers-power",
    collection: "tech-deals", brand: "Baseus", vendor: "gadget-house-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["charger", "gan", "baseus"],
    weight: "90g", images: [IMG.charger],
    isFlashSale: true, daysAgo: 10,
    description: "Two USB-C + one USB-A, 65W GaN tech in a pocketable brick.",
  },
  {
    title: "Anker PowerCore 20000mAh Power Bank",
    slug: "anker-powercore-20000",
    sku: "ANK-PC200-20K",
    barcode: "8480610382815",
    price: 3490, salePrice: 2790, discount: 20, costPrice: 2300,
    stock: 2, category: "electronics", subCategory: "computers-accessories", childCategory: "chargers-power",
    collection: "best-sellers", brand: "Anker", vendor: "gadget-house-bd", supplier: "tech-source-bd",
    countryOfOrigin: "China", warranty: "18 Months Warranty",
    tags: ["powerbank", "anker", "20000mah"],
    weight: "345g", images: [IMG.powerbank, IMG.charger],
    colors: [{ name: "Black", value: "#1a1a1a" }, { name: "White", value: "#f5f5f5" }],
    isBestSeller: true, daysAgo: 25,
    description: "High-capacity 20000mAh bank with fast charging for phones and tablets.",
  },
  {
    title: "TP-Link AC750 Dual Band WiFi Router",
    slug: "tp-link-ac750-router",
    sku: "TPL-AC750",
    barcode: "6935364089221",
    price: 2350, salePrice: 1890, discount: 20, costPrice: 1550,
    stock: 45, category: "electronics", subCategory: "computers-accessories", childCategory: "keyboards-mice",
    collection: "home-essentials", brand: "TP-Link", vendor: "smart-living-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["router", "tp-link", "wifi"],
    weight: "310g", images: [IMG.router],
    isFeatured: true, daysAgo: 35,
    description: "Reliable dual-band WiFi for a smooth home connection.",
  },
  {
    title: "Baseus Wireless Keyboard & Mouse Combo",
    slug: "baseus-wireless-keyboard-mouse",
    sku: "BAS-KBM-COMBO",
    barcode: "6931796909159",
    price: 3490, salePrice: 2790, discount: 20, costPrice: 2300,
    stock: 28, category: "electronics", subCategory: "computers-accessories", childCategory: "keyboards-mice",
    collection: "home-essentials", brand: "Baseus", vendor: "gadget-house-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["keyboard", "mouse", "baseus"],
    weight: "780g", images: [IMG.keyboard, IMG.mouse],
    isTrending: true, daysAgo: 14,
    description: "Silent keys and a precise wireless mouse — tidy and quiet.",
  },
  {
    title: "Samsung 55\" Crystal 4K Smart TV",
    slug: "samsung-55-crystal-4k-tv",
    sku: "SAM-55CU7000",
    barcode: "8806095068317",
    price: 74500, salePrice: 69900, discount: 6, costPrice: 67000,
    stock: 9, category: "electronics", subCategory: "tv-home-entertainment", childCategory: "televisions",
    collection: "tech-deals", brand: "Samsung", vendor: "dhaka-tech-hub", supplier: "global-electronics-supply",
    countryOfOrigin: "South Korea", warranty: "2 Years Panel Warranty", emiAvailable: true,
    tags: ["tv", "samsung", "4k"],
    weight: "12500g", images: [IMG.tv],
    isFeatured: true, isOfficial: true, daysAgo: 40,
    description: "Crystal 4K processor and a slim design for the living room.",
  },
  {
    title: "Samsung 5.1 Channel Soundbar",
    slug: "samsung-51-soundbar",
    sku: "SAM-HW-Q600A",
    barcode: "8806094120057",
    price: 28999, salePrice: 25999, discount: 10, costPrice: 24000,
    stock: 0, category: "electronics", subCategory: "tv-home-entertainment", childCategory: "soundbars",
    collection: "tech-deals", brand: "Samsung", vendor: "dhaka-tech-hub", supplier: "global-electronics-supply",
    countryOfOrigin: "South Korea", warranty: "1 Year Warranty", emiAvailable: true,
    tags: ["soundbar", "samsung", "home-theatre"],
    weight: "5900g", images: [IMG.soundbar],
    isHotDeal: true, daysAgo: 50,
    description: "True 5.1 surround with wireless rear speakers and Dolby Atmos.",
  },
  {
    title: "Philips Premium Air Fryer 5.5L",
    slug: "philips-air-fryer-55l",
    sku: "PHL-AF5525",
    barcode: "8710103909141",
    price: 13990, salePrice: 11990, discount: 14, costPrice: 10500,
    stock: 8, category: "home-kitchen-appliances", subCategory: "kitchen-appliances", childCategory: "air-fryers",
    collection: "home-essentials", brand: "Philips", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "China", warranty: "2 Years Warranty",
    tags: ["airfryer", "philips", "kitchen"],
    features: ["Rapid Air technology", "5.5L family capacity", "Up to 90% less fat"],
    weight: "6800g", images: [IMG.airfryer, IMG.kitchen],
    isFeatured: true, isBestSeller: true, isFlashSale: true, daysAgo: 18,
    description: "Crispy results with up to 90% less fat — Rapid Air technology.",
  },
  {
    title: "Philips 600W Blender",
    slug: "philips-600w-blender",
    sku: "PHL-BL6018",
    barcode: "8710103584080",
    price: 4490, salePrice: 3690, discount: 18, costPrice: 3100,
    stock: 30, category: "home-kitchen-appliances", subCategory: "kitchen-appliances", childCategory: "blenders-juicers",
    collection: "home-essentials", brand: "Philips", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "China", warranty: "2 Years Warranty",
    tags: ["blender", "philips", "kitchen"],
    weight: "2100g", images: [IMG.blender],
    isBestSeller: true, daysAgo: 28,
    description: "ProBlend 600W motor with stainless steel blades.",
  },
  {
    title: "Walton 2.5L Electric Rice Cooker",
    slug: "walton-25l-rice-cooker",
    sku: "WLT-RC-25L",
    barcode: "8801935718206",
    price: 2990, salePrice: 2490, discount: 17, costPrice: 2050,
    stock: 50, category: "home-kitchen-appliances", subCategory: "kitchen-appliances", childCategory: "rice-cookers",
    collection: "home-essentials", brand: "Walton", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "Bangladesh", warranty: "2 Years Warranty",
    tags: ["rice-cooker", "walton"],
    weight: "2200g", images: [IMG.ricecooker],
    isBestSeller: true, daysAgo: 32,
    description: "One-touch cooking with keep-warm function for perfect rice.",
  },
  {
    title: "De'Longhi Automatic Coffee Maker",
    slug: "delonghi-coffee-maker",
    sku: "DLG-CM-9015",
    barcode: "8004399350141",
    price: 18900, salePrice: 15900, discount: 16, costPrice: 14000,
    stock: 7, category: "home-kitchen-appliances", subCategory: "kitchen-appliances", childCategory: "coffee-makers",
    collection: "new-arrivals", brand: "Philips", vendor: "digital-world-bd", supplier: "global-electronics-supply",
    countryOfOrigin: "Italy", warranty: "1 Year Warranty",
    tags: ["coffee", "delonghi"],
    weight: "4600g", images: [IMG.coffeemaker],
    isNewArrival: true, daysAgo: 9,
    description: "Barista-grade espresso, cappuccino and latte at home.",
  },
  {
    title: "Philips 1500W Steam Iron",
    slug: "philips-steam-iron",
    sku: "PHL-IR-1500",
    barcode: "8710103804163",
    price: 3990, salePrice: 3290, discount: 18, costPrice: 2700,
    stock: 3, category: "home-kitchen-appliances", subCategory: "small-appliances",
    collection: "home-essentials", brand: "Philips", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "China", warranty: "2 Years Warranty",
    tags: ["iron", "steam", "philips"],
    weight: "1350g", images: [IMG.iron, IMG.kitchen],
    isFlashSale: true, daysAgo: 11,
    description: "Powerful steam for crisp, crease-free clothes.",
  },
  {
    title: "Walton 1.8L Electric Kettle",
    slug: "walton-electric-kettle",
    sku: "WLT-EK-18L",
    barcode: "8801935718207",
    price: 1690, salePrice: 1290, discount: 24, costPrice: 1000,
    stock: 0, category: "home-kitchen-appliances", subCategory: "small-appliances",
    collection: "home-essentials", brand: "Walton", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "Bangladesh", warranty: "2 Years Warranty",
    tags: ["kettle", "walton"],
    weight: "950g", images: [IMG.kettle],
    daysAgo: 60,
    description: "Rapid boil 1.8L kettle with auto shut-off.",
  },
  {
    title: "Xiaomi Robot Vacuum Cleaner",
    slug: "xiaomi-robot-vacuum",
    sku: "XIA-VAC-ROBOT",
    barcode: "6941812748885",
    price: 16990, salePrice: 14990, discount: 12, costPrice: 13500,
    stock: 14, category: "home-kitchen-appliances", subCategory: "cleaning-appliances", childCategory: "vacuum-cleaners",
    collection: "smart-home-picks", brand: "Xiaomi", vendor: "smart-living-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty", emiAvailable: true,
    tags: ["vacuum", "robot", "xiaomi"],
    features: ["Laser navigation", "4000Pa suction", "App + voice control"],
    weight: "3400g", images: [IMG.vacuum],
    isFeatured: true, isBestSeller: true, daysAgo: 16,
    description: "Laser-guided robot vacuum that maps your home and cleans itself.",
  },
  {
    title: "Smart Air Purifier HEPA Filter",
    slug: "smart-air-purifier-hepa",
    sku: "SMT-AP-HEPA",
    barcode: "8809660712889",
    price: 18900, salePrice: 15900, discount: 16, costPrice: 14200,
    stock: 11, category: "home-kitchen-appliances", subCategory: "cleaning-appliances", childCategory: "air-purifiers",
    collection: "smart-home-picks", brand: "Walton", vendor: "home-essentials-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "Bangladesh", warranty: "2 Years Warranty",
    tags: ["purifier", "air", "hepa"],
    weight: "5800g", images: [IMG.airpurifier],
    isTrending: true, daysAgo: 13,
    description: "HEPA filtration with real-time air quality display.",
  },
  {
    title: "TP-Link Smart WiFi LED Bulb",
    slug: "tp-link-smart-wifi-bulb",
    sku: "TPL-SB-65W",
    barcode: "6935364091143",
    price: 1390, salePrice: 990, discount: 29, costPrice: 750,
    stock: 100, category: "smart-home", subCategory: "smart-lighting", childCategory: "smart-bulbs",
    collection: "smart-home-picks", brand: "TP-Link", vendor: "smart-living-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["bulb", "smart", "wifi"],
    weight: "120g", images: [IMG.bulb, IMG.lamp],
    colors: [{ name: "White", value: "#f5f5f5" }, { name: "Warm", value: "#ffb74d" }, { name: "RGB", value: "#9f7aea" }],
    isFlashSale: true, isBestSeller: true, daysAgo: 5,
    description: "16 million colors, scheduling and voice control with no hub.",
  },
  {
    title: "Smart Table Lamp with Dimmer",
    slug: "smart-table-lamp",
    sku: "SMT-LAMP-DIM",
    barcode: "8809660712896",
    price: 2490, salePrice: 1990, discount: 20, costPrice: 1600,
    stock: 26, category: "smart-home", subCategory: "smart-lighting", childCategory: "smart-lamps",
    collection: "smart-home-picks", brand: "Walton", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "Bangladesh", warranty: "1 Year Warranty",
    tags: ["lamp", "smart", "dimmer"],
    weight: "950g", images: [IMG.lamp, IMG.bulb],
    isNewArrival: true, daysAgo: 4,
    description: "Touch dimmer with warm-to-cool white tones for reading.",
  },
  {
    title: "360° WiFi Security Camera",
    slug: "wifi-security-camera-360",
    sku: "SMT-CAM-360",
    barcode: "8809660712902",
    price: 4490, salePrice: 3690, discount: 18, costPrice: 3100,
    stock: 33, category: "smart-home", subCategory: "smart-security", childCategory: "security-cameras",
    collection: "smart-home-picks", brand: "TP-Link", vendor: "smart-living-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["camera", "cctv", "wifi"],
    weight: "480g", images: [IMG.cctv, IMG.cam],
    isBestSeller: true, isTrending: true, daysAgo: 22,
    description: "360° pan-tilt coverage with night vision and two-way audio.",
  },
  {
    title: "Smart Video Doorbell",
    slug: "smart-video-doorbell",
    sku: "SMT-DB-1080",
    barcode: "8809660712919",
    price: 7990, salePrice: 6790, discount: 15, costPrice: 5900,
    stock: 16, category: "smart-home", subCategory: "smart-security",
    collection: "smart-home-picks", brand: "TP-Link", vendor: "smart-living-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["doorbell", "smart", "security"],
    weight: "380g", images: [IMG.cctv, IMG.lock],
    isNewArrival: true, daysAgo: 6,
    description: "See and speak to visitors from anywhere, day or night.",
  },
  {
    title: "Smart Fingerprint Door Lock",
    slug: "smart-fingerprint-lock",
    sku: "SMT-LOCK-FP",
    barcode: "8809660712926",
    price: 15900, salePrice: 13900, discount: 13, costPrice: 12000,
    stock: 9, category: "smart-home", subCategory: "smart-security", childCategory: "smart-locks",
    collection: "smart-home-picks", brand: "Walton", vendor: "home-essentials-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "Bangladesh", warranty: "1 Year Warranty",
    tags: ["lock", "fingerprint", "smart"],
    weight: "2500g", images: [IMG.lock],
    isFeatured: true, daysAgo: 19,
    description: "Fingerprint, PIN and app access — deadbolt security reimagined.",
  },
  {
    title: "Premium Cotton Panjabi (Men)",
    slug: "premium-cotton-panjabi",
    sku: "GB-PNJ-COT-001",
    barcode: "8809555010001",
    price: 1890, salePrice: 1490, discount: 21, costPrice: 1100,
    stock: 75, category: "fashion", subCategory: "mens-fashion", childCategory: "panjabi",
    collection: "eid-collection", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh", warranty: null,
    tags: ["panjabi", "cotton", "men"], emiAvailable: false,
    features: ["100% premium cotton", "Soft hand feel", "Regular fit"],
    weight: "450g", images: [IMG.panjabi, IMG.fashionStore],
    sizes: ["M", "L", "XL"],
    colors: [{ name: "White", value: "#f5f5f5", image: IMG.panjabi }, { name: "Navy", value: "#1e3a5f", image: IMG.tshirt }, { name: "Black", value: "#1a1a1a", image: IMG.suit }],
    isBestSeller: true, isTrending: true, isNewArrival: true, daysAgo: 3,
    description: "Lightweight cotton panjabi, cut for comfort from Fajr to festive nights.",
  },
  {
    title: "Classic White Premium Panjabi",
    slug: "classic-white-premium-panjabi",
    sku: "GB-PNJ-WHT-001",
    barcode: "8809555010002",
    price: 2490, salePrice: 1990, discount: 20, costPrice: 1500,
    stock: 40, category: "fashion", subCategory: "mens-fashion", childCategory: "panjabi",
    collection: "eid-collection", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["panjabi", "white", "premium"],
    weight: "480g", images: [IMG.tshirt, IMG.panjabi],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "White", value: "#f5f5f5" }],
    isNewArrival: true, daysAgo: 8,
    description: "Structured collar and hand-finished stitching — the classic Eid essential.",
  },
  {
    title: "Men's Slim Fit Formal Shirt",
    slug: "mens-slim-fit-formal-shirt",
    sku: "GB-SHT-SLIM-001",
    barcode: "8809555010003",
    price: 1690, salePrice: 1290, discount: 24, costPrice: 900,
    stock: 90, category: "fashion", subCategory: "mens-fashion", childCategory: "formal-shirts",
    collection: "best-sellers", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["shirt", "formal", "slim"],
    weight: "300g", images: [IMG.shirt, IMG.suit],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", value: "#f5f5f5" }, { name: "Blue", value: "#2b6cb0" }, { name: "Navy", value: "#1e3a5f" }],
    isBestSeller: true, daysAgo: 21,
    description: "Wrinkle-resistant cotton blend with a clean modern slim fit.",
  },
  {
    title: "Designer Silk Saree",
    slug: "designer-silk-saree",
    sku: "GB-SAR-SLK-001",
    barcode: "8809555010004",
    price: 5490, salePrice: 4490, discount: 18, costPrice: 3200,
    stock: 20, category: "fashion", subCategory: "womens-fashion", childCategory: "sarees",
    collection: "eid-collection", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["saree", "silk", "women"],
    weight: "600g", images: [IMG.saree, IMG.woman, IMG.shopping],
    colors: [{ name: "Red", value: "#c53030", image: IMG.saree }, { name: "Gold", value: "#d4af37", image: IMG.woman }],
    isFeatured: true, isTrending: true, daysAgo: 9,
    description: "Handcrafted silk saree with intricate zari border work.",
  },
  {
    title: "Trendy Casual Saree",
    slug: "trendy-casual-saree",
    sku: "GB-SAR-CAS-001",
    barcode: "8809555010005",
    price: 3490, salePrice: 2790, discount: 20, costPrice: 2000,
    stock: 34, category: "fashion", subCategory: "womens-fashion", childCategory: "sarees",
    collection: "eid-collection", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["saree", "casual", "women"],
    weight: "520g", images: [IMG.woman, IMG.saree],
    colors: [{ name: "Blue", value: "#2b6cb0" }, { name: "Green", value: "#2f855a" }],
    isBestSeller: true, daysAgo: 17,
    description: "Easy-to-drape soft saree with a playful contemporary print.",
  },
  {
    title: "Casual Maxi Dress",
    slug: "casual-maxi-dress",
    sku: "GB-DRS-MAX-001",
    barcode: "8809555010006",
    price: 2390, salePrice: 1890, discount: 21, costPrice: 1300,
    stock: 48, category: "fashion", subCategory: "womens-fashion", childCategory: "dresses",
    collection: "new-arrivals", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["dress", "maxi", "women"],
    weight: "400g", images: [IMG.dress, IMG.woman],
    sizes: ["S", "M", "L"],
    colors: [{ name: "Black", value: "#1a1a1a", image: IMG.dress }, { name: "Green", value: "#2f855a" }],
    isNewArrival: true, isTrending: true, daysAgo: 5,
    description: "Flowy everyday maxi with breathable fabric and side pockets.",
  },
  {
    title: "Office A-Line Dress",
    slug: "office-a-line-dress",
    sku: "GB-DRS-A-001",
    barcode: "8809555010007",
    price: 3490, salePrice: 2890, discount: 17, costPrice: 2100,
    stock: 22, category: "fashion", subCategory: "womens-fashion", childCategory: "dresses",
    collection: "best-sellers", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["dress", "office", "women"],
    weight: "420g", images: [IMG.woman, IMG.dress],
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Navy", value: "#1e3a5f" }, { name: "Gray", value: "#808080" }],
    isBestSeller: true, daysAgo: 23,
    description: "Structured A-line silhouette that moves from meetings to evenings.",
  },
  {
    title: "Casual Canvas Sneakers",
    slug: "casual-canvas-sneakers",
    sku: "GB-SNK-CAN-001",
    barcode: "8809555010008",
    price: 3990, salePrice: 3190, discount: 20, costPrice: 2200,
    stock: 5, category: "sports-lifestyle", subCategory: "footwear", childCategory: "sneakers",
    collection: "new-arrivals", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["sneaker", "canvas", "shoe"],
    weight: "850g", images: [IMG.sneaker1, IMG.sneaker2],
    sizes: ["40", "41", "42", "43"],
    colors: [{ name: "Red", value: "#c53030", image: IMG.sneaker1 }, { name: "White", value: "#f5f5f5", image: IMG.sneaker2 }],
    isTrending: true, isNewArrival: true, daysAgo: 7,
    description: "Classic canvas sneakers with cushioned insole for all-day comfort.",
  },
  {
    title: "Running Performance Sneakers",
    slug: "running-performance-sneakers",
    sku: "GB-SNK-RUN-001",
    barcode: "8809555010009",
    price: 5490, salePrice: 4390, discount: 20, costPrice: 3100,
    stock: 27, category: "sports-lifestyle", subCategory: "footwear", childCategory: "sneakers",
    collection: "new-arrivals", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["sneaker", "running", "sport"],
    weight: "780g", images: [IMG.sneaker2, IMG.sneaker1],
    sizes: ["38", "39", "40", "41", "42"],
    colors: [{ name: "White", value: "#f5f5f5" }, { name: "Gray", value: "#808080" }],
    isFeatured: true, isBestSeller: true, daysAgo: 10,
    description: "Responsive foam midsole engineered for daily miles.",
  },
  {
    title: "Urban Backpack 25L",
    slug: "urban-backpack-25l",
    sku: "GB-BAG-25L",
    barcode: "8809555010010",
    price: 2790, salePrice: 2190, discount: 21, costPrice: 1500,
    stock: 38, category: "sports-lifestyle", subCategory: "footwear", childCategory: "sneakers",
    collection: "home-essentials", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["bag", "backpack", "urban"],
    weight: "700g", images: [IMG.bag, IMG.fashionStore],
    isNewArrival: true, daysAgo: 12,
    description: "Water-resistant 25L backpack with padded laptop sleeve.",
  },
  {
    title: "Camping & Travel Duffel",
    slug: "camping-travel-duffel",
    sku: "GB-BAG-DUF-01",
    barcode: "8809555010011",
    price: 3290, salePrice: 2590, discount: 21, costPrice: 1800,
    stock: 0, category: "sports-lifestyle", subCategory: "footwear", childCategory: "sneakers",
    collection: "home-essentials", brand: "Walton", vendor: "style-mart-bd", supplier: "style-mart-bd",
    countryOfOrigin: "Bangladesh",
    tags: ["bag", "duffel", "travel"],
    weight: "850g", images: [IMG.camp, IMG.bag],
    daysAgo: 55,
    description: "Spacious 40L duffel built for weekend trips and gym days.",
  },
  {
    title: "Walton Ceiling Fan (56\")",
    slug: "walton-ceiling-fan-56",
    sku: "WLT-CF-56",
    barcode: "8801935718208",
    price: 4590, salePrice: 3890, discount: 15, costPrice: 3200,
    stock: 44, category: "home-kitchen-appliances", subCategory: "small-appliances",
    collection: "home-essentials", brand: "Walton", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "Bangladesh", warranty: "2 Years Warranty",
    tags: ["fan", "ceiling", "walton"],
    weight: "4200g", images: [IMG.fan],
    isBestSeller: true, daysAgo: 30,
    description: "High-airflow silent ceiling fan with 3-speed control.",
  },
  {
    title: "Walton Microwave Oven 23L",
    slug: "walton-microwave-oven",
    sku: "WLT-MWO-23L",
    barcode: "8801935718209",
    price: 13900, salePrice: 11900, discount: 14, costPrice: 10400,
    stock: 13, category: "home-kitchen-appliances", subCategory: "kitchen-appliances",
    collection: "home-essentials", brand: "Walton", vendor: "home-essentials-bd", supplier: "dhaka-wholesale-hub",
    countryOfOrigin: "Bangladesh", warranty: "2 Years Warranty",
    tags: ["microwave", "walton"],
    weight: "13500g", images: [IMG.microwave, IMG.kitchen],
    isFeatured: true, daysAgo: 26,
    description: "23L digital microwave with 8 auto-cook menus.",
  },
  {
    title: "Baseus Magnetic Power Bank 10000mAh",
    slug: "baseus-magnetic-power-bank",
    sku: "BAS-MPB-10K",
    barcode: "6931796909166",
    price: 4290, salePrice: 3590, discount: 16, costPrice: 3000,
    stock: 19, category: "electronics", subCategory: "computers-accessories", childCategory: "chargers-power",
    collection: "tech-deals", brand: "Baseus", vendor: "gadget-house-bd", supplier: "smart-product-distribution",
    countryOfOrigin: "China", warranty: "1 Year Warranty",
    tags: ["powerbank", "magnetic", "baseus"],
    weight: "250g", images: [IMG.powerbank, IMG.charger],
    isFlashSale: true, isNewArrival: true, daysAgo: 5,
    description: "MagSafe-style magnetic snap-on charging with 20W fast charge.",
  },
  {
    title: "Sony WH-CH520 Wireless Headphones",
    slug: "sony-wh-ch520",
    sku: "SNY-WHCH520",
    barcode: "4548736082210",
    price: 7990, salePrice: 6490, discount: 19, costPrice: 5700,
    stock: 31, category: "electronics", subCategory: "audio-wearables", childCategory: "headphones-earbuds",
    collection: "tech-deals", brand: "Sony", vendor: "digital-world-bd", supplier: "global-electronics-supply",
    countryOfOrigin: "Japan", warranty: "1 Year Warranty",
    tags: ["headphone", "sony", "wireless"],
    weight: "147g", images: [IMG.headphones, IMG.earbuds],
    colors: [{ name: "Black", value: "#1a1a1a" }, { name: "Blue", value: "#2b6cb0" }],
    isTrending: true, daysAgo: 24,
    description: "50h battery, quick charge and lightweight comfort.",
  },
];

export const heroSlideSeeds = [
  {
    id: "seed-slide-1",
    desktopImage: "https://images.unsplash.com/photo-1511707175664-5f897ff02aa9?q=80&w=1920&auto=format&fit=crop",
    mobileImage: "https://images.unsplash.com/photo-1511707175664-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
    badge: "New Season Tech",
    title: "Smart Living\nStarts Here",
    subtitle: "Flagship phones, wearables and smart home — curated for you.",
    description: "Up to 20% off on the season's most-wanted gadgets.",
    primaryButtonText: "Shop Now",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Explore Deals",
    secondaryButtonUrl: "/shop?label=flash_sale",
    alignment: "left",
    overlay: true,
    overlayOpacity: 0.55,
    status: "active",
    priority: 4,
  },
  {
    id: "seed-slide-2",
    desktopImage: "https://images.unsplash.com/photo-1556911220-bff31c812dba?q=80&w=1920&auto=format&fit=crop",
    mobileImage: "https://images.unsplash.com/photo-1556911220-bff31c812dba?q=80&w=800&auto=format&fit=crop",
    badge: "Home Essentials",
    title: "Upgrade Your\nEveryday",
    subtitle: "Appliances that cook, clean and care.",
    description: "Save big on air fryers, purifiers and more.",
    primaryButtonText: "Shop Appliances",
    primaryButtonUrl: "/shop?category=home-kitchen-appliances",
    alignment: "left",
    overlay: true,
    overlayOpacity: 0.5,
    textColor: "#ffffff",
    status: "active",
    priority: 3,
  },
  {
    id: "seed-slide-3",
    desktopImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1920&auto=format&fit=crop",
    mobileImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=800&auto=format&fit=crop",
    badge: "Fashion",
    title: "Fresh Tech.\nBetter Life.",
    subtitle: "Seasonal fashion for the whole family.",
    description: "Premium panjabi, sarees and everyday essentials.",
    primaryButtonText: "Shop Fashion",
    primaryButtonUrl: "/shop?category=fashion",
    secondaryButtonText: "View Collections",
    secondaryButtonUrl: "/shop?collection=eid-collection",
    alignment: "center",
    overlay: true,
    overlayOpacity: 0.5,
    status: "active",
    priority: 2,
  },
  {
    id: "seed-slide-4",
    desktopImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1920&auto=format&fit=crop",
    mobileImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop",
    badge: "Flash Deals",
    title: "Big Deals,\nBetter Choices.",
    subtitle: "Limited-time prices on tech and lifestyle.",
    description: "When they're gone, they're gone — while stocks last.",
    primaryButtonText: "Shop Flash Deals",
    primaryButtonUrl: "/shop?label=flash_sale",
    alignment: "left",
    overlay: true,
    overlayOpacity: 0.55,
    status: "active",
    priority: 1,
  },
];
