const u = (id: string, w = 1080) => `https://images.unsplash.com/${id}?q=80&w=${w}&auto=format&fit=crop`;

export const IMG = {
  phone: u("photo-1511707175664-5f897ff02aa9"),
  phone2: u("photo-1533228100845-08145b01de14"),
  tablet: u("photo-1527698266440-12104e498b76"),
  watch: u("photo-1523275335684-37898b6baf30"),
  headphones: u("photo-1505740420928-5e560c06d30e"),
  earbuds: u("photo-1590658268037-6bf12165a8df"),
  speaker: u("photo-1608043152269-423dbba4e7e1"),
  tv: u("photo-1593359677879-a4bb92f829d1"),
  soundbar: u("photo-1545454675-3531b543be5d"),
  laptop: u("photo-1496181133206-80ce9b88a853"),
  keyboard: u("photo-1541140532154-b024d705b90a"),
  mouse: u("photo-1527864550417-7fd91fc51a46"),
  charger: u("photo-1583863788434-e58a36330cf0"),
  powerbank: u("photo-1609091839311-d5365f9ff1c5"),
  router: u("photo-1544197150-b99a580bb7a8"),
  bulb: u("photo-1558002038-1055907df827"),
  lamp: u("photo-1507473885765-e6ed057f782c"),
  cam: u("photo-1526170375885-4d8ecf77b99f"),
  cctv: u("photo-1557324232-b8917d3c3dcb"),
  lock: u("photo-1563013544-824ae1b704d3"),
  kitchen: u("photo-1556911220-bff31c812dba"),
  airfryer: u("photo-1598511723449-2ab4d0c5f9b4"),
  blender: u("photo-1570222094114-d1b58f9c34c9"),
  coffeemaker: u("photo-1509042239860-f550ce710b93"),
  ricecooker: u("photo-1586201375761-83865001e31c"),
  vacuum: u("photo-1558317377-067fb923f30000"),
  airpurifier: u("photo-1585771724684-38269d6639fd"),
  kettle: u("photo-1603969206502-2d5f1af0e6b5"),
  iron: u("photo-1623484236971-32eba16bd7ff"),
  fan: u("photo-1554308669-bd8bc3d31d71"),
  microwave: u("photo-1585751139243-efc8a1e3e1b2"),
  fashionStore: u("photo-1441986300917-64674bd600d8"),
  shopping: u("photo-1483985988355-763728e1935b"),
  woman: u("photo-1517841905240-472988babdf9"),
  tshirt: u("photo-1521572163474-6864f9cf17ab"),
  shirt: u("photo-1598033129183-c4f50c736f10"),
  dress: u("photo-1566174053879-31528523f8ae"),
  saree: u("photo-1583391733957-3750e2b408d8"),
  panjabi: u("photo-1594938298603-c8148c4dae35"),
  suit: u("photo-1594938298603-c8148c4dae35", 900),
  sneaker1: u("photo-1542291026-7eec264c27ff"),
  sneaker2: u("photo-1549298916-b41d501d3772"),
  bag: u("photo-1553062407-98eeb64c6a62"),
  camp: u("photo-1504851149312-7a075b496cc7"),
  drone: u("photo-1507580382020-4dd4f2c1b3a0"),
};

export {
  DEV_ADMIN_PHONE,
  DEV_ADMIN_PASSWORD,
  DEV_CUSTOMER_PHONE,
  DEV_CUSTOMER_PASSWORD,
} from "../src/config/dev-credentials";

export const categorySeeds = [
  { name: "Electronics", slug: "electronics", image: IMG.phone, parent: null, featured: 1 },
  { name: "Mobile & Tablets", slug: "mobile-tablets", parent: "electronics", featured: 0 },
  { name: "Smartphones", slug: "smartphones", parent: "mobile-tablets", image: IMG.phone, featured: 1 },
  { name: "Tablets", slug: "tablets", parent: "mobile-tablets", image: IMG.tablet, featured: 0 }, // IMG.tablet below
  { name: "Audio & Wearables", slug: "audio-wearables", parent: "electronics", featured: 0 },
  { name: "Headphones & Earbuds", slug: "headphones-earbuds", parent: "audio-wearables", image: IMG.headphones, featured: 1 },
  { name: "Bluetooth Speakers", slug: "bluetooth-speakers", parent: "audio-wearables", image: IMG.speaker, featured: 0 },
  { name: "Smartwatches", slug: "smartwatches", parent: "audio-wearables", image: IMG.watch, featured: 0 },
  { name: "Computers & Accessories", slug: "computers-accessories", parent: "electronics", featured: 0 },
  { name: "Keyboards & Mice", slug: "keyboards-mice", parent: "computers-accessories", image: IMG.keyboard, featured: 0 },
  { name: "Chargers & Power", slug: "chargers-power", parent: "computers-accessories", image: IMG.charger, featured: 0 },
  { name: "TV & Home Entertainment", slug: "tv-home-entertainment", parent: "electronics", featured: 0 },
  { name: "Televisions", slug: "televisions", parent: "tv-home-entertainment", image: IMG.tv, featured: 1 },
  { name: "Soundbars", slug: "soundbars", parent: "tv-home-entertainment", image: IMG.soundbar, featured: 0 },
  { name: "Home & Kitchen Appliances", slug: "home-kitchen-appliances", image: IMG.kitchen, featured: 1 },
  { name: "Kitchen Appliances", slug: "kitchen-appliances", parent: "home-kitchen-appliances", featured: 0 },
  { name: "Air Fryers", slug: "air-fryers", parent: "kitchen-appliances", image: IMG.airfryer, featured: 1 },
  { name: "Blenders & Juicers", slug: "blenders-juicers", parent: "kitchen-appliances", image: IMG.blender, featured: 0 },
  { name: "Rice Cookers", slug: "rice-cookers", parent: "kitchen-appliances", image: IMG.ricecooker, featured: 0 },
  { name: "Coffee Makers", slug: "coffee-makers", parent: "kitchen-appliances", image: IMG.coffeemaker, featured: 0 },
  { name: "Cleaning Appliances", slug: "cleaning-appliances", parent: "home-kitchen-appliances", featured: 0 },
  { name: "Vacuum Cleaners", slug: "vacuum-cleaners", parent: "cleaning-appliances", image: IMG.vacuum, featured: 1 },
  { name: "Air Purifiers", slug: "air-purifiers", parent: "cleaning-appliances", image: IMG.airpurifier, featured: 0 },
  { name: "Small Appliances", slug: "small-appliances", parent: "home-kitchen-appliances", featured: 0 },
  { name: "Electric Kettles", slug: "electric-kettles", parent: "small-appliances", image: IMG.kettle, featured: 0 },
  { name: "Smart Home", slug: "smart-home", image: IMG.bulb, featured: 1 },
  { name: "Smart Lighting", slug: "smart-lighting", parent: "smart-home", featured: 0 },
  { name: "Smart Bulbs", slug: "smart-bulbs", parent: "smart-lighting", image: IMG.bulb, featured: 1 },
  { name: "Smart Lamps", slug: "smart-lamps", parent: "smart-lighting", image: IMG.lamp, featured: 0 },
  { name: "Smart Security", slug: "smart-security", parent: "smart-home", featured: 0 },
  { name: "Security Cameras", slug: "security-cameras", parent: "smart-security", image: IMG.cctv, featured: 1 },
  { name: "Smart Locks", slug: "smart-locks", parent: "smart-security", image: IMG.lock, featured: 0 },
  { name: "Fashion", slug: "fashion", image: IMG.fashionStore, featured: 1 },
  { name: "Men's Fashion", slug: "mens-fashion", parent: "fashion", featured: 0 },
  { name: "Panjabi", slug: "panjabi", parent: "mens-fashion", image: IMG.panjabi, featured: 1 },
  { name: "Formal Shirts", slug: "formal-shirts", parent: "mens-fashion", image: IMG.tshirt, featured: 0 },
  { name: "Women's Fashion", slug: "womens-fashion", parent: "fashion", featured: 0 },
  { name: "Sarees", slug: "sarees", parent: "womens-fashion", image: IMG.saree, featured: 1 },
  { name: "Dresses", slug: "dresses", parent: "womens-fashion", image: IMG.dress, featured: 0 },
  { name: "Sports & Lifestyle", slug: "sports-lifestyle", image: IMG.sneaker1, featured: 0 },
  { name: "Footwear", slug: "footwear", parent: "sports-lifestyle", featured: 0 },
  { name: "Sneakers", slug: "sneakers", parent: "footwear", image: IMG.sneaker1, featured: 1 },
];

// IMG.tablet defined inline above via u()
export const brandSeeds = [
  { name: "Apple", slug: "apple", country: "USA", website: "https://www.apple.com", featured: 1 },
  { name: "Samsung", slug: "samsung", country: "South Korea", website: "https://www.samsung.com", featured: 1 },
  { name: "Xiaomi", slug: "xiaomi", country: "China", website: "https://www.mi.com", featured: 1 },
  { name: "Sony", slug: "sony", country: "Japan", website: "https://www.sony.com", featured: 0 },
  { name: "JBL", slug: "jbl", country: "USA", website: "https://www.jbl.com", featured: 1 },
  { name: "Philips", slug: "philips", country: "Netherlands", website: "https://www.philips.com", featured: 0 },
  { name: "TP-Link", slug: "tp-link", country: "China", website: "https://www.tp-link.com", featured: 0 },
  { name: "Anker", slug: "anker", country: "USA", website: "https://www.anker.com", featured: 1 },
  { name: "Baseus", slug: "baseus", country: "China", website: "https://www.baseus.com", featured: 0 },
  { name: "Walton", slug: "walton", country: "Bangladesh", website: "https://www.waltonbd.com", featured: 0 },
];

export const collectionSeeds = [
  { name: "New Arrivals", slug: "new-arrivals", desc: "Fresh from our suppliers — the latest drops.", featured: 1 },
  { name: "Best Sellers", slug: "best-sellers", desc: "The products everyone is talking about.", featured: 1 },
  { name: "Smart Home Picks", slug: "smart-home-picks", desc: "Connect, control, enjoy.", featured: 0 },
  { name: "Home Essentials", slug: "home-essentials", desc: "Everyday appliances for a smarter home.", featured: 0 },
  { name: "Tech Deals", slug: "tech-deals", desc: "Genuine markdowns on popular tech.", featured: 1 },
  { name: "Eid Collection", slug: "eid-collection", desc: "Festive fashion favourites.", featured: 0 },
];

export const vendorSeeds = [
  { name: "Dhaka Tech Hub", slug: "dhaka-tech-hub", contact: "Rafi Ahmed", phone: "01711000001", email: "dhakatech@example.dev", address: "Uttara, Dhaka" },
  { name: "Smart Living BD", slug: "smart-living-bd", contact: "Sadia Islam", phone: "01711000002", email: "smartliving@example.dev", address: "Dhanmondi, Dhaka" },
  { name: "Digital World BD", slug: "digital-world-bd", contact: "Mehedi Hasan", phone: "01711000003", email: "digitalworld@example.dev", address: "Elephant Road, Dhaka" },
  { name: "Home Essentials BD", slug: "home-essentials-bd", contact: "Nusrat Jahan", phone: "01711000004", email: "homeessentials@example.dev", address: "Mirpur, Dhaka" },
  { name: "Gadget House BD", slug: "gadget-house-bd", contact: "Tanvir Ahmed", phone: "01711000005", email: "gadgethouse@example.dev", address: "Gulshan, Dhaka" },
];

export const supplierSeeds = [
  { name: "Tech Source BD", slug: "tech-source-bd", contact: "Kamal Hossain", phone: "01712000001", email: "techsource@example.dev", address: "Kawran Bazar, Dhaka" },
  { name: "Global Electronics Supply", slug: "global-electronics-supply", contact: "Sabbir Rahman", phone: "01712000002", email: "globalelectronics@example.dev", address: "Agargaon, Dhaka" },
  { name: "Dhaka Wholesale Hub", slug: "dhaka-wholesale-hub", contact: "Riaz Uddin", phone: "01712000003", email: "wholesalehub@example.dev", address: "Islampur, Dhaka" },
  { name: "Smart Product Distribution", slug: "smart-product-distribution", contact: "Mou Akter", phone: "01712000004", email: "smartdistro@example.dev", address: "Tejgaon, Dhaka" },
  { name: "Style Mart BD", slug: "style-mart-bd", contact: "Shakil Khan", phone: "01712000005", email: "stylemart@example.dev", address: "Gulisthan, Dhaka" },
];

export const colorSeeds = [
  { name: "Black", displayName: "Black", hex: "#1a1a1a" },
  { name: "White", displayName: "White", hex: "#f5f5f5" },
  { name: "Silver", displayName: "Silver", hex: "#c0c0c0" },
  { name: "Gray", displayName: "Gray", hex: "#808080" },
  { name: "Blue", displayName: "Blue", hex: "#2b6cb0" },
  { name: "Navy", displayName: "Navy", hex: "#1e3a5f" },
  { name: "Red", displayName: "Red", hex: "#c53030" },
  { name: "Green", displayName: "Green", hex: "#2f855a" },
  { name: "Gold", displayName: "Gold", hex: "#d4af37" },
];

export const sizeSeeds = [
  { name: "XS", type: "clothing" },
  { name: "S", type: "clothing" },
  { name: "M", type: "clothing" },
  { name: "L", type: "clothing" },
  { name: "XL", type: "clothing" },
  { name: "XXL", type: "clothing" },
  { name: "38", type: "shoes" },
  { name: "39", type: "shoes" },
  { name: "40", type: "shoes" },
  { name: "41", type: "shoes" },
  { name: "42", type: "shoes" },
  { name: "43", type: "shoes" },
  { name: "44", type: "shoes" },
  { name: "Small", type: "general" },
  { name: "Medium", type: "general" },
  { name: "Large", type: "general" },
];