import {
  BadgePercent,
  Boxes,
  CreditCard,
  FolderOpen,
  Flame,
  LayoutTemplate,
  Megaphone,
  Package,
  ShoppingBag,
  ShoppingBasket,
  ShieldCheck,
  Sparkles,
  Star,
  Store,
  Tags,
  Timer,
  TrendingUp,
  Truck,
  UserRound,
  type LucideIcon,
} from 'lucide-react'
import type { HomepageSectionType } from '../../../types/homepage'

export const SECTION_META: Record<HomepageSectionType, { label: string; icon: LucideIcon; description: string }> = {
  hero: { label: 'Hero Carousel', icon: LayoutTemplate, description: 'Full-width rotating banner slides' },
  trust_strip: { label: 'Trust Strip', icon: BadgePercent, description: 'Icon perks — delivery, warranty, support' },
  categories: { label: 'Categories', icon: Tags, description: 'Shop-by-category image grid' },
  category_products: { label: 'Category Products', icon: ShoppingBasket, description: 'Products picked automatically from a selected category' },
  promo_banner: { label: 'Promo Banner', icon: Megaphone, description: 'Single promo banner from Banners manager' },
  flash_deals: { label: 'Flash Deals', icon: Timer, description: 'Discounted products with live countdown' },
  featured: { label: 'Featured Products', icon: Sparkles, description: 'Products marked as featured' },
  best_sellers: { label: 'Best Sellers', icon: ShoppingBag, description: 'Top products by real order volume' },
  brands: { label: 'Brands', icon: Store, description: 'Scrolling logo marquee of active brands' },
  collections: { label: 'Collections', icon: FolderOpen, description: 'Curated collection banner tiles' },
  trending: { label: 'Trending', icon: TrendingUp, description: 'Products marked as trending' },
  new_arrivals: { label: 'New Arrivals', icon: Package, description: 'Most recently added products' },
  limited_edition: { label: 'Limited Edition', icon: ShieldCheck, description: 'Products marked as limited edition' },
  official: { label: 'Official Products', icon: Star, description: 'Products marked as official' },
  hot_deals: { label: 'Hot Deals', icon: Flame, description: 'Products marked as hot deals' },
  emi_available: { label: 'EMI Available', icon: CreditCard, description: 'Products available for EMI payment' },
  recommendations: { label: 'Recommended for You', icon: UserRound, description: 'Personalized picks for signed-in shoppers' },
  why_choose_us: { label: 'Why Choose Us', icon: Star, description: 'Value proposition icon cards' },
  reviews: { label: 'Customer Reviews', icon: Boxes, description: 'Approved reviews carousel' },
  newsletter: { label: 'Newsletter', icon: Truck, description: 'Email capture CTA block' },
}

export const SECTION_ORDER: HomepageSectionType[] = [
  'hero',
  'trust_strip',
  'categories',
  'category_products',
  'new_arrivals',
  'promo_banner',
  'featured',
  'brands',
  'collections',
  'flash_deals',
  'best_sellers',
  'trending',
  'limited_edition',
  'official',
  'hot_deals',
  'emi_available',
  'recommendations',
  'why_choose_us',
  'reviews',
  'newsletter',
]
