<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }} — Mama Bazar</title>
    <style>
        @page { size: A4 landscape; margin: 10mm 12mm; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9.5px; color: #1e293b; line-height: 1.4; }
        .header { width: 100%; border-bottom: 2px solid #0f4d2c; padding-bottom: 8px; margin-bottom: 12px; }
        .header td { vertical-align: top; }
        .brand { font-size: 18px; font-weight: bold; color: #0f4d2c; }
        .meta { font-size: 8.5px; color: #64748b; }
        .title { text-align: right; }
        .title h1 { font-size: 16px; color: #0f4d2c; margin: 0 0 4px 0; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 8px; font-weight: bold; text-transform: uppercase; }
        .badge-success { background: #dcfce7; color: #15803d; }
        .badge-failure { background: #fee2e2; color: #b91c1c; }
        .badge-pending { background: #fef3c7; color: #b45309; }
        .badge-module { background: #f1f5f9; color: #475569; }
        table.records { width: 100%; border-collapse: collapse; font-size: 8.5px; margin-top: 8px; }
        table.records th { background: #0f4d2c; color: #ffffff; padding: 6px 6px; text-align: left; font-size: 8px; text-transform: uppercase; letter-spacing: 0.5px; }
        table.records td { padding: 5px 6px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        table.records tr:nth-child(even) td { background-color: #f8fafc; }
        .summary-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; padding: 8px 12px; margin-bottom: 10px; font-size: 8.5px; }
        .footer { margin-top: 15px; border-top: 1px solid #cbd5e1; padding-top: 6px; text-align: center; font-size: 8px; color: #94a3b8; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; }
    </style>
</head>
<body>

<table class="header">
    <tr>
        <td style="width: 50%;">
            <div class="brand">MAMA BAZAR</div>
            <div class="meta">
                Administrative Activity Monitoring & Security Audit Trail<br>
                Official Super Admin Operational Intelligence Report
            </div>
        </td>
        <td class="title" style="width: 50%;">
            <h1>{{ $title }}</h1>
            <div class="meta">
                Generated: {{ $generatedAt }}<br>
                Generated By: {{ $generatedBy }}
            </div>
        </td>
    </tr>
</table>

<div class="summary-box">
    <strong>Report Scope & Parameters:</strong>
    Date Range: {{ $filters['from'] ?? 'Earliest' }} to {{ $filters['to'] ?? 'Latest' }} |
    Module: {{ ucfirst($filters['module'] ?? 'All') }} |
    Status: {{ ucfirst($filters['status'] ?? 'All') }} |
    Total Tracked Records: <strong>{{ number_format($totalMatching) }}</strong>
    @if($totalMatching > 500)
        (Displaying top 500 records in PDF export)
    @endif
</div>

<table class="records">
    <thead>
        <tr>
            <th style="width: 13%;">Timestamp</th>
            <th style="width: 14%;">Actor</th>
            <th style="width: 16%;">Event / Action</th>
            <th style="width: 10%;">Module</th>
            <th style="width: 12%;">Target</th>
            <th style="width: 8%;">Status</th>
            <th style="width: 12%;">Source / IP</th>
            <th style="width: 15%;">Location</th>
        </tr>
    </thead>
    <tbody>
        @forelse($activities as $act)
            <tr>
                <td>{{ optional($act->occurred_at)->format('Y-m-d H:i:s') }}</td>
                <td>
                    <strong>{{ $act->actor_name ?: 'System' }}</strong>
                    @if($act->actor_role)<br><span style="color:#64748b; font-size:7.5px;">[{{ strtoupper($act->actor_role) }}]</span>@endif
                </td>
                <td>
                    <strong>{{ $act->human_action }}</strong>
                    @if($act->description)<br><span style="color:#64748b; font-size:7.5px;">{{ \Illuminate\Support\Str::limit($act->description, 50) }}</span>@endif
                </td>
                <td><span class="badge badge-module">{{ ucfirst($act->module) }}</span></td>
                <td>{{ $act->subject_type ? $act->subject_type . ' #' . $act->subject_id : '—' }}</td>
                <td>
                    <span class="badge badge-{{ $act->status }}">
                        {{ strtoupper($act->status) }}
                    </span>
                </td>
                <td>
                    <span style="font-family: monospace;">{{ $act->ip_address ?: '—' }}</span>
                    <br><span style="color:#64748b; font-size:7.5px;">[{{ ucfirst($act->source) }}]</span>
                </td>
                <td>{{ $act->location ?: 'Location unavailable' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="8" style="text-align: center; padding: 15px; color: #94a3b8;">
                    No activity logs recorded matching the specified filter criteria.
                </td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Mama Bazar E-Commerce Administration — Confidential Activity Audit Report — Strictly for Authorized Super Administrators
</div>

</body>
</html>
