<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $customer->name }} (ID: {{ $customer->id }}) — Customer 360° Profile</title>
    <style>
        @page { size: A4 portrait; margin: 12mm 15mm; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9.5px; color: #1e293b; line-height: 1.4; }
        .header { width: 100%; border-bottom: 2px solid #0f4d2c; padding-bottom: 8px; margin-bottom: 12px; }
        .header td { vertical-align: top; }
        .brand { font-size: 20px; font-weight: bold; color: #0f4d2c; }
        .meta { font-size: 8px; color: #64748b; }
        .title { text-align: right; }
        .title h1 { font-size: 16px; color: #0f4d2c; margin: 0 0 4px 0; }
        .section-title { font-size: 11px; font-weight: bold; color: #0f4d2c; border-bottom: 1.5px solid #cbd5e1; padding-bottom: 3px; margin: 14px 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px; }
        .profile-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        .profile-table td { padding: 4px 8px; border: 1px solid #e2e8f0; font-size: 9px; }
        .profile-label { background: #f8fafc; font-weight: bold; color: #475569; width: 22%; }
        .metrics-grid { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        .metrics-grid td { width: 33.33%; padding: 8px; background: #f8fafc; border: 1px solid #e2e8f0; text-align: center; }
        .metric-val { font-size: 15px; font-weight: bold; color: #0f4d2c; margin-top: 2px; }
        .metric-lbl { font-size: 8px; text-transform: uppercase; color: #64748b; font-weight: 600; }
        table.data-table { width: 100%; border-collapse: collapse; font-size: 8.5px; margin-top: 6px; margin-bottom: 10px; }
        table.data-table th { background: #0f4d2c; color: #ffffff; padding: 5px 6px; text-align: left; font-size: 8px; text-transform: uppercase; }
        table.data-table td { padding: 5px 6px; border-bottom: 1px solid #e2e8f0; }
        table.data-table tr:nth-child(even) td { background-color: #f8fafc; }
        .badge { display: inline-block; padding: 2px 5px; border-radius: 3px; font-size: 7.5px; font-weight: bold; text-transform: uppercase; }
        .badge-active { background: #dcfce7; color: #15803d; }
        .badge-inactive { background: #fee2e2; color: #b91c1c; }
        .footer { margin-top: 20px; border-top: 1px solid #cbd5e1; padding-top: 6px; text-align: center; font-size: 8px; color: #94a3b8; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; }
    </style>
</head>
<body>

<table class="header">
    <tr>
        <td style="width: 50%;">
            <div class="brand">MAMA BAZAR</div>
            <div class="meta">
                Customer 360° Profile & Lifetime Intelligence Dossier<br>
                Official E-Commerce Storefront & Admin Record
            </div>
        </td>
        <td class="title" style="width: 50%;">
            <h1>Customer Profile Dossier</h1>
            <div class="meta">
                Customer ID: #{{ $customer->id }}<br>
                Generated: {{ $generatedAt }}<br>
                Generated By: {{ $generatedBy }}
            </div>
        </td>
    </tr>
</table>

<div class="section-title">1. Customer Identification & Contact Info</div>
<table class="profile-table">
    <tr>
        <td class="profile-label">Full Name</td>
        <td><strong>{{ $customer->name }}</strong></td>
        <td class="profile-label">Account Status</td>
        <td>
            <span class="badge {{ $customer->status === 'active' ? 'badge-active' : 'badge-inactive' }}">
                {{ ucfirst($customer->status) }}
            </span>
        </td>
    </tr>
    <tr>
        <td class="profile-label">Primary Phone</td>
        <td>{{ $customer->phone }}</td>
        <td class="profile-label">Email Address</td>
        <td>{{ $customer->email ?: 'Not Provided' }}</td>
    </tr>
    <tr>
        <td class="profile-label">Registration Date</td>
        <td>{{ $customer->created_at ? $customer->created_at->format('M d, Y h:i A') : 'N/A' }}</td>
        <td class="profile-label">Last Login</td>
        <td>{{ $customer->last_login_at ? $customer->last_login_at->format('M d, Y h:i A') : 'Never Logged In' }}</td>
    </tr>
    <tr>
        <td class="profile-label">Shipping Area</td>
        <td>{{ $customer->shipping_area ?: 'Not Specified' }}</td>
        <td class="profile-label">Default Address</td>
        <td>{{ $customer->shipping_address ?: 'No primary address configured' }}</td>
    </tr>
</table>

<div class="section-title">2. Lifetime Financial & Order Metrics</div>
<table class="metrics-grid">
    <tr>
        <td>
            <div class="metric-lbl">Total Orders Placed</div>
            <div class="metric-val">{{ $metrics['totalOrders'] ?? 0 }}</div>
        </td>
        <td>
            <div class="metric-lbl">Lifetime Spend (CLV)</div>
            <div class="metric-val">৳{{ number_format($metrics['totalSpent'] ?? 0, 2) }}</div>
        </td>
        <td>
            <div class="metric-lbl">Average Order Value (AOV)</div>
            <div class="metric-val">৳{{ number_format($metrics['aov'] ?? 0, 2) }}</div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="metric-lbl">Pending / Processing</div>
            <div class="metric-val" style="color: #b45309;">{{ $metrics['pendingOrders'] ?? 0 }}</div>
        </td>
        <td>
            <div class="metric-lbl">Delivered / Completed</div>
            <div class="metric-val" style="color: #15803d;">{{ $metrics['completedOrders'] ?? 0 }}</div>
        </td>
        <td>
            <div class="metric-lbl">Cancelled / Returned</div>
            <div class="metric-val" style="color: #b91c1c;">{{ $metrics['cancelledOrders'] ?? 0 }}</div>
        </td>
    </tr>
</table>

<div class="section-title">3. Order History (Most Recent)</div>
<table class="data-table">
    <thead>
        <tr>
            <th style="width: 15%;">Order #</th>
            <th style="width: 14%;">Date</th>
            <th style="width: 25%;">Items Summary</th>
            <th style="width: 14%; text-align: right;">Total Price</th>
            <th style="width: 16%;">Payment</th>
            <th style="width: 16%;">Status</th>
        </tr>
    </thead>
    <tbody>
        @forelse($orders->take(15) as $ord)
            <tr>
                <td><strong>#{{ $ord->order_id }}</strong></td>
                <td>{{ $ord->created_at ? $ord->created_at->format('M d, Y') : '—' }}</td>
                <td>
                    @if($ord->items && $ord->items->count())
                        {{ $ord->items->pluck('product_title')->take(2)->implode(', ') }}
                        @if($ord->items->count() > 2)
                            <span style="color: #64748b;">+{{ $ord->items->count() - 2 }} more</span>
                        @endif
                    @else
                        1 item
                    @endif
                </td>
                <td style="text-align: right; font-weight: bold;">৳{{ number_format((float) $ord->total_price, 2) }}</td>
                <td>{{ strtoupper($ord->payment_method ?? 'COD') }} ({{ ucfirst($ord->payment_status ?? 'pending') }})</td>
                <td>{{ ucfirst($ord->status) }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="6" style="text-align: center; padding: 10px; color: #64748b;">No orders placed by this customer yet.</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="section-title">4. Saved Address Book</div>
<table class="data-table">
    <thead>
        <tr>
            <th style="width: 20%;">Recipient</th>
            <th style="width: 15%;">Phone</th>
            <th style="width: 15%;">Division / District</th>
            <th style="width: 40%;">Street Address & Area</th>
            <th style="width: 10%;">Default</th>
        </tr>
    </thead>
    <tbody>
        @forelse($addresses as $addr)
            <tr>
                <td><strong>{{ $addr->recipient_name }}</strong></td>
                <td>{{ $addr->phone }}</td>
                <td>{{ $addr->division }} / {{ $addr->district }}</td>
                <td>{{ $addr->formatted_address ?: $addr->address }}</td>
                <td>{{ $addr->is_default ? 'YES' : 'NO' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5" style="text-align: center; padding: 10px; color: #64748b;">No saved addresses found in address book.</td>
            </tr>
        @endforelse
    </tbody>
</table>

@if($notes && count($notes) > 0)
    <div class="section-title">5. Internal Administrator Notes</div>
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 18%;">Date</th>
                <th style="width: 20%;">Admin Staff</th>
                <th style="width: 62%;">Note</th>
            </tr>
        </thead>
        <tbody>
            @foreach($notes as $note)
                <tr>
                    <td>{{ $note->created_at ? $note->created_at->format('M d, Y h:i A') : '—' }}</td>
                    <td><strong>{{ $note->admin?->name ?? 'Staff Admin' }}</strong></td>
                    <td>{{ $note->note }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endif

<div class="footer">
    Mama Bazar Customer Management System — Confidential Business Dossier.<br>
    {{ $branding['tagline'] ?? 'Software crafted by Bornosoft' }} — {{ $branding['url'] ?? 'https://bornosoft.bd/' }}
</div>

</body>
</html>
