<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }} — Mama Bazar</title>
    <style>
        @page { size: A4 landscape; margin: 10mm 12mm; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9px; color: #1e293b; line-height: 1.4; }
        .header { width: 100%; border-bottom: 2px solid #0f4d2c; padding-bottom: 8px; margin-bottom: 12px; }
        .header td { vertical-align: top; }
        .brand { font-size: 18px; font-weight: bold; color: #0f4d2c; }
        .meta { font-size: 8px; color: #64748b; }
        .title { text-align: right; }
        .title h1 { font-size: 15px; color: #0f4d2c; margin: 0 0 4px 0; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 7.5px; font-weight: bold; text-transform: uppercase; }
        .badge-active { background: #dcfce7; color: #15803d; }
        .badge-inactive { background: #fee2e2; color: #b91c1c; }
        table.records { width: 100%; border-collapse: collapse; font-size: 8px; margin-top: 8px; }
        table.records th { background: #0f4d2c; color: #ffffff; padding: 6px 5px; text-align: left; font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.5px; }
        table.records td { padding: 5px 5px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        table.records tr:nth-child(even) td { background-color: #f8fafc; }
        .summary-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; padding: 8px 12px; margin-bottom: 10px; font-size: 8.5px; }
        .footer { margin-top: 15px; border-top: 1px solid #cbd5e1; padding-top: 6px; text-align: center; font-size: 8px; color: #94a3b8; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; }
    </style>
</head>
<body>

<table class="header">
    <tr>
        <td style="width: 50%;">
            <div class="brand">MAMA BAZAR</div>
            <div class="meta">
                Customer 360° Management & Accounts Directory<br>
                Official Customer Base Analysis & Directory Export
            </div>
        </td>
        <td class="title" style="width: 50%;">
            <h1>{{ $title }}</h1>
            <div class="meta">
                Generated: {{ $generatedAt }}<br>
                Generated By: {{ $generatedBy }}
            </div>
        </td>
    </tr>
</table>

<div class="summary-box">
    <strong>Directory Scope & Parameters:</strong>
    Status: {{ ucfirst($filters['status'] ?? 'All') }} |
    Search Query: {{ $filters['search'] ?? 'None' }} |
    Registration Range: {{ $filters['date_from'] ?? 'Earliest' }} to {{ $filters['date_to'] ?? 'Latest' }} |
    Total Customers Displayed: <strong>{{ count($customers) }}</strong>
</div>

<table class="records">
    <thead>
        <tr>
            <th style="width: 4%;">#</th>
            <th style="width: 18%;">Customer Name</th>
            <th style="width: 12%;">Phone</th>
            <th style="width: 16%;">Email</th>
            <th style="width: 7%;">Status</th>
            <th style="width: 10%;">Registered</th>
            <th style="width: 7%; text-align: center;">Orders</th>
            <th style="width: 10%; text-align: right;">Total Spent</th>
            <th style="width: 8%; text-align: right;">AOV</th>
            <th style="width: 8%;">Last Order</th>
        </tr>
    </thead>
    <tbody>
        @forelse($customers as $c)
            @php
                $spent = (float)($c->total_spent ?? 0);
                $ordersCnt = (int)($c->valid_orders_count ?? $c->orders_count ?? 0);
                $aov = $ordersCnt > 0 ? ($spent / $ordersCnt) : 0;
            @endphp
            <tr>
                <td>{{ $c->id }}</td>
                <td><strong>{{ $c->name }}</strong></td>
                <td>{{ $c->phone }}</td>
                <td>{{ $c->email ?: '—' }}</td>
                <td>
                    <span class="badge {{ $c->status === 'active' ? 'badge-active' : 'badge-inactive' }}">
                        {{ $c->status }}
                    </span>
                </td>
                <td>{{ $c->created_at ? $c->created_at->format('M d, Y') : '—' }}</td>
                <td style="text-align: center; font-weight: bold; color: #0f4d2c;">{{ $c->orders_count ?? 0 }}</td>
                <td style="text-align: right; font-weight: bold;">৳{{ number_format($spent, 2) }}</td>
                <td style="text-align: right;">৳{{ number_format($aov, 2) }}</td>
                <td>{{ $c->last_order_at ? \Carbon\Carbon::parse($c->last_order_at)->format('M d, Y') : 'Never' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="10" style="text-align: center; padding: 15px; color: #64748b;">No customers match the selected filter criteria.</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Mama Bazar Customer Management System — Confidential Business Records.<br>
    {{ $branding['tagline'] ?? 'Software crafted by Bornosoft' }} — {{ $branding['url'] ?? 'https://bornosoft.bd/' }}
</div>

</body>
</html>
