<?php

namespace Database\Seeders;

class BrandData
{
    public static function get(): array
    {
        return [
            ['name' => 'Apple', 'slug' => 'apple', 'country' => 'USA', 'website' => 'https://apple.com', 'desc' => 'Pioneering consumer electronics, iPhones, MacBooks, iPads, and wearables.'],
            ['name' => 'Samsung', 'slug' => 'samsung', 'country' => 'South Korea', 'website' => 'https://samsung.com', 'desc' => 'Global leader in Galaxy smartphones, OLED displays, memory chips, and home appliances.'],
            ['name' => 'Xiaomi', 'slug' => 'xiaomi', 'country' => 'China', 'website' => 'https://mi.com', 'desc' => 'Innovative smartphones, smart home IoT ecosystem, and lifestyle electronics.'],
            ['name' => 'OnePlus', 'slug' => 'oneplus', 'country' => 'China', 'website' => 'https://oneplus.com', 'desc' => 'Never Settle flagship smartphones and premium wireless audio gear.'],
            ['name' => 'Sony', 'slug' => 'sony', 'country' => 'Japan', 'website' => 'https://sony.com', 'desc' => 'Industry-leading noise cancelling audio, Alpha cameras, PlayStation, and BRAVIA TVs.'],
            ['name' => 'LG', 'slug' => 'lg', 'country' => 'South Korea', 'website' => 'https://lg.com', 'desc' => 'Life\'s Good premier OLED TVs, home appliances, and gaming monitors.'],
            ['name' => 'Google', 'slug' => 'google', 'country' => 'USA', 'website' => 'https://store.google.com', 'desc' => 'Google Pixel smartphones, Nest smart home devices, and Chromecast.'],
            ['name' => 'Asus', 'slug' => 'asus', 'country' => 'Taiwan', 'website' => 'https://asus.com', 'desc' => 'ROG gaming hardware, ZenBook ultrabooks, and high-performance motherboards.'],
            ['name' => 'Dell', 'slug' => 'dell', 'country' => 'USA', 'website' => 'https://dell.com', 'desc' => 'XPS ultrabooks, Alienware gaming rigs, and enterprise business displays.'],
            ['name' => 'HP', 'slug' => 'hp', 'country' => 'USA', 'website' => 'https://hp.com', 'desc' => 'Spectre laptops, OMEN gaming systems, printers, and desktop computing.'],
            ['name' => 'Lenovo', 'slug' => 'lenovo', 'country' => 'China', 'website' => 'https://lenovo.com', 'desc' => 'World-renowned ThinkPad business laptops, Legion gaming, and tablets.'],
            ['name' => 'Acer', 'slug' => 'acer', 'country' => 'Taiwan', 'website' => 'https://acer.com', 'desc' => 'Predator gaming laptops, Nitro displays, and everyday computers.'],
            ['name' => 'MSI', 'slug' => 'msi', 'country' => 'Taiwan', 'website' => 'https://msi.com', 'desc' => 'True Gaming enthusiast motherboards, GPUs, and stealth gaming laptops.'],
            ['name' => 'Intel', 'slug' => 'intel', 'country' => 'USA', 'website' => 'https://intel.com', 'desc' => 'World leader in semiconductor processors and computing silicon.'],
            ['name' => 'AMD', 'slug' => 'amd', 'country' => 'USA', 'website' => 'https://amd.com', 'desc' => 'High-performance Ryzen CPUs and Radeon graphics architectures.'],
            ['name' => 'NVIDIA', 'slug' => 'nvidia', 'country' => 'USA', 'website' => 'https://nvidia.com', 'desc' => 'Pioneer of GPU-accelerated computing and GeForce RTX gaming graphics.'],
            ['name' => 'Kingston', 'slug' => 'kingston', 'country' => 'USA', 'website' => 'https://kingston.com', 'desc' => 'FURY gaming memory, high-speed RAM modules, and reliable SSD storage.'],
            ['name' => 'Western Digital', 'slug' => 'western-digital', 'country' => 'USA', 'website' => 'https://westerndigital.com', 'desc' => 'WD Black and Blue NVMe SSDs and external storage solutions.'],
            ['name' => 'SanDisk', 'slug' => 'sandisk', 'country' => 'USA', 'website' => 'https://sandisk.com', 'desc' => 'Extreme portable SSDs, high-capacity microSD cards, and USB flash memory.'],
            ['name' => 'TP-Link', 'slug' => 'tp-link', 'country' => 'China', 'website' => 'https://tp-link.com', 'desc' => 'Archer WiFi 6 routers, Deco mesh networks, and Tapo smart home gadgets.'],
            ['name' => 'Logitech', 'slug' => 'logitech', 'country' => 'Switzerland', 'website' => 'https://logitech.com', 'desc' => 'MX Master mice, mechanical keyboards, StreamCam, and gaming gear.'],
            ['name' => 'Razer', 'slug' => 'razer', 'country' => 'USA', 'website' => 'https://razer.com', 'desc' => 'For Gamers. By Gamers. Premium gaming peripherals, mice, and keyboards.'],
            ['name' => 'Anker', 'slug' => 'anker', 'country' => 'China', 'website' => 'https://anker.com', 'desc' => 'World\'s #1 mobile charging brand, fast wall chargers, and Soundcore audio.'],
            ['name' => 'JBL', 'slug' => 'jbl', 'country' => 'USA', 'website' => 'https://jbl.com', 'desc' => 'Iconic Pro Sound portable bluetooth speakers, partyboxes, and soundbars.'],
            ['name' => 'Bose', 'slug' => 'bose', 'country' => 'USA', 'website' => 'https://bose.com', 'desc' => 'QuietComfort acoustic noise cancelling headphones and premium sound systems.'],
            ['name' => 'Canon', 'slug' => 'canon', 'country' => 'Japan', 'website' => 'https://canon.com', 'desc' => 'EOS R mirrorless digital cameras, RF lenses, and professional imaging.'],
            ['name' => 'Nikon', 'slug' => 'nikon', 'country' => 'Japan', 'website' => 'https://nikon.com', 'desc' => 'Z-series mirrorless cameras, Nikkor precision glass, and DSLR optics.'],
            ['name' => 'DJI', 'slug' => 'dji', 'country' => 'China', 'website' => 'https://dji.com', 'desc' => 'Aerial drones, Osmo action cameras, and Ronin handheld gimbals.'],
            ['name' => 'Philips', 'slug' => 'philips', 'country' => 'Netherlands', 'website' => 'https://philips.com', 'desc' => 'Electric shavers, Sonicare dental care, Hue smart lights, and kitchen gadgets.'],
            ['name' => 'Bosch', 'slug' => 'bosch', 'country' => 'Germany', 'website' => 'https://bosch.com', 'desc' => 'German precision engineering in kitchen appliances, dishwashers, and power tools.'],
            ['name' => 'Panasonic', 'slug' => 'panasonic', 'country' => 'Japan', 'website' => 'https://panasonic.com', 'desc' => 'Reliable microwave ovens, inverter ACs, groomers, and household electronics.'],
            ['name' => 'Dyson', 'slug' => 'dyson', 'country' => 'UK', 'website' => 'https://dyson.com', 'desc' => 'V15 cordless stick vacuums, Supersonic hair dryers, and air purifiers.'],
            ['name' => 'Haier', 'slug' => 'haier', 'country' => 'China', 'website' => 'https://haier.com', 'desc' => 'Smart frost-free refrigerators, inverter washing machines, and split air conditioning.'],
            ['name' => 'Walton', 'slug' => 'walton', 'country' => 'Bangladesh', 'website' => 'https://waltonbd.com', 'desc' => 'Leading Bangladeshi manufacturer of electronics, appliances, and smart tech.'],
            ['name' => 'Singer', 'slug' => 'singer', 'country' => 'USA', 'website' => 'https://singerbd.com', 'desc' => 'Heritage brand for home sewing machines, kitchen appliances, and TVs.'],
            ['name' => 'Tefal', 'slug' => 'tefal', 'country' => 'France', 'website' => 'https://tefal.com', 'desc' => 'World pioneer in non-stick thermo-spot cookware, steam irons, and air fryers.'],
            ['name' => 'IKEA', 'slug' => 'ikea', 'country' => 'Sweden', 'website' => 'https://ikea.com', 'desc' => 'Scandinavian minimalist flat-pack furniture, home decor, and cookware.'],
            ['name' => 'Nike', 'slug' => 'nike', 'country' => 'USA', 'website' => 'https://nike.com', 'desc' => 'Just Do It. World leader in running sneakers, athletic apparel, and streetwear.'],
            ['name' => 'Adidas', 'slug' => 'adidas', 'country' => 'Germany', 'website' => 'https://adidas.com', 'desc' => 'Three stripes performance footwear, Ultraboost, football cleats, and sports clothing.'],
            ['name' => 'Puma', 'slug' => 'puma', 'country' => 'Germany', 'website' => 'https://puma.com', 'desc' => 'Forever Faster athletic running shoes, sportswear, and lifestyle apparel.'],
            ['name' => 'Levi\'s', 'slug' => 'levis', 'country' => 'USA', 'website' => 'https://levi.com', 'desc' => 'Iconic 501 original denim jeans, trucker jackets, and timeless western apparel.'],
            ['name' => 'Zara', 'slug' => 'zara', 'country' => 'Spain', 'website' => 'https://zara.com', 'desc' => 'Contemporary runway-inspired fast fashion dresses, blazers, and menswear.'],
            ['name' => 'H&M', 'slug' => 'hm', 'country' => 'Sweden', 'website' => 'https://hm.com', 'desc' => 'Sustainable modern wardrobe basics, casual shirts, hoodies, and dresses.'],
            ['name' => 'Bata', 'slug' => 'bata', 'country' => 'Switzerland', 'website' => 'https://bata.com', 'desc' => 'Comfortable and durable family footwear, formal shoes, and leather sandals.'],
            ['name' => 'Apex', 'slug' => 'apex', 'country' => 'Bangladesh', 'website' => 'https://apexfootwearltd.com', 'desc' => 'Premium handcrafted leather formal shoes, loafers, and lifestyle footwear.'],
            ['name' => 'Casio', 'slug' => 'casio', 'country' => 'Japan', 'website' => 'https://casio.com', 'desc' => 'Indestructible G-Shock watches, Edifice chronographs, and digital timepieces.'],
            ['name' => 'Seiko', 'slug' => 'seiko', 'country' => 'Japan', 'website' => 'https://seikowatches.com', 'desc' => 'Pioneering automatic mechanical 5 Sports and Presage horology timepieces.'],
            ['name' => 'Fossil', 'slug' => 'fossil', 'country' => 'USA', 'website' => 'https://fossil.com', 'desc' => 'Vintage American leather bags, chronograph watches, and accessories.'],
            ['name' => 'Ray-Ban', 'slug' => 'ray-ban', 'country' => 'Italy', 'website' => 'https://ray-ban.com', 'desc' => 'Classic Aviator, Wayfarer, and Clubmaster polarized UV sunglasses.'],
            ['name' => 'L\'Oreal Paris', 'slug' => 'loreal-paris', 'country' => 'France', 'website' => 'https://lorealparis.com', 'desc' => 'Because You\'re Worth It. Global leader in skin serums, cosmetics, and hair care.'],
            ['name' => 'The Ordinary', 'slug' => 'the-ordinary', 'country' => 'Canada', 'website' => 'https://theordinary.com', 'desc' => 'Clinical formulations with integrity, Niacinamide, Retinol, and Hyaluronic Acid.'],
            ['name' => 'CeraVe', 'slug' => 'cerave', 'country' => 'USA', 'website' => 'https://cerave.com', 'desc' => 'Dermatologist developed cleansers and barrier-restoring ceramide lotions.'],
            ['name' => 'Nivea', 'slug' => 'nivea', 'country' => 'Germany', 'website' => 'https://nivea.com', 'desc' => 'Gentle skin moisturization, deep body lotions, and men\'s grooming care.'],
            ['name' => 'Dove', 'slug' => 'dove', 'country' => 'UK', 'website' => 'https://dove.com', 'desc' => 'Deeply nourishing beauty bars, hydrating body washes, and hair therapies.'],
            ['name' => 'Gillette', 'slug' => 'gillette', 'country' => 'USA', 'website' => 'https://gillette.com', 'desc' => 'The Best a Man Can Get. Fusion5 precision razors and shaving gels.'],
            ['name' => 'Braun', 'slug' => 'braun', 'country' => 'Germany', 'website' => 'https://braun.com', 'desc' => 'Series 9 Pro foil shavers, all-in-one beard styling kits, and grooming tools.'],
            ['name' => 'Nescafe', 'slug' => 'nescafe', 'country' => 'Switzerland', 'website' => 'https://nescafe.com', 'desc' => 'Gold Blend rich roasted coffee granules, espresso, and premium beans.'],
            ['name' => 'Twinings', 'slug' => 'twinings', 'country' => 'UK', 'website' => 'https://twinings.co.uk', 'desc' => 'Master tea blenders of Earl Grey, English Breakfast, and herbal infusions.'],
            ['name' => 'Ferrero Rocher', 'slug' => 'ferrero-rocher', 'country' => 'Italy', 'website' => 'https://ferrerorocher.com', 'desc' => 'Decadent whole hazelnut wrapped in crisp wafer and smooth milk chocolate.'],
            ['name' => 'PRAN', 'slug' => 'pran', 'country' => 'Bangladesh', 'website' => 'https://pranfoods.net', 'desc' => 'Quality aromatic Chinigura rice, fruit juices, confectionery, and spice staples.'],
            ['name' => 'Radhuni', 'slug' => 'radhuni', 'country' => 'Bangladesh', 'website' => 'https://squareconsumer.com', 'desc' => 'Pure cold-pressed mustard oil, ground spices, and authentic Bangladeshi seasonings.'],
            ['name' => 'Wilson', 'slug' => 'wilson', 'country' => 'USA', 'website' => 'https://wilson.com', 'desc' => 'Pro staff sports equipment, championship basketballs, and leather accessories.'],
            ['name' => 'Yonex', 'slug' => 'yonex', 'country' => 'Japan', 'website' => 'https://yonex.com', 'desc' => 'Astrox and Nanoflare world-championship badminton rackets and shuttlecocks.'],
            ['name' => 'Yamaha', 'slug' => 'yamaha', 'country' => 'Japan', 'website' => 'https://yamaha.com', 'desc' => 'Acoustic guitars, touch-sensitive digital pianos, and studio sound monitors.'],
            ['name' => 'Whiskas', 'slug' => 'whiskas', 'country' => 'USA', 'website' => 'https://whiskas.com', 'desc' => 'Nutritionally complete wet and dry food crafted for happy, healthy cats.'],
            ['name' => 'Pedigree', 'slug' => 'pedigree', 'country' => 'USA', 'website' => 'https://pedigree.com', 'desc' => 'Veterinarian formulated dog food kibble, dental sticks, and meat gravy cans.'],
        ];
    }
}
