<?php

namespace Database\Seeders;

class ProductCatalogDefinitionPart2
{
    public static function get(): array
    {
        return [
            // 26. Bags & Luggage
            [
                'cat_slug' => 'bags-luggage',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Samsonite Omni PC Hardside 28 Spinner Luggage', 'brand' => 'nike', 'sub' => 0, 'price' => 24500, 'sale' => 22500, 'stock' => 16, 'specs' => ['Shell' => '100% Polycarbonate micro-diamond scratch-resistant texture', 'Wheels' => 'Four multi-directional oversized dual spinner wheels', 'Lock' => 'Side-mounted TSA compatible combination lock', 'Expansion' => 'Expands 1.5" for added packing capacity']],
                    ['title' => 'American Tourister Curio Spinner 24 Check-in', 'brand' => 'adidas', 'sub' => 0, 'price' => 16500, 'sale' => 14999, 'stock' => 22, 'specs' => ['Design' => 'Retro record-groove concentric circle pattern', 'Material' => 'Durable lightweight polypropylene HS shell', 'Interior' => 'Cross ribbons and zippered divider with mesh pocket', 'Capacity' => '68 Liters volume']],
                    ['title' => 'The North Face Borealis Commuter Backpack 28L', 'brand' => 'nike', 'sub' => 1, 'price' => 11500, 'sale' => 10200, 'stock' => 30, 'specs' => ['Suspension' => 'FlexVent suspension system certified by ACA', 'Compartment' => 'Dedicated protective 15" laptop sleeve', 'Bungee' => 'External bungee-compression system with clips', 'Fabric' => '210D recycled nylon ripstop with non-PFC DWR finish']],
                    ['title' => 'Fossil Haskell Genuine Leather Messenger Bag', 'brand' => 'fossil', 'sub' => 2, 'price' => 18500, 'sale' => 16999, 'stock' => 14, 'specs' => ['Material' => '100% Rich full-grain cowhide leather', 'Hardware' => 'Estate brass finish metal buckles and zippers', 'Device' => 'Padded compartment fits up to 14" laptop and iPad', 'Strap' => 'Adjustable and detachable webbing shoulder strap']],
                    ['title' => 'Nike Brasilia Large Training Gym Duffle Bag 95L', 'brand' => 'nike', 'sub' => 3, 'price' => 4500, 'sale' => 3999, 'stock' => 40, 'specs' => ['Capacity' => 'Massive 95 Liters storage space', 'Shoe' => 'Zippered bottom compartment separates shoes and wet gear', 'Base' => 'Coated water-resistant bottom panel protects from puddles', 'Handles' => 'Dual carry handles and padded shoulder strap']],
                    ['title' => 'Peak Design Everyday Backpack 20L V2 Black', 'brand' => 'canon', 'sub' => 1, 'price' => 28500, 'sale' => 26000, 'stock' => 10, 'specs' => ['Hardware' => 'Patented MagLatch hardware provides lightning fast top access', 'Dividers' => '3 FlexFold origami dividers keep cameras and lenses organized', 'Weather' => '100% Recycled 400D weatherproof nylon canvas shell', 'Laptops' => 'Dedicated sleeve holds 15" laptop, tablet, and documents']],
                    ['title' => 'Puma Challenger Medium Duffle Bag 58L', 'brand' => 'puma', 'sub' => 3, 'price' => 3200, 'sale' => 2750, 'stock' => 35, 'specs' => ['Compartment' => 'Side zip pocket with shoe inlay and ventilation eyelet', 'D-Ring' => 'D-ring on main body for clipping accessories', 'Branding' => 'Bold Puma wordmark printed across front', 'Fabric' => 'Durable 100% polyester with PU backing']],
                    ['title' => 'Zara Minimalist Flap Laptop Backpack Black', 'brand' => 'zara', 'sub' => 1, 'price' => 5800, 'sale' => 4999, 'stock' => 28, 'specs' => ['Exterior' => 'Smooth matte technical rubberized polyurethane', 'Flap' => 'Magnetic foldover flap with double snap clasps', 'Pocket' => 'Back zip anti-theft security pocket for passport', 'Interior' => 'Reinforced 15.6" laptop compartment']],
                    ['title' => 'Apex Handcrafted Leather Travel Weekend Duffle', 'brand' => 'apex', 'sub' => 3, 'price' => 12500, 'sale' => 10999, 'stock' => 15, 'specs' => ['Leather' => 'Vegetable-tanned rich oily pull-up leather', 'Zippers' => 'Heavy-duty YKK antique brass dual zippers', 'Studs' => 'Reinforced base with 5 protective brass metal feet', 'Lining' => 'Tough cotton twill striped lining']],
                    ['title' => 'Fossil Defender Leather Top Zip Briefcase', 'brand' => 'fossil', 'sub' => 2, 'price' => 21000, 'sale' => 18999, 'stock' => 12, 'specs' => ['Construction' => 'Distressed vintage brown leather gets better with age', 'Pass-Through' => 'Rear trolley sleeve slides over rolling luggage handles', 'Pockets' => 'Organizer panel with pen loops, card slots, and key leash', 'Size' => 'Fits up to 15" MacBook Pro comfortably']],
                ]
            ],
            // 27. Eyewear & Sunglasses
            [
                'cat_slug' => 'eyewear-sunglasses',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Ray-Ban Original Wayfarer Classic Polarized Black', 'brand' => 'ray-ban', 'sub' => 1, 'price' => 18500, 'sale' => 16999, 'stock' => 25, 'specs' => ['Lens' => 'Polarized G-15 Green crystal glass lenses', 'UV' => '100% UV400 radiation protection with zero glare', 'Frame' => 'High quality polished black acetate frame', 'Heritage' => 'Since 1952 iconic rock & roll eyewear style']],
                    ['title' => 'Ray-Ban Aviator Classic Gold Frame Green Lens', 'brand' => 'ray-ban', 'sub' => 1, 'price' => 17500, 'sale' => 15999, 'stock' => 30, 'specs' => ['Frame' => 'Classic lightweight pilot teardrop gold metal wire frame', 'Pads' => 'Adjustable silicone nose pads for custom comfort', 'Temple' => 'Tubular metal temples with clear acetate tips', 'Size' => 'Standard 58mm lens diameter']],
                    ['title' => 'Ray-Ban Clubmaster Classic Browline Sunglasses', 'brand' => 'ray-ban', 'sub' => 1, 'price' => 18000, 'sale' => 16500, 'stock' => 20, 'specs' => ['Design' => 'Retro 1950s browline frame with metal rim', 'Acetate' => 'Glossy tortoiseshell acetate top brow and temples', 'Lenses' => 'Classic mineral glass lenses with logo signature', 'Bridge' => 'Curved metal bridge with coin edge detailing']],
                    ['title' => 'Fastrack Polarized Sport Wraparound Shades', 'brand' => 'casio', 'sub' => 3, 'price' => 2800, 'sale' => 2450, 'stock' => 45, 'specs' => ['Frame' => 'Aerodynamic wraparound polycarbonate sport frame', 'Polarization' => 'TAC polarized lenses eliminate harsh pavement glare', 'Grips' => 'Non-slip rubber temple inserts stay put during sweat', 'Weight' => '24g ultra-lightweight for running and cycling']],
                    ['title' => 'Gunnar Blue Light Blocking Computer Glasses', 'brand' => 'razer', 'sub' => 2, 'price' => 6500, 'sale' => 5800, 'stock' => 30, 'specs' => ['Filter' => 'Patented amber lens blocks 65% harmful blue light', 'Focus' => 'Slight +0.2 diopter magnification sharpens text', 'Anti-Glare' => 'Dual-sided anti-reflective coating reduces glare', 'Certification' => 'Doctor recommended for reducing digital eye strain']],
                    ['title' => 'Ray-Ban Round Metal Classic Gold Sunglasses', 'brand' => 'ray-ban', 'sub' => 1, 'price' => 17800, 'sale' => 16200, 'stock' => 22, 'specs' => ['Style' => 'Counter-culture 1960s circular wire rim silhouette', 'Lenses' => 'Legendary G-15 solid green lenses', 'Frame' => 'Thin lightweight gold-tone alloy', 'Fit' => 'Unisex bohemian fashion statement']],
                    ['title' => 'Zara Acetate Square Polarized Sunglasses Tortoise', 'brand' => 'zara', 'sub' => 0, 'price' => 3800, 'sale' => 3299, 'stock' => 35, 'specs' => ['Material' => '100% Cellulose acetate with tortoiseshell finish', 'Category' => 'Category 3 UV400 full sun protection', 'Hinges' => 'Durable 5-barrel metal hinges', 'Includes' => 'Hard protective folding case and microfiber cloth']],
                    ['title' => 'Nike Show X3 Elite Wraparound Sports Sunglasses', 'brand' => 'nike', 'sub' => 3, 'price' => 14500, 'sale' => 13200, 'stock' => 15, 'specs' => ['Optics' => 'Nike Elite one-piece shield lens for uninterrupted field of view', 'Ventilation' => 'Anti-fogging ventilation holes in top frame', 'Nosebridge' => 'Floating rubber nose pad optimizes airflow', 'Temples' => 'Pro-contour silicone grip temples']],
                    ['title' => 'H&M Blue Light Blocking Retro Clear Glasses', 'brand' => 'hm', 'sub' => 2, 'price' => 1450, 'sale' => 1250, 'stock' => 50, 'specs' => ['Lenses' => 'Clear acrylic lenses with blue light filter', 'Frame' => 'Clear transparent acetate rectangular frames', 'Look' => 'Intellectual chic look for office screen work', 'Protection' => 'UVA and UVB 400 protection']],
                    ['title' => 'Zara Retro Aviator Metal Sunglasses Silver', 'brand' => 'zara', 'sub' => 1, 'price' => 3200, 'sale' => 2799, 'stock' => 38, 'specs' => ['Frame' => 'Silver-tone stainless steel dual top brow bar', 'Lenses' => 'Smoke gradient tinted lenses', 'Comfort' => 'Clear silicone adjustable nose pads', 'Style' => 'Classic 70s pilot luxury']],
                ]
            ],
            // 28. Jewelry & Luxury Ornaments
            [
                'cat_slug' => 'jewelry-fashion-ornaments',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Swarovski Sparkling Dance Clover Pendant Necklace', 'brand' => 'fossil', 'sub' => 0, 'price' => 14500, 'sale' => 13200, 'stock' => 20, 'specs' => ['Concept' => 'Dancing stone suspended inside clover cage sparkles with every move', 'Plating' => 'Rose gold-tone plated chain with lobster clasp', 'Stones' => 'Precision cut clear Swarovski crystals', 'Length' => '38 cm adjustable chain with 5 cm extender']],
                    ['title' => 'Pandora Moments Snake Chain Charm Bracelet Silver', 'brand' => 'fossil', 'sub' => 3, 'price' => 9500, 'sale' => 8600, 'stock' => 25, 'specs' => ['Metal' => 'Handcrafted in genuine 925 sterling silver', 'Chain' => 'Signature barrel clasp snake chain with threading system', 'Capacity' => 'Holds 15-20 Pandora charms and clips', 'Sizing' => 'Available in multiple wrist circumferences']],
                    ['title' => 'Aarong Handcrafted Silver Filigree Jhumka Earrings', 'brand' => 'apex', 'sub' => 2, 'price' => 4800, 'sale' => 4200, 'stock' => 30, 'specs' => ['Art' => 'Authentic Cuttack silver wire filigree (Tarakasi)', 'Silver' => '92.5% Pure sterling silver with anti-tarnish coat', 'Design' => 'Two-tier bell jhumka with delicate dangling silver beads', 'Closure' => 'Secure hook with safety stopper']],
                    ['title' => 'Fossil Vintage Glitz Stainless Steel Slider Bracelet', 'brand' => 'fossil', 'sub' => 3, 'price' => 5800, 'sale' => 4999, 'stock' => 28, 'specs' => ['Material' => 'Polished stainless steel with pave crystal bar', 'Closure' => 'Adjustable slider bead fits any wrist size effortlessly', 'Finish' => 'Hypoallergenic tarnish-proof finish', 'Packaging' => 'Authentic Fossil collectible tin box']],
                    ['title' => 'Giva 925 Sterling Silver Classic Solitaire Ring', 'brand' => 'fossil', 'sub' => 1, 'price' => 3400, 'sale' => 2999, 'stock' => 35, 'specs' => ['Stone' => 'AAA+ grade 1-carat brilliant cut cubic zirconia', 'Setting' => '6-prong elevated crown setting for maximum light', 'Band' => '925 silver stamped with rhodium e-coat against tarnish', 'Certificate' => 'Authenticity certificate included']],
                    ['title' => 'Zara Multi-Layered Coin Chain Necklace Gold', 'brand' => 'zara', 'sub' => 0, 'price' => 2450, 'sale' => 2100, 'stock' => 40, 'specs' => ['Layers' => '3 attached chains (choker, paperclip link, and medallion)', 'Finish' => '18K Gold dipped high-gloss finish', 'Pendant' => 'Embossed vintage Roman coin medallion', 'Fastening' => 'Single lobster claw clasp with extender chain']],
                    ['title' => 'H&M 12-Piece Gold-Tone Hoop & Stud Earrings Set', 'brand' => 'hm', 'sub' => 2, 'price' => 1650, 'sale' => 1400, 'stock' => 50, 'specs' => ['Variety' => 'Mix of chunky huggie hoops, pearl studs, and crystal studs', 'Metal' => 'Nickel-tested hypoallergenic alloy', 'Versatility' => 'Perfect for curated ear stacks and multiple piercings', 'Posts' => 'Titanium hypoallergenic ear posts']],
                    ['title' => 'Fossil Heritage D-Link Rose Gold Steel Ring', 'brand' => 'fossil', 'sub' => 1, 'price' => 4200, 'sale' => 3700, 'stock' => 24, 'specs' => ['Inspiration' => 'Iconic Fossil D-link purse hardware motif', 'Material' => 'Solid stainless steel with durable rose gold ion plating', 'Band' => 'Interlocking bold curb link silhouette', 'Width' => '8mm statement band']],
                    ['title' => 'Aarong Traditional Nakshi Meenakari Choker Set', 'brand' => 'apex', 'sub' => 0, 'price' => 7500, 'sale' => 6700, 'stock' => 18, 'specs' => ['Technique' => 'Enamel Meenakari hand-painted detailing on reverse', 'Stones' => 'Faux kundan stones with faux pearl droplet fringe', 'Set' => 'Includes adjustable dori choker necklace and matching earrings', 'Style' => 'Royal Mughal heritage wedding ornament']],
                    ['title' => 'Zara Textured Chunky C-Shape Bangle Bracelet', 'brand' => 'zara', 'sub' => 3, 'price' => 2800, 'sale' => 2400, 'stock' => 32, 'specs' => ['Design' => 'Sculptural organic melted-metal textured finish', 'Profile' => 'C-shape cuff slips easily over wrist', 'Plating' => 'Warm vintage brushed gold tone', 'Weight' => 'Lightweight hollow construction for daily wear']],
                ]
            ],
            // 29. Kitchen Appliances
            [
                'cat_slug' => 'kitchen-appliances',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Philips XXL Airfryer HD9650/99 Twin TurboStar', 'brand' => 'philips', 'sub' => 0, 'price' => 28500, 'sale' => 26500, 'stock' => 18, 'specs' => ['Capacity' => '1.4 kg / 7.3 Liters XXL capacity cooks whole chicken', 'Technology' => 'Twin TurboStar technology captures and removes fat', 'Power' => '2225W rapid heating with instant warm function', 'Cleaning' => 'QuickClean basket with non-stick mesh dishwasher safe']],
                    ['title' => 'Panasonic 27L Convection Microwave Oven Inverter', 'brand' => 'panasonic', 'sub' => 1, 'price' => 29500, 'sale' => 27500, 'stock' => 15, 'specs' => ['Technology' => 'Panasonic Inverter technology for even, gradual heating', 'Modes' => 'Convection baking, grilling, defrost, and microwave', 'Menus' => '131 Auto cook menus with zero-oil recipes', 'Chamber' => 'Full stainless steel interior cavity 27 Liters']],
                    ['title' => 'Bosch TrueMixx Pro 1000W Mixer Grinder 4 Jars', 'brand' => 'bosch', 'sub' => 2, 'price' => 16500, 'sale' => 14999, 'stock' => 25, 'specs' => ['Motor' => '1000W 3-C series motor with 100% copper windings', 'Pounding' => 'PoundingBlade mimics traditional stone-pounding taste', 'Jars' => '4 stainless steel jars with active lid locks', 'Stability' => 'Strong suction feet keep machine stable during heavy grinding']],
                    ['title' => 'Tefal Ultrablend High Speed Blender 1500W', 'brand' => 'tefal', 'sub' => 2, 'price' => 19500, 'sale' => 17999, 'stock' => 14, 'specs' => ['Speed' => '45000 RPM high speed crushes ice into snow in seconds', 'Blades' => 'Tripl\'Ax Pro technology with 6 stainless steel blades', 'Programs' => '6 automatic digital programs with digital screen', 'Jar' => '2-Liter ultra-durable Tritan shatterproof jug']],
                    ['title' => 'Philips Daily Collection Electric Kettle 1.5L', 'brand' => 'philips', 'sub' => 3, 'price' => 3800, 'sale' => 3350, 'stock' => 45, 'specs' => ['Capacity' => '1.5 Liters rapid boiling stainless steel kettle', 'Safety' => 'Multi safety system against boil-dry with auto shut-off', 'Base' => '360-degree pirouette cordless power base', 'Filter' => 'Removable micro-mesh anti-calc filter on spout']],
                    ['title' => 'Panasonic Automatic Rice Cooker 2.2L SR-W22', 'brand' => 'panasonic', 'sub' => 3, 'price' => 5400, 'sale' => 4850, 'stock' => 35, 'specs' => ['Capacity' => '2.2 Liters (cooks up to 1.25 kg raw rice)', 'Pan' => 'Anodized aluminum inner cooking pan with thermal bridge', 'Function' => 'Automatic cooking and 5-hour keep warm function', 'Lid' => 'Stainless steel lid with heat-resistant handle']],
                    ['title' => 'Singer 2-Slice Pop-Up Bread Toaster with Defrost', 'brand' => 'singer', 'sub' => 0, 'price' => 2800, 'sale' => 2450, 'stock' => 40, 'specs' => ['Slots' => 'Wide self-centering slots accommodate thick bagel slices', 'Browning' => '7-level variable browning control knob', 'Functions' => 'Reheat, Defrost, and Cancel push buttons with LED lights', 'Tray' => 'Slide-out removable crumb tray for easy cleaning']],
                    ['title' => 'Philips Daily Collection Hand Blender Chopper Set', 'brand' => 'philips', 'sub' => 2, 'price' => 4500, 'sale' => 3999, 'stock' => 38, 'specs' => ['Power' => '550W reliable motor with ProMix triangular blade head', 'Accessory' => 'Includes compact chopper for onions and herbs, and beaker', 'Grip' => 'Slim ergonomic handle with single speed trigger switch', 'Release' => '2-button easy release system for dishwasher cleaning']],
                    ['title' => 'Tefal Express Compact Food Processor 800W', 'brand' => 'tefal', 'sub' => 2, 'price' => 12500, 'sale' => 11200, 'stock' => 20, 'specs' => ['Bowl' => '2.4L main bowl and 1.5L dedicated blender jar', 'Attachments' => 'Reversible slicing, shredding discs, dough kneader, emulsifier', 'Speeds' => '2 pulse speed settings plus turbo pulse', 'Storage' => 'In-bowl blade storage system saves counter space']],
                    ['title' => 'Walton Electric Oven 28L Grill Rotisserie', 'brand' => 'walton', 'sub' => 1, 'price' => 7800, 'sale' => 6999, 'stock' => 26, 'specs' => ['Chamber' => '28 Liters with motorized rotisserie spit rod', 'Heating' => '4 stainless steel heating elements with convection fan', 'Timer' => '60-minute mechanical timer with bell ring signal', 'Thermostat' => 'Adjustable temperature control from 100°C to 250°C']],
                ]
            ],
            // 30. Large Home Appliances
            [
                'cat_slug' => 'large-home-appliances',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Samsung 1.5 Ton WindFree Inverter Split AC', 'brand' => 'samsung', 'sub' => 0, 'price' => 78000, 'sale' => 72999, 'stock' => 12, 'specs' => ['Technology' => 'WindFree cooling gently disperses air via 23,000 micro-holes', 'Inverter' => 'Digital Inverter Boost saves up to 73% energy consumption', 'Filtration' => 'Tri-Care filter captures large dust, fibers and animal hairs', 'Smart' => 'SmartThings WiFi app control from anywhere']],
                    ['title' => 'LG 437L Frost-Free Double Door Refrigerator Smart', 'brand' => 'lg', 'sub' => 1, 'price' => 88000, 'sale' => 82000, 'stock' => 10, 'specs' => ['Compressor' => 'Smart Inverter Compressor with 10-year warranty', 'Cooling' => 'DoorCooling+ delivers 35% faster even cooling', 'Hygiene' => 'Hygiene Fresh+ 5-step air filter eliminates 99.999% bacteria', 'Capacity' => '437 Liters gross volume with movable twist ice tray']],
                    ['title' => 'Bosch Serie 6 8kg Front Load Washing Machine', 'brand' => 'bosch', 'sub' => 2, 'price' => 69000, 'sale' => 64500, 'stock' => 14, 'specs' => ['Motor' => 'EcoSilence Drive brushless motor with 10-year warranty', 'Hygiene' => 'AllergyPlus program certified by ECARF kills allergens', 'Speed' => 'SpeedPerfect cleans up to 65% faster without compromising wash', 'Drum' => 'VarioDrum wave-droplet design protects delicate fabrics']],
                    ['title' => 'Haier 516L Side by Side Refrigerator Black Glass', 'brand' => 'haier', 'sub' => 1, 'price' => 105000, 'sale' => 97999, 'stock' => 8, 'specs' => ['Finish' => 'Luxury black toughened glass door panel with digital touch', 'System' => 'Twin Inverter technology: fan and compressor run concurrently', 'Freezer' => '100% convertible cooling zones for versatile storage', 'Warranty' => '10-Year compressor warranty']],
                    ['title' => 'Dyson V15 Detect Absolute Cordless Vacuum Cleaner', 'brand' => 'dyson', 'sub' => 3, 'price' => 89000, 'sale' => 84000, 'stock' => 15, 'specs' => ['Laser' => 'Acoustic piezo sensor reveals invisible micro dust particles', 'Motor' => 'Hyperdymium motor spins up to 125000 RPM for 240AW suction', 'Screen' => 'LCD screen counts and displays scientific dust proof in real time', 'Run Time' => 'Up to 60 minutes fade-free whole home runtime']],
                    ['title' => 'Panasonic 1.5 Ton Twin Cool Inverter Split AC', 'brand' => 'panasonic', 'sub' => 0, 'price' => 74000, 'sale' => 69999, 'stock' => 14, 'specs' => ['Purification' => 'nanoe-G generator removes 99% PM2.5 air particles', 'Efficiency' => 'Twin rotary inverter compressor high energy rating', 'Coils' => '100% Pure copper condenser coils with Blue Fin anti-corrosion', 'Shield' => 'ECO mode with Artificial Intelligence network']],
                    ['title' => 'LG 9kg AI DD Front Load Washer with Steam+', 'brand' => 'lg', 'sub' => 2, 'price' => 79000, 'sale' => 73999, 'stock' => 11, 'specs' => ['AI DD' => 'AI Direct Drive senses weight and fabric softness automatically', 'Steam' => 'Steam+ reduces 99.9% dust mites and reduces wrinkles by 30%', 'Speed' => 'TurboWash 360 completes thorough clean in just 39 minutes', 'ThinQ' => 'WiFi control and remote cycle download via LG ThinQ']],
                    ['title' => 'Walton 380L Non-Frost Inverter Refrigerator', 'brand' => 'walton', 'sub' => 1, 'price' => 54000, 'sale' => 49999, 'stock' => 18, 'specs' => ['Capacity' => '380 Liters gross storage capacity', 'Refrigerant' => 'Eco-friendly R600a hydrocarbon refrigerant', 'Deodorizer' => 'Nano silver ion active anti-bacterial air filtration', 'Deals' => '12-Year Walton replacement guarantee on compressor']],
                    ['title' => 'Singer 2.0 Ton Inverter Split Air Conditioner', 'brand' => 'singer', 'sub' => 0, 'price' => 79000, 'sale' => 74500, 'stock' => 10, 'specs' => ['Capacity' => '24000 BTU 2.0 Ton rapid ambient cooling', 'Coil' => 'Golden Fin anti-corrosive gold hydrophilic fin coating', 'Display' => 'Hidden digital temperature LED display', 'Features' => 'Turbo Cool, Sleep Mode, Auto Restart with memory']],
                    ['title' => 'Xiaomi Robot Vacuum S10 LiDAR Navigation', 'brand' => 'xiaomi', 'sub' => 3, 'price' => 28500, 'sale' => 25999, 'stock' => 20, 'specs' => ['Navigation' => '360° LDS laser radar mapping with obstacle avoidance', 'Suction' => '4000Pa powerful suction blower sweeps deep carpet dirt', 'Mopping' => 'Smart electronically controlled water tank with 3 flow levels', 'App' => 'Mi Home app custom zone cleaning and virtual no-go walls']],
                ]
            ],
        ];
    }
}
