<?php

namespace Database\Seeders;

class ProductCatalogDefinitionPart4
{
    public static function get(): array
    {
        return [
            // 41. Daily Groceries & Staples
            [
                'cat_slug' => 'daily-groceries-staples',
                'has_variants' => false,
                'items' => [
                    ['title' => 'PRAN Chinigura Aromatic Kalijeera Rice 5kg', 'brand' => 'pran', 'sub' => 0, 'price' => 780, 'sale' => 720, 'stock' => 80, 'specs' => ['Grain' => '100% Pure indigenous Kalijeera aromatic fine grain', 'Processing' => 'Sortex cleaned, aged for maximum aroma and non-sticky cooking', 'Dishes' => 'Ideal for traditional Polao, Biryani, Khichuri, and Firni', 'Origin' => 'Grown in fertile Dinajpur plains of Bangladesh']],
                    ['title' => 'Radhuni Pure Cold Pressed Mustard Oil 1 Liter', 'brand' => 'radhuni', 'sub' => 1, 'price' => 380, 'sale' => 345, 'stock' => 90, 'specs' => ['Extraction' => 'Cold-pressed from selected grade-1 yellow and brown mustard seeds', 'Aroma' => 'Pungent authentic sharp mustard aroma and deep golden tint', 'Health' => 'Rich in Omega-3 and Omega-6 essential fatty acids', 'Purity' => 'BSTI certified 100% natural zero adulteration']],
                    ['title' => 'Radhuni Turmeric Powder Haldi 500g Jar', 'brand' => 'radhuni', 'sub' => 2, 'price' => 240, 'sale' => 215, 'stock' => 100, 'specs' => ['Curcumin' => 'High natural curcumin content guarantees vibrant golden color', 'Milling' => 'Cryogenic low-temperature grinding preserves volatile essential oils', 'Container' => 'Airtight food-grade pet jar keeps spice fresh', 'Ingredients' => '100% Dried turmeric rhizomes']],
                    ['title' => 'Radhuni Red Chili Powder Morich 500g Jar', 'brand' => 'radhuni', 'sub' => 2, 'price' => 280, 'sale' => 250, 'stock' => 95, 'specs' => ['Heat' => 'Fiery authentic punch with natural crimson red coloring', 'Selected' => 'Handpicked sun-dried whole red chilies', 'Purity' => 'No added synthetic dyes, Sudan dyes or preservatives', 'Net Weight' => '500 grams sealed jar']],
                    ['title' => 'ACI Pure Premium Deshi Masoor Daal 1kg', 'brand' => 'pran', 'sub' => 3, 'price' => 165, 'sale' => 148, 'stock' => 85, 'specs' => ['Variety' => 'Small grain local Deshi red split lentils', 'Cleaning' => 'Triple cleaned and laser-sorted free from pebbles and dust', 'Protein' => 'High protein density cooks into velvety traditional daal', 'Cooking Time' => 'Cooks tender in 15 minutes']],
                    ['title' => 'Daawat Devaaya Premium Long Grain Basmati Rice 5kg', 'brand' => 'pran', 'sub' => 0, 'price' => 1350, 'sale' => 1220, 'stock' => 45, 'specs' => ['Length' => 'Extra-long grains elongate up to 2.5x after cooking', 'Aging' => 'Naturally aged in temperature-controlled silos for 1 year', 'Fluffiness' => 'Slender pearl-white grains stay separate and fluffy', 'Origin' => 'Sourced from Himalayan foothills']],
                    ['title' => 'Radhuni Pure Garam Masala Ground Spice 100g', 'brand' => 'radhuni', 'sub' => 2, 'price' => 180, 'sale' => 160, 'stock' => 75, 'specs' => ['Blend' => 'Cardamom, Cinnamon, Cloves, Mace, Nutmeg, Black Pepper, Cumin', 'Flavor' => 'Warm aristocratic fragrance for royal Mughlai curries and roasts', 'Packaging' => 'Foil-sealed pouch inside protective cardboard carton', 'Weight' => '100 grams']],
                    ['title' => 'Fortune Sunlite Refined Sunflower Oil 5L Can', 'brand' => 'radhuni', 'sub' => 1, 'price' => 980, 'sale' => 899, 'stock' => 50, 'specs' => ['Vitamins' => 'Enriched with Vitamin A and Vitamin D for heart wellness', 'Clarity' => 'Light, clear, and odor-free absorbs less into food', 'Smoke Point' => 'High smoke point perfect for deep frying and sautéing', 'Container' => 'Sturdy 5-Liter ergonomic pour spout can']],
                    ['title' => 'Dano Daily Pushti Full Cream Milk Powder 1kg', 'brand' => 'pran', 'sub' => 3, 'price' => 890, 'sale' => 820, 'stock' => 60, 'specs' => ['Source' => '100% Fresh European cow milk from Arla dairy farmers', 'Nutrition' => 'Rich in calcium, protein, Vitamin A, and Vitamin D3', 'Taste' => 'Creamy rich taste dissolves instantly in hot or cold water', 'Pack' => 'Multi-layer hermetically sealed foil pouch']],
                    ['title' => 'ACI Pure Vacuum Evaporated Iodized Salt 1kg', 'brand' => 'pran', 'sub' => 2, 'price' => 45, 'sale' => 40, 'stock' => 120, 'specs' => ['Purity' => '99.9% Pure vacuum-evaporated refined table salt', 'Iodine' => 'Adequately iodized to prevent iodine deficiency disorders', 'Flow' => 'Free-flowing crystals do not cake or clump in humidity', 'Weight' => '1 kg polypack']],
                ]
            ],
            // 42. Beverages & Juices
            [
                'cat_slug' => 'beverages-juices',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Nescafe Gold Blend Premium Roasted Coffee 200g', 'brand' => 'nescafe', 'sub' => 1, 'price' => 1450, 'sale' => 1299, 'stock' => 60, 'specs' => ['Roast' => 'Expertly crafted golden roast with finely ground Arabica beans', 'Aroma' => 'Rich aroma and smooth, well-rounded velvety taste', 'Format' => 'Freeze-dried premium instant coffee crystals', 'Jar' => '200g Glass jar with aroma-protecting golden seal cap']],
                    ['title' => 'Twinings Earl Grey Black Tea Bags 50 Count', 'brand' => 'twinings', 'sub' => 0, 'price' => 780, 'sale' => 699, 'stock' => 70, 'specs' => ['Blend' => 'Fine black tea scented with citrus bergamot oil', 'Heritage' => 'Originally blended for the British Prime Minister in 1831', 'Bags' => '50 Foil-wrapped tea bags for fresh preservation', 'Serving' => 'Best enjoyed black with a slice of fresh lemon or splash of milk']],
                    ['title' => 'PRAN 100% Real Mango Fruit Drink 1 Liter Tetra', 'brand' => 'pran', 'sub' => 2, 'price' => 140, 'sale' => 125, 'stock' => 100, 'specs' => ['Pulp' => 'Crafted from hand-selected ripe Rajshahi Fazli & Langra mangoes', 'Vitamins' => 'Enriched with Vitamin C, A, and natural electrolytes', 'Packaging' => '6-layer aseptic Tetra Pak seals in fresh orchard flavor', 'Preservatives' => 'Zero artificial colors or preservatives']],
                    ['title' => 'Twinings Pure Green Tea 50 Tea Bags Box', 'brand' => 'twinings', 'sub' => 0, 'price' => 750, 'sale' => 660, 'stock' => 65, 'specs' => ['Leaves' => 'Pure steamed green tea leaves from Zhejiang province', 'Taste' => 'Delicate, clean, refreshing flavor without bitterness', 'Antioxidants' => 'Naturally loaded with healthy flavonoids and polyphenols', 'Steep' => 'Infuse in freshly boiled water for 2 minutes']],
                    ['title' => 'Ispahani Mirzapore Best Leaf Black Tea 400g Box', 'brand' => 'pran', 'sub' => 0, 'price' => 260, 'sale' => 235, 'stock' => 90, 'specs' => ['Origin' => 'Selected from premier tea gardens of Sylhet & Chittagong', 'Grade' => 'BOP (Broken Orange Pekoe) with liquor density', 'Color' => 'Deep amber liquor with robust brisk character', 'Usage' => 'The nation\'s favorite choice for traditional milk tea']],
                    ['title' => 'Davidoff Café Rich Aroma Ground Coffee 250g', 'brand' => 'nescafe', 'sub' => 1, 'price' => 1250, 'sale' => 1100, 'stock' => 40, 'specs' => ['Beans' => '100% Arabica beans from South America and East Africa', 'Roast' => 'Medium roast with spicy and fruity acidic complexity', 'Grind' => 'Universal filter grind for French Press, Drip, and Moka Pot', 'Pack' => 'Vacuum sealed aroma freshness foil brick']],
                    ['title' => 'Red Bull Energy Drink Cans 250ml (Pack of 4)', 'brand' => 'nescafe', 'sub' => 3, 'price' => 720, 'sale' => 650, 'stock' => 80, 'specs' => ['Vitalizes' => 'Vitalizes body and mind during work, study, or sports', 'Ingredients' => 'High quality Caffeine, Taurine, B-Group Vitamins, Sugars, Alpine Water', 'Volume' => '4x 250ml slim aluminum cans (100% recyclable)', 'Serving' => 'Best served ice cold']],
                    ['title' => 'Twinings English Breakfast Tea Bags 50 Count', 'brand' => 'twinings', 'sub' => 0, 'price' => 780, 'sale' => 699, 'stock' => 55, 'specs' => ['Blend' => 'Hearty robust blend of Assam, Ceylon and Kenyan black teas', 'Character' => 'Full-bodied and comforting, pairs perfectly with morning milk and sugar', 'Bags' => 'Individually envelope-wrapped tag bags', 'Origin' => 'Master blended in Hampshire, United Kingdom']],
                    ['title' => 'PRAN Frooto Green Mango Juice 250ml 6-Pack', 'brand' => 'pran', 'sub' => 2, 'price' => 180, 'sale' => 160, 'stock' => 85, 'specs' => ['Flavor' => 'Tangy, refreshing sour green mango nectar drink', 'Refreshment' => 'Instant cooldown during hot tropical afternoons', 'Pack' => 'Convenient on-the-go bottles with straws', 'Volume' => '6x 250ml mini bottles']],
                    ['title' => 'Ovaltine Malt Chocolate Milk Drink Mix 400g Jar', 'brand' => 'nescafe', 'sub' => 3, 'price' => 450, 'sale' => 399, 'stock' => 70, 'specs' => ['Malt' => 'Wholesome malted barley extract and Swiss chocolate recipe', 'Nutrients' => 'Nutri-10 formula with Calcium, Iron, Zinc, and 7 Vitamins', 'Serving' => 'Mix with hot or cold milk for wholesome nutritional boost', 'Jar' => '400g reusable sealed amber glass jar']],
                ]
            ],
            // 43. Snacks & Confectionery
            [
                'cat_slug' => 'snacks-confectionery',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Ferrero Rocher Fine Hazelnut Chocolates 24-Piece', 'brand' => 'ferrero-rocher', 'sub' => 0, 'price' => 1650, 'sale' => 1499, 'stock' => 50, 'specs' => ['Structure' => 'Whole roasted crunchy hazelnut in creamy filling, crisp wafer, and milk chocolate with hazelnut pieces', 'Packaging' => 'Iconic transparent gift box with golden foil pralines', 'Quantity' => '24 Individually wrapped luxury pieces (300g)', 'Country' => 'Made in Italy']],
                    ['title' => 'Lindt Excellence 70% Cocoa Dark Chocolate 100g', 'brand' => 'ferrero-rocher', 'sub' => 0, 'price' => 450, 'sale' => 399, 'stock' => 65, 'specs' => ['Cocoa' => '70% Pure cocoa content with balanced rich bitterness', 'Notes' => 'Subtle nuances of vanilla, roasted nuts, and red fruits', 'Texture' => 'Snaps cleanly and melts with silky smoothness on the palate', 'Craft' => 'Crafted by Lindt Swiss Master Chocolatiers since 1845']],
                    ['title' => 'Pringles Sour Cream & Onion Potato Crisps 165g', 'brand' => 'pran', 'sub' => 1, 'price' => 320, 'sale' => 280, 'stock' => 75, 'specs' => ['Can' => 'Iconic resealable canister keeps chips unbroken and fresh', 'Flavor' => 'Tangy sour cream, savory onion, and toasted potato bliss', 'Shape' => 'Perfect hyperbolic paraboloid stackable saddle shape', 'Net Weight' => '165 grams']],
                    ['title' => 'Nutella Hazelnut Spread with Cocoa 750g Glass Jar', 'brand' => 'ferrero-rocher', 'sub' => 0, 'price' => 880, 'sale' => 790, 'stock' => 55, 'specs' => ['Recipe' => '7 Quality ingredients: Roasted hazelnuts, skim milk, cocoa, sugar', 'Texture' => 'Creamy velvet spread glides smoothly over warm toast and pancakes', 'Purity' => 'Zero artificial colors and preservatives', 'Jar' => '750g family size recyclable glass jar']],
                    ['title' => 'Tong Garden Salted Roasted Cashew Nuts 150g', 'brand' => 'pran', 'sub' => 2, 'price' => 480, 'sale' => 420, 'stock' => 60, 'specs' => ['Nuts' => 'Jumbo whole grade cashews slowly oven roasted to golden crunch', 'Seasoning' => 'Lightly dusted with fine sea salt', 'Health' => 'Zero trans fats, rich in plant protein and heart-healthy magnesium', 'Pouch' => 'Resealable foil zipper pouch preserves vacuum crispness']],
                    ['title' => 'Dan Cake Danish Butter Cookies Tin 454g', 'brand' => 'pran', 'sub' => 3, 'price' => 550, 'sale' => 490, 'stock' => 70, 'specs' => ['Recipe' => 'Traditional Danish recipe made with real creamy dairy butter', 'Shapes' => '5 Classic biscuit shapes: Pretzel, Vanilla Ring, Finnish, Country, Coconut', 'Tin' => 'Collectible reusable embossed royal blue metal gift tin', 'Texture' => 'Rich, crumbly melt-in-the-mouth buttery bite']],
                    ['title' => 'Lay\'s Classic Salted Potato Chips 130g Party Pack', 'brand' => 'pran', 'sub' => 1, 'price' => 160, 'sale' => 140, 'stock' => 90, 'specs' => ['Potatoes' => 'Specially selected farm-grown potatoes sliced paper thin', 'Oil' => 'Cooked in 100% pure vegetable oil with pinch of salt', 'Crunch' => 'Light, crispy crunch is addictive from the first bite', 'Net Weight' => '130 grams party bag']],
                    ['title' => 'Cadbury Dairy Milk Silk Chocolate Bar 150g', 'brand' => 'ferrero-rocher', 'sub' => 0, 'price' => 320, 'sale' => 280, 'stock' => 85, 'specs' => ['Silkiness' => 'Richer, smoother, and creamier than standard milk chocolate', 'Melt' => 'Indulgent curated chocolate melts luxuriously in the mouth', 'Ingredients' => '100% Sustainably sourced cocoa via Cocoa Life program', 'Weight' => '150 grams large sharing bar']],
                    ['title' => 'Tong Garden Roasted California Almonds 150g', 'brand' => 'pran', 'sub' => 2, 'price' => 450, 'sale' => 390, 'stock' => 65, 'specs' => ['Origin' => 'Imported whole California Nonpareil grade almonds', 'Roasting' => 'Hot air dry roasted without added oil', 'Fiber' => 'High dietary fiber and Vitamin E antioxidant booster', 'Pack' => 'Nitrogen flushed airtight standup pouch']],
                    ['title' => 'Britannia Good Day Butter Biscuits 6-Pack Combo', 'brand' => 'pran', 'sub' => 3, 'price' => 220, 'sale' => 190, 'stock' => 100, 'specs' => ['Smile' => 'Signature smiling cookie design with butter-rich ridges', 'Taste' => 'Rich aroma of real butter in every golden baked bite', 'Tea Time' => 'The ultimate companion for morning and evening tea', 'Combo' => 'Multipack contains 6 individual 100g fresh rolls']],
                ]
            ],
            // 44. Baby Care & Maternity
            [
                'cat_slug' => 'baby-care-maternity',
                'has_variants' => true,
                'variant_type' => 'baby_diaper',
                'items' => [
                    ['title' => 'Pampers Premium Protection Diaper Pants L-54', 'brand' => 'dove', 'sub' => 0, 'price' => 2450, 'sale' => 2199, 'stock' => 45, 'specs' => ['Absorbency' => 'Air channels lock away wetness for up to 12 hours dryness', 'Softness' => 'Feather-like ultra soft materials gently wrap baby in comfort', 'Indicator' => 'Wetness indicator line turns blue when it\'s time to change', 'Waist' => '360° All-around stretchy waistband pulls on like underwear']],
                    ['title' => 'Huggies Wonder Pants Extra Absorb Diapers M-60', 'brand' => 'dove', 'sub' => 0, 'price' => 2200, 'sale' => 1950, 'stock' => 50, 'specs' => ['Bubble Bed' => 'Next Gen Bubble Bed technology feels like a soft cot bed', 'Dispersal' => 'Triple absorption core disperses liquid evenly preventing bulk', 'Skin' => 'Helps prevent diaper rash and red waistband marks', 'Size' => 'Medium (fits babies 7-12 kg) 60 pants']],
                    ['title' => 'Johnson\'s Baby No More Tears Shampoo 500ml', 'brand' => 'dove', 'sub' => 2, 'price' => 780, 'sale' => 690, 'stock' => 65, 'specs' => ['Formula' => 'No More Tears formula is as gentle to the eyes as pure water', 'Hypoallergenic' => 'Pediatrician and dermatologist tested hypoallergenic', 'Purity' => 'Free from parabens, phthalates, sulfates, and dyes', 'Scalp' => 'Gently cleanses fine baby hair and sensitive scalp']],
                    ['title' => 'WaterWipes 99.9% Pure Water Baby Wipes 4-Pack', 'brand' => 'dove', 'sub' => 1, 'price' => 1850, 'sale' => 1650, 'stock' => 40, 'specs' => ['Ingredients' => '99.9% Purified water and a drop of natural fruit seed extract', 'Purity' => 'The world\'s purest baby wipes for newborn and premature skin', 'Hypoallergenic' => 'Zero fragrance, alcohol, or harsh preservatives', 'Pack' => 'Multipack of 4 packs (240 total biodegradable wipes)']],
                    ['title' => 'Philips Avent Anti-Colic Feeding Bottle 260ml Twin', 'brand' => 'philips', 'sub' => 3, 'price' => 2450, 'sale' => 2199, 'stock' => 35, 'specs' => ['Anti-Colic' => 'Clinically proven anti-colic valve flexes into bottle, not baby tummy', 'Latch' => 'Ribbed texture prevents nipple collapse for uninterrupted feed', 'Cleaning' => 'Wide bottle neck with only 4 pieces for easy washing and assembly', 'Safety' => '100% BPA-free durable polypropylene material']],
                    ['title' => 'Sebamed Baby Gentle Cleansing Bar 100g Soap', 'brand' => 'cerave', 'sub' => 2, 'price' => 620, 'sale' => 540, 'stock' => 70, 'specs' => ['pH 5.5' => 'Exact pH 5.5 consolidates baby\'s acid mantle barrier against dryness', 'Soap-Free' => '100% Soap and alkali free sugar ten-side cleansing complex', 'Nourish' => 'Panthenol and inulin moisturize and relieve irritated skin', 'Safety' => 'Made in Germany, recommended by dermatologists worldwide']],
                    ['title' => 'Chicco Baby Moments Rich Massage Oil 200ml', 'brand' => 'dove', 'sub' => 2, 'price' => 750, 'sale' => 650, 'stock' => 55, 'specs' => ['Oil' => 'Formulated with natural Rice Bran oil for relaxing massage', 'Removal' => 'Also ideal for gently removing newborn cradle cap crusts', 'Petroleum' => 'Free from parabens, mineral oils, alcohol, and silicones', 'Tested' => 'Clinically tested on sensitive skin']],
                    ['title' => 'Sudocrem Antiseptic Healing Nappy Cream 125g', 'brand' => 'cerave', 'sub' => 2, 'price' => 880, 'sale' => 780, 'stock' => 60, 'specs' => ['Zinc Oxide' => 'Zinc oxide water-repellent base forms protective barrier on skin', 'Anesthetic' => 'Mild local anesthetic eases pain and irritation of diaper rash', 'Healing' => 'Antibacterial and antifungal agents protect against infection', 'Heritage' => 'Clinically proven and trusted by mothers for over 90 years']],
                    ['title' => 'Cetaphil Baby Daily Lotion with Shea Butter 400ml', 'brand' => 'cerave', 'sub' => 2, 'price' => 1450, 'sale' => 1299, 'stock' => 45, 'specs' => ['Hydration' => 'Organic Calendula, Sweet Almond oil, Sunflower oil & Shea butter', 'Protection' => 'Protects baby\'s delicate skin barrier against roughness for 24h', 'Pediatric' => 'Hypoallergenic and non-irritating tested by pediatricians', 'Dispenser' => 'Convenient single-hand pump dispenser bottle']],
                    ['title' => 'Pampers Sensitive Baby Wipes 3-Pack Flip-Top', 'brand' => 'dove', 'sub' => 1, 'price' => 1250, 'sale' => 1099, 'stock' => 50, 'specs' => ['Balance' => 'Unique pH balancing formula restores natural skin pH better than water', 'Softness' => '20% Thicker soft grip texture cleans messes with fewer wipes', 'Fragrance' => '0% Fragrance, alcohol, phenoxyethanol, and parabens', 'Lid' => 'Plastic flip-top lid seals moisture to prevent drying out']],
                ]
            ],
            // 45. Fitness & Home Gym
            [
                'cat_slug' => 'fitness-home-gym',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Bowflex SelectTech 552 Adjustable Dumbbells Pair', 'brand' => 'wilson', 'sub' => 0, 'price' => 28500, 'sale' => 26000, 'stock' => 12, 'specs' => ['Weight Range' => 'Adjusts from 5 to 52.5 lbs (2.5 to 24 kg) per dumbbell', 'Dial' => 'Quick turn-of-a-dial weight selection replaces 15 pairs of dumbbells', 'Molding' => 'Durable molding around metal plates creates quiet workout', 'Workouts' => 'Full body strength workouts: chest, arms, shoulders, back, legs']],
                    ['title' => 'Decathlon Domyos High Resistance Loop Bands Set', 'brand' => 'wilson', 'sub' => 1, 'price' => 2450, 'sale' => 2100, 'stock' => 45, 'specs' => ['Set' => '3 Resistance levels: 15kg (Light), 25kg (Medium), 35kg (Heavy)', 'Material' => '100% Durable natural latex rubber withstands heavy stretching', 'Use' => 'Assisted pull-ups, squats, mobility drills, and muscle rehab', 'Portability' => 'Includes breathable nylon mesh carry pouch']],
                    ['title' => 'Liforme Original Non-Slip Yoga Mat 4.2mm', 'brand' => 'nike', 'sub' => 2, 'price' => 14500, 'sale' => 13200, 'stock' => 20, 'specs' => ['AlignForMe' => 'Patented intelligent alignment system guides poses and posture', 'Grip-For-Me' => 'Revolutionary Grip-For-Me warrior-like grip even during sweaty hot yoga', 'Eco' => 'Made from biodegradable eco-polyurethane and natural rubber', 'Bag' => 'Includes premium Liforme yoga mat bag with shoulder strap']],
                    ['title' => 'Iron Gym Total Upper Body Workout Pull-Up Bar', 'brand' => 'wilson', 'sub' => 3, 'price' => 2800, 'sale' => 2400, 'stock' => 35, 'specs' => ['Installation' => 'Uses leverage to hook onto doorway without drilling holes or screws', 'Positions' => '3 Grip positions: Narrow, neutral, and wide for diverse back activation', 'Capacity' => 'Heavy-gauge steel construction supports up to 300 lbs (136 kg)', 'Multipurpose' => 'Flip to floor for push-ups, dips, and abdominal sit-up anchors']],
                    ['title' => 'Decathlon Domyos Cast Iron Kettlebell 16kg', 'brand' => 'wilson', 'sub' => 0, 'price' => 4800, 'sale' => 4200, 'stock' => 25, 'specs' => ['Weight' => '16 kg solid cast iron core for explosive hip hinge swings', 'Base' => 'Heavy rubber shock-absorbing base protects tiled home gym floors', 'Handle' => 'Wide ergonomic powder-coated handle accommodates two-handed grip', 'Finish' => 'Anti-rust textured black finish']],
                    ['title' => 'Adidas Essential Flat Workout Weight Bench', 'brand' => 'adidas', 'sub' => 0, 'price' => 12500, 'sale' => 10999, 'stock' => 18, 'specs' => ['Padding' => '65mm thick high-density foam upholstery provides firm support', 'Steel' => 'Heavy duty 60mm tubular steel frame with wide stance feet', 'Max Load' => 'Total maximum load capacity of 200 kg (user + weights)', 'Versatility' => 'Compact footprint ideal for dumbbell press, rows, and step-ups']],
                    ['title' => 'Decathlon 65cm Anti-Burst Core Exercise Gym Ball', 'brand' => 'wilson', 'sub' => 2, 'price' => 1850, 'sale' => 1550, 'stock' => 40, 'specs' => ['Anti-Burst' => 'Thick anti-burst PVC deflates slowly if punctured by sharp objects', 'Size' => '65 cm diameter ideal for users between 165cm and 185cm tall', 'Lines' => 'Non-slip embossed circular rib lines improve hand grip', 'Pump' => 'Includes fast hand inflation pump and valve plugs']],
                    ['title' => 'ProForm Adjustable Incline Decline Weight Bench', 'brand' => 'wilson', 'sub' => 0, 'price' => 18500, 'sale' => 16500, 'stock' => 15, 'specs' => ['Positions' => '6 Backrest positions: Decline, flat, incline (30°, 45°, 60°, 85°)', 'Lock' => 'Quick-lock pin mechanism adjusts position securely in seconds', 'Wheels' => 'Transport wheels and front handle for easy storage in corners', 'Upholstery' => 'Sweat-resistant box-stitched vinyl upholstery']],
                    ['title' => 'SKLZ Speed & Agility Footwork Training Ladder 15ft', 'brand' => 'adidas', 'sub' => 1, 'price' => 2800, 'sale' => 2450, 'stock' => 35, 'specs' => ['Length' => '15-foot heavy-duty flat nylon webbing ladder', 'Rungs' => '11 Adjustable heavy-impact plastic flat rungs', 'Athletics' => 'Enhances foot speed, lateral quickness, balance, and coordination', 'Anchors' => 'Includes 4 ground stakes and convenient storage bag']],
                    ['title' => 'Everlast Heavy Boxing Punching Bag 70lbs Filled', 'brand' => 'nike', 'sub' => 3, 'price' => 11500, 'sale' => 9999, 'stock' => 16, 'specs' => ['Filling' => 'Custom blend of sanitized synthetic and natural fibers absorbs shock', 'Exterior' => 'Premium Nevatear synthetic leather with reinforced webbing', 'Straps' => 'Heavy-duty nylon straps provide security and quiet operation', 'Swivel' => 'Double-end loop for bottom anchoring against excessive sway']],
                ]
            ],
            // 46. Sports & Outdoor Gear
            [
                'cat_slug' => 'sports-outdoor-gear',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Kookaburra Kahuna Pro English Willow Cricket Bat', 'brand' => 'wilson', 'sub' => 0, 'price' => 34000, 'sale' => 31000, 'stock' => 10, 'specs' => ['Willow' => 'Grade 1 Unbleached English Willow hand-selected for performance', 'Profile' => 'High sweet spot with massive 38mm edges for power strokeplay', 'Handle' => '12-piece round cane handle with Kahuna octopus rubber grip', 'Weight' => 'Short Handle 2 lbs 8 oz (1150 grams)']],
                    ['title' => 'Adidas FIFA World Cup Pro Official Match Ball', 'brand' => 'adidas', 'sub' => 1, 'price' => 14500, 'sale' => 12999, 'stock' => 20, 'specs' => ['Certification' => 'FIFA Quality Pro highest official international match rating', 'Construction' => 'Seamless thermally bonded panel construction for predictable trajectory', 'Bladder' => 'High-grade butyl bladder for superior air and shape retention', 'Cover' => '100% Polyurethane textured speedshell for aerodynamic spin']],
                    ['title' => 'Yonex Astrox 99 Pro Badminton Racket (4U/G5)', 'brand' => 'yonex', 'sub' => 2, 'price' => 21000, 'sale' => 18999, 'stock' => 18, 'specs' => ['Balance' => 'Head-heavy balance with Rotational Generator System', 'Frame' => 'HM Graphite + Namd + Volume Cut Resin for steep smashes', 'Shaft' => 'Extra slim shaft cuts air resistance dramatically', 'Origin' => 'Developed and manufactured in Japan']],
                    ['title' => 'Coleman Sundome 4-Person Waterproof Camping Tent', 'brand' => 'wilson', 'sub' => 3, 'price' => 16500, 'sale' => 14999, 'stock' => 15, 'specs' => ['WeatherTec' => 'WeatherTec system welded floors and inverted seams keep rain out', 'Setup' => 'Snag-free continuous pole sleeves set up in under 10 minutes', 'Ventilation' => 'Large windows and ground vent for optimal air circulation', 'Dimensions' => '9 x 7 feet floor area with 4-foot 11-inch center height']],
                    ['title' => 'SS Ton Master 100 English Willow Cricket Bat', 'brand' => 'wilson', 'sub' => 0, 'price' => 22000, 'sale' => 19500, 'stock' => 14, 'specs' => ['Willow' => 'Air-dried handpicked Grade 2 English willow with straight grains', 'Spine' => 'Exaggerated concave spine for lightweight pickup balance', 'Toe' => 'Fitted with factory toe guard to prevent moisture swelling', 'Grip' => 'Scale texture chevron embossed multi-colored grip']],
                    ['title' => 'Wilson Evolution Official Game Indoor Basketball', 'brand' => 'wilson', 'sub' => 1, 'price' => 7800, 'sale' => 6999, 'stock' => 28, 'specs' => ['Cover' => 'Evo microfiber composite leather provides softest feel on court', 'Channels' => 'Laid-in composite channels create consistent 100% grip surface', 'Cushion' => 'Cushion Core carcass combines sponge and butyl for great bounce', 'Size' => 'Official Regulation Men\'s Size 7 (29.5 inches)']],
                    ['title' => 'Yonex Aerosensa 30 Feather Shuttlecocks (12 Pack)', 'brand' => 'yonex', 'sub' => 2, 'price' => 3800, 'sale' => 3450, 'stock' => 40, 'specs' => ['Feathers' => '100% Solid grade goose feathers precision sorted for flight', 'Cork' => 'Full natural solid cork base delivers solid hitting feedback', 'Flight' => 'Stable consistent trajectory even in tournament hall drafts', 'Quantity' => 'Tube containing 12 tournament grade shuttlecocks']],
                    ['title' => 'Speedo Fastskin Elite Mirrored Swimming Goggles', 'brand' => 'nike', 'sub' => 3, 'price' => 4500, 'sale' => 3999, 'stock' => 35, 'specs' => ['IQfit' => 'IQfit 3D goggle seal fits securely without leaving facial marks', 'Lenses' => 'Hydroscopic curved mirrored lenses reduce glare and maximize 180° view', 'Straps' => 'Tensioning scale strap ensures precise fit every time', 'Anti-Fog' => 'Factory applied anti-fog coating provides crystal clear vision']],
                    ['title' => 'Campingaz Camp Bistro 2 Portable Gas Stove', 'brand' => 'wilson', 'sub' => 3, 'price' => 3800, 'sale' => 3350, 'stock' => 30, 'specs' => ['Ignition' => 'Piezo auto ignition starts flame instantly without matches', 'Power' => '2200W high-efficiency burner boils 1 Liter water in 5 minutes', 'Safety' => 'Cartridge safety locking system prevents gas leaks', 'Case' => 'Includes rugged hard plastic carrying suitcase for transport']],
                    ['title' => 'Decathlon Quechua 20L Hiking Backpack Grey', 'brand' => 'wilson', 'sub' => 3, 'price' => 2450, 'sale' => 2100, 'stock' => 50, 'specs' => ['Comfort' => 'Foam-padded back and shoulder straps with chest strap', 'Ventilation' => 'Simple back ventilation system reduces perspiration', 'Compartments' => '2 Compartments, 2 bottle holders, and pole carrier loops', 'Warranty' => 'Decathlon 10-Year warranty against fabric and zip defects']],
                ]
            ],
            // 47. Automotive & Motorbike
            [
                'cat_slug' => 'automotive-motorbike',
                'has_variants' => true,
                'variant_type' => 'helmet',
                'items' => [
                    ['title' => 'MT Helmets Thunder 4 SV Full Face Helmet DOT', 'brand' => 'yamaha', 'sub' => 0, 'price' => 12500, 'sale' => 11200, 'stock' => 25, 'specs' => ['Safety' => 'ECE 22.06 and DOT certified aerodynamic polycarbonate shell', 'Visor' => 'Max Vision Pinlock-ready optical visor with drop-down sun visor', 'Ventilation' => 'High-flow multi-channel front and rear exhaust vents', 'Lining' => 'Removable, washable hypoallergenic emergency quick-release pads']],
                    ['title' => 'Motul 7100 4T 10W-40 100% Synthetic Motor Oil 1L', 'brand' => 'yamaha', 'sub' => 1, 'price' => 1550, 'sale' => 1399, 'stock' => 70, 'specs' => ['Ester' => '100% Synthetic Ester technology ensures optimal engine response', 'Standards' => 'API SN and JASO MA2 performance standards for wet clutch', 'Color' => 'Red colored oil with signature aromatic ester scent', 'Protection' => 'Outstanding shear resistance protects gearbox and engine components']],
                    ['title' => '70mai Dash Cam A810 4K HDR Front and Rear Dual', 'brand' => 'xiaomi', 'sub' => 3, 'price' => 18500, 'sale' => 16999, 'stock' => 20, 'specs' => ['Sensor' => 'Sony Starvis 2 IMX678 sensor captures true 4K UHD video', 'HDR' => 'Dual-channel HDR front and rear ensures readable license plates', 'GPS' => 'Built-in GPS tracks speed, coordinates, and ADAS driving alerts', 'Night' => 'Night Owl Vision optimizes exposure in pitch black roads']],
                    ['title' => 'Meguiar\'s Gold Class Carnauba Liquid Car Wax 473ml', 'brand' => 'yamaha', 'sub' => 2, 'price' => 1950, 'sale' => 1750, 'stock' => 45, 'specs' => ['Formula' => 'Premium blend of pure carnauba wax with nourishing polymers', 'Shine' => 'Creates deep brilliant reflective shine with rich gloss', 'Protection' => 'Clear coat safe; repels rainwater and environmental contaminants', 'Application' => 'Includes soft foam applicator pad for easy hand application']],
                    ['title' => 'Baseus 65W Dual USB-C Fast Car Charger Metal', 'brand' => 'anker', 'sub' => 3, 'price' => 1850, 'sale' => 1550, 'stock' => 60, 'specs' => ['Power' => '65W Max high-speed output charges laptops and phones simultaneously', 'Ports' => 'USB-C (PD 65W) + USB-A (QC 30W) dual fast-charge ports', 'Body' => 'Heat-dissipating anodized aluminum alloy translucent shell', 'Display' => 'Digital LED voltage display monitors car battery health']],
                    ['title' => 'Chemical Guys Mr. Pink Super Suds Car Wash 1 Gal', 'brand' => 'yamaha', 'sub' => 2, 'price' => 2800, 'sale' => 2450, 'stock' => 35, 'specs' => ['Foam' => 'High-foaming snow wash creates mountains of slick wash bubbles', 'pH-Neutral' => '100% pH neutral formula will not strip existing wax or sealant', 'Safety' => 'Super slick polymers glide wash mitt safely over dirt preventing swirls', 'Scent' => 'Fresh delicious candy scent']],
                    ['title' => 'Castrol Power1 Ultimate 10W-40 4T Full Synthetic 1L', 'brand' => 'yamaha', 'sub' => 1, 'price' => 1350, 'sale' => 1199, 'stock' => 65, 'specs' => ['Technology' => '5-in-1 formula delivers outstanding acceleration and protection', 'Endurance' => 'Maintains power on long highway journeys without viscosity breakdown', 'Compatibility' => 'Suitable for modern high-performance sports motorbikes', 'Volume' => '1 Liter bottle']],
                    ['title' => 'Alpinestars SMX-1 Air V2 Motorcycle Gloves Black', 'brand' => 'yamaha', 'sub' => 0, 'price' => 6500, 'sale' => 5800, 'stock' => 30, 'specs' => ['Chassis' => 'Full-grain leather chassis and breathable air mesh zones', 'Knuckles' => 'Hard polymer knuckle guard for superior impact and abrasion defense', 'Touchscreen' => 'Touchscreen compatible fingertip for smartphones and GPS', 'Closure' => 'Ergonomic stretch wrist cuff with velcro tab closure']],
                    ['title' => 'Michelin Digital High Power Tire Inflator Pump', 'brand' => 'yamaha', 'sub' => 3, 'price' => 5400, 'sale' => 4800, 'stock' => 25, 'specs' => ['Speed' => 'Inflates a standard car tire from 0 to 35 PSI in under 3 minutes', 'Display' => 'Backlit digital gauge accurate to +/- 1 PSI with auto shut-off', 'Power' => '12V DC auxiliary car plug with 3-meter reach cable', 'LED' => 'Integrated bright white LED inspection light for nighttime flats']],
                    ['title' => 'Meguiar\'s Ultimate Microfiber Wash Mitt & Towel Kit', 'brand' => 'yamaha', 'sub' => 2, 'price' => 1450, 'sale' => 1250, 'stock' => 50, 'specs' => ['Fibers' => 'Deep pile plush microfiber lifts and traps dirt away from paintwork', 'Absorption' => 'Absorbs 10x its weight in soapy water for lubricated washing', 'Towel' => 'Includes Water Magnet waffle-weave 1200 GSM drying towel', 'Machine Wash' => 'Lint-free and machine washable for hundreds of washes']],
                ]
            ],
            // 48. Books & Stationery
            [
                'cat_slug' => 'books-stationery',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Atomic Habits by James Clear Hardcover Edition', 'brand' => 'apple', 'sub' => 1, 'price' => 1250, 'sale' => 1099, 'stock' => 55, 'specs' => ['Author' => 'James Clear', 'Publisher' => 'Penguin Random House UK', 'Topic' => 'Habit formation, personal productivity, and self-improvement', 'Pages' => '320 Pages premium cream paper hardcover']],
                    ['title' => 'The Psychology of Money by Morgan Housel', 'brand' => 'apple', 'sub' => 1, 'price' => 850, 'sale' => 750, 'stock' => 60, 'specs' => ['Author' => 'Morgan Housel', 'Publisher' => 'Harriman House', 'Topic' => 'Timeless lessons on wealth, greed, and happiness in 19 short stories', 'Format' => 'Paperback English edition 256 pages']],
                    ['title' => 'Lamy Safari Charcoal Black Fine Nib Fountain Pen', 'brand' => 'casio', 'sub' => 3, 'price' => 2850, 'sale' => 2499, 'stock' => 40, 'specs' => ['Body' => 'Indestructible matte black ABS plastic casing', 'Nib' => 'Black PVD coated polished stainless steel Fine (F) nib', 'Grip' => 'Ergonomically contoured triangular grip section', 'Clip' => 'Spring-loaded self-adjusting bronze metal wire clip']],
                    ['title' => 'Leuchtturm1917 Hardcover Medium A5 Dotted Journal', 'brand' => 'casio', 'sub' => 2, 'price' => 2450, 'sale' => 2199, 'stock' => 45, 'specs' => ['Paper' => '251 Numbered pages of 80 GSM acid-free bleed-proof ink paper', 'Ruling' => '5mm subtle dotted grid ideal for bullet journaling and sketching', 'Features' => 'Blank table of contents, 2 ribbon bookmarks, elastic band closure', 'Pocket' => 'Expandable inner gusset pocket inside back cover']],
                    ['title' => 'Sapiens: A Brief History of Humankind by Yuval Harari', 'brand' => 'apple', 'sub' => 0, 'price' => 980, 'sale' => 850, 'stock' => 50, 'specs' => ['Author' => 'Yuval Noah Harari', 'Publisher' => 'Vintage Books', 'Topic' => 'Evolution of Homo sapiens from the stone age to modern silicon era', 'Format' => 'Paperback international bestseller 498 pages']],
                    ['title' => 'Parker Jotter Stainless Steel Chrome Trim Ballpoint', 'brand' => 'casio', 'sub' => 3, 'price' => 1650, 'sale' => 1450, 'stock' => 60, 'specs' => ['Design' => 'Iconic 1954 teardrop click silhouette with signature arrow clip', 'Body' => 'Expertly crafted all-stainless steel barrel and cap', 'Refill' => 'Includes Quinkflow ballpoint refill for optimal smooth ink flow', 'Packaging' => 'Parker luxury royal blue presentation gift box']],
                    ['title' => 'Ikigai: The Japanese Secret to a Long and Happy Life', 'brand' => 'apple', 'sub' => 1, 'price' => 750, 'sale' => 650, 'stock' => 65, 'specs' => ['Authors' => 'Héctor García and Francesc Miralles', 'Topic' => 'Finding your life purpose through the wisdom of Okinawa centenarians', 'Format' => 'Collectible pocket hardcover clothbound book', 'Pages' => '208 Pages with calming illustrations']],
                    ['title' => 'Faber-Castell 48 Classic Colour Pencils Tin', 'brand' => 'casio', 'sub' => 2, 'price' => 1250, 'sale' => 1050, 'stock' => 45, 'specs' => ['Lead' => 'SV bonding technology prevents lead breakage during sharpening', 'Colors' => '48 Vibrant, rich pigment hexagonal colored pencils', 'Wood' => '100% Sustainably managed plantation cedar wood', 'Tin' => 'Durable two-tier metal storage tin container']],
                    ['title' => 'Rich Dad Poor Dad by Robert T. Kiyosaki', 'brand' => 'apple', 'sub' => 1, 'price' => 820, 'sale' => 720, 'stock' => 55, 'specs' => ['Author' => 'Robert T. Kiyosaki', 'Topic' => 'What the rich teach their kids about money that poor do not', 'Milestone' => '25th Anniversary expanded edition with study guide', 'Pages' => '336 Pages English paperback']],
                    ['title' => 'Midori MD Notebook Journal Blank A5 Japanese Paper', 'brand' => 'casio', 'sub' => 2, 'price' => 1850, 'sale' => 1599, 'stock' => 35, 'specs' => ['Paper' => 'Authentic Japanese MD Paper engineered not to feather with wet fountain ink', 'Binding' => 'Thread-stitched lay-flat binding opens full 180 degrees', 'Cover' => 'Glassine wax paper protective wrapper with index label stickers', 'Sheets' => '176 Blank unruled pages for writers and sketch artists']],
                ]
            ],
            // 49. Musical Instruments
            [
                'cat_slug' => 'musical-instruments',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Yamaha F310 Full-Size Dreadnought Acoustic Guitar', 'brand' => 'yamaha', 'sub' => 0, 'price' => 14500, 'sale' => 13200, 'stock' => 20, 'specs' => ['Top' => 'Select Spruce wood soundboard produces warm acoustic resonance', 'Back & Sides' => 'Locally sourced tonewood (Meranti) with gloss finish', 'Fingerboard' => 'Smooth rosewood fretboard with 20 frets and dot inlays', 'Tuning' => 'Covered chrome tuning peg machine heads maintain pitch']],
                    ['title' => 'Casio Casiotone CT-S300 61-Key Digital Keyboard', 'brand' => 'casio', 'sub' => 1, 'price' => 18500, 'sale' => 16999, 'stock' => 15, 'specs' => ['Keys' => '61 Full-size piano-style keys with 2-level touch response', 'Features' => '400 Tones, 77 Rhythms, Dance Music Mode, Pitch Bend Wheel', 'Handle' => 'Integrated center carry handle for portable practice', 'Connectivity' => 'USB to host micro B port connects to Chordana Play app']],
                    ['title' => 'Audio-Technica AT2020 Cardioid Condenser Studio Mic', 'brand' => 'sony', 'sub' => 2, 'price' => 12500, 'sale' => 11200, 'stock' => 22, 'specs' => ['Polar Pattern' => 'Cardioid pattern reduces pickup of sounds from sides and rear', 'Diaphragm' => 'Custom-engineered 16mm low-mass diaphragm delivers wide frequency response', 'SPL' => 'High SPL handling 144 dB handles loud vocals and instruments', 'Connector' => 'Professional 3-pin XLR output requires 48V phantom power']],
                    ['title' => 'Kala KA-15S Mahogany Soprano Ukulele Natural', 'brand' => 'yamaha', 'sub' => 3, 'price' => 6500, 'sale' => 5800, 'stock' => 30, 'specs' => ['Body' => 'Exotic mahogany wood body with traditional satin finish', 'Strings' => 'Strung with authentic Italian Aquila Super Nylgut strings', 'Fretboard' => 'Walnut fingerboard with 12 brass frets and etched rosette', 'Tone' => 'Bright, cheerful, sunny Hawaiian acoustic tone']],
                    ['title' => 'Yamaha P-45 88-Key Weighted Hammer Action Digital Piano', 'brand' => 'yamaha', 'sub' => 1, 'price' => 58000, 'sale' => 54000, 'stock' => 8, 'specs' => ['Action' => 'Graded Hammer Standard (GHS) weighted 88-key piano action', 'Sampling' => 'AWM (Advanced Wave Memory) stereo sampled acoustic grand piano', 'Polyphony' => '64-Note polyphony prevents dropped notes during sustained chords', 'Pedal' => 'Includes sustain pedal and sheet music rest']],
                    ['title' => 'Shure SM58 Cardioid Dynamic Vocal Microphone', 'brand' => 'sony', 'sub' => 2, 'price' => 13500, 'sale' => 12200, 'stock' => 25, 'specs' => ['Industry Standard' => 'The world\'s most popular live vocal performance microphone', 'Filter' => 'Built-in spherical wind and pop filter minimizes breath noise', 'Shock Mount' => 'Pneumatic shock-mount system cuts down handling vibrations', 'Build' => 'Legendary rugged steel mesh grille resists drops and stage abuse']],
                    ['title' => 'Yamaha Pacifica 012 Solid Body Electric Guitar', 'brand' => 'yamaha', 'sub' => 0, 'price' => 22500, 'sale' => 20500, 'stock' => 14, 'specs' => ['Pickups' => 'H-S-S pickup configuration (1 Humbucker, 2 Single-Coil)', 'Body' => 'Solid Agathis wood body with polyurethane gloss finish', 'Neck' => 'Comfortable C-profile satin finished maple neck', 'Bridge' => 'Vintage style tremolo system with adjustable saddles']],
                    ['title' => 'Focusrite Scarlett 2i2 4th Gen USB Audio Interface', 'brand' => 'sony', 'sub' => 2, 'price' => 24500, 'sale' => 22999, 'stock' => 16, 'specs' => ['Preamps' => 'Dual ultra-low-noise 4th Gen mic preamps with 69dB gain range', 'Air Mode' => 'Re-engineered Air mode adds high-end presence and harmonic drive', 'Converters' => 'Studio-grade 24-bit/192kHz converters with 120dB dynamic range', 'Software' => 'Includes Pro Tools Artist, Ableton Live Lite, and Hitmaker bundle']],
                    ['title' => 'Yamaha YRS-24B Soprano Recorder Instrument', 'brand' => 'yamaha', 'sub' => 3, 'price' => 650, 'sale' => 550, 'stock' => 60, 'specs' => ['Fingering' => 'Baroque fingering system accurate in pitch throughout scale', 'Resin' => 'Durable ABS resin body cleans easily under running tap', 'Windway' => 'Straight windway produces soft pure tone for music students', 'Case' => 'Includes protective cotton cloth bag and fingering chart']],
                    ['title' => 'Dunlop Cry Baby GCB95 Standard Wah Guitar Pedal', 'brand' => 'yamaha', 'sub' => 0, 'price' => 12000, 'sale' => 10800, 'stock' => 15, 'specs' => ['Heritage' => 'The original classic wah pedal created in late 1960s', 'Inductor' => 'Red Fasel inductor for legendary vintage sweep tone', 'Chassis' => 'Heavy-duty die-cast zinc housing built for road touring', 'Power' => 'Operates on 9V battery or optional Dunlop ECB003 AC adapter']],
                ]
            ],
            // 50. Pet Care & Supplies
            [
                'cat_slug' => 'pet-care-supplies',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Whiskas Ocean Fish Adult Dry Cat Food 7kg Bag', 'brand' => 'whiskas', 'sub' => 0, 'price' => 3800, 'sale' => 3350, 'stock' => 40, 'specs' => ['Nutrients' => 'Rich in Omega 3 & 6 fatty acids and Zinc for shiny healthy fur', 'Vitamins' => 'Enriched with Vitamin A and Taurine for sharp eyesight', 'Pockets' => 'Crunchy exterior kibbles with delicious soft salmon & tuna center', 'Age' => 'Complete and balanced nutrition for adult cats 1+ years']],
                    ['title' => 'Pedigree Adult Meat & Rice Dog Food 10kg Bag', 'brand' => 'pedigree', 'sub' => 1, 'price' => 4500, 'sale' => 3999, 'stock' => 35, 'specs' => ['Immunity' => 'Antioxidant Vitamin E helps support strong natural defense immune system', 'Digestion' => 'Dietary fibers support healthy digestive tract and firm stools', 'Muscles' => 'High quality animal protein strengthens muscle structure', 'Dental' => 'Specially designed kibble helps clean plaque from teeth']],
                    ['title' => 'OdourLock Ultra Premium Clumping Cat Litter 12kg', 'brand' => 'whiskas', 'sub' => 2, 'price' => 2200, 'sale' => 1950, 'stock' => 50, 'specs' => ['Odor Control' => 'Smart Odor Shield technology neutralizes ammonia for 40 days', 'Clumping' => 'Extra fast and hard clumping reduces litter waste and scraping', 'Dust' => '99.9% Dust-free clay protects feline and human respiratory health', 'Clay' => '100% Pure natural sodium bentonite clay']],
                    ['title' => 'Whiskas Tasty Mix Seafood Cocktail Gravy 85g (Pack of 12)', 'brand' => 'whiskas', 'sub' => 0, 'price' => 1250, 'sale' => 1099, 'stock' => 60, 'specs' => ['Ingredients' => 'Real tuna, salmon, crab meat, and seaweed in savory gravy', 'Hydration' => 'Provides essential daily hydration for healthy kidney function', 'Flavor' => 'Appetizing aroma entices even the pickiest feline eaters', 'Pack' => '12 Convenient single-serve 85g foil tear pouches']],
                    ['title' => 'Pedigree DentaStix Daily Oral Care Treats Large Dog', 'brand' => 'pedigree', 'sub' => 1, 'price' => 850, 'sale' => 740, 'stock' => 65, 'specs' => ['X-Shape' => 'Unique X-shape design bends around teeth to clean down to gumline', 'Plaque' => 'Clinically proven to reduce tartar and plaque build-up by up to 80%', 'Texture' => 'Gently abrasive texture scrubs teeth while dogs chew', 'Dog Size' => 'For large adult dogs 25 kg+ (Pack of 7 sticks)']],
                    ['title' => 'Catit Senses 2.0 Flower Drinking Water Fountain 3L', 'brand' => 'whiskas', 'sub' => 2, 'price' => 3400, 'sale' => 2999, 'stock' => 30, 'specs' => ['Water Flow' => '3 Different water flow settings (gentle flow, bubble top, calm streams)', 'Filter' => 'Dual-action water softening filter removes magnesium and debris', 'Capacity' => 'Large 3-Liter reservoir ensures constant fresh running water', 'Pump' => 'Whisper-quiet low-voltage energy-efficient electric pump']],
                    ['title' => 'Bioline Oatmeal Hypoallergenic Pet Shampoo 500ml', 'brand' => 'pedigree', 'sub' => 3, 'price' => 950, 'sale' => 820, 'stock' => 45, 'specs' => ['Formulation' => 'Natural colloidal oatmeal and Aloe vera extracts', 'Soothing' => 'Relieves dry, itchy, irritated pet skin and moisturizes coat', 'Safe' => 'Soap-free formula will not wash off topical flea and tick treatments', 'Animals' => 'Safe for both dogs and cats of all breeds']],
                    ['title' => 'Trixie Soft Slicker Grooming Brush with Cleaner', 'brand' => 'whiskas', 'sub' => 3, 'price' => 750, 'sale' => 650, 'stock' => 50, 'specs' => ['Pins' => 'Fine curved wire pins with protective rubber safety tips', 'Cleaning' => 'One-touch push button retracts pins for instant hair clump disposal', 'Handle' => 'Ergonomic soft-grip rubber handle prevents hand strain', 'Coat' => 'Gently removes loose undercoat hair and detangles knots']],
                    ['title' => 'JerHigh Real Chicken Meat Dog Treats 400g Pouch', 'brand' => 'pedigree', 'sub' => 1, 'price' => 880, 'sale' => 760, 'stock' => 55, 'specs' => ['Protein' => 'Prepared from 100% human-grade pure chicken breast meat', 'Nutrients' => 'Packed with Vitamin E, Inulin, and essential amino acids', 'Texture' => 'Tender chewy jerky sticks ideal for obedience training rewards', 'Origin' => 'Manufactured in Thailand under international ISO standards']],
                    ['title' => 'Bentonite Fresh Lavender Scented Cat Litter 10L', 'brand' => 'whiskas', 'sub' => 2, 'price' => 1450, 'sale' => 1250, 'stock' => 60, 'specs' => ['Scent' => 'Subtle calming lavender aroma releases only when moisture is detected', 'Clumping' => 'Instant tight round clumps within 3 seconds', 'Absorption' => 'High moisture absorption capacity keeps tray bottom dry', 'Eco' => '100% Natural non-toxic chemical-free mineral formula']],
                ]
            ],
        ];
    }
}
