<?php

namespace Database\Seeders;

class ProductCatalogDataPart1
{
    public static function get(): array
    {
        return [
            // 1. Smartphones & Mobile Tech (cat_slug: smartphones-mobile-tech)
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'flagship-smartphones',
                'brand_slug' => 'apple',
                'title' => 'Apple iPhone 15 Pro Max 256GB',
                'slug' => 'apple-iphone-15-pro-max-256gb',
                'sku' => 'APP-IPH15PM-256',
                'price' => 179999,
                'sale_price' => 169999,
                'cost_price' => 150000,
                'stock' => 24,
                'weight' => '221g',
                'dimensions' => '159.9 x 76.7 x 8.3 mm',
                'is_featured' => true,
                'is_best_seller' => true,
                'warranty' => '1 Year Apple Official Warranty',
                'description' => '<p>iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.</p>',
                'short_description' => 'A17 Pro chip, Titanium design, 48MP main camera with 5x optical zoom.',
                'has_variants' => true,
                'variant_type' => 'storage_color',
                'specs' => [
                    'Display' => '6.7-inch Super Retina XDR OLED 120Hz',
                    'Processor' => 'Apple A17 Pro (3nm)',
                    'Main Camera' => '48MP + 12MP + 12MP with 5x Optical Zoom',
                    'Battery' => '4422 mAh with 20W fast charging',
                    'OS' => 'iOS 17'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'flagship-smartphones',
                'brand_slug' => 'samsung',
                'title' => 'Samsung Galaxy S24 Ultra 5G',
                'slug' => 'samsung-galaxy-s24-ultra-5g',
                'sku' => 'SAM-S24U-256',
                'price' => 164999,
                'sale_price' => 154999,
                'cost_price' => 135000,
                'stock' => 18,
                'weight' => '232g',
                'dimensions' => '162.3 x 79.0 x 8.6 mm',
                'is_featured' => true,
                'is_trending' => true,
                'warranty' => '1 Year Official Samsung Warranty',
                'description' => '<p>Galaxy S24 Ultra with Galaxy AI, Titanium frame, integrated S Pen, and 200MP quad camera system.</p>',
                'short_description' => 'Snapdragon 8 Gen 3 for Galaxy, S Pen, 200MP camera, Galaxy AI.',
                'has_variants' => true,
                'variant_type' => 'storage_color',
                'specs' => [
                    'Display' => '6.8-inch Dynamic AMOLED 2X 120Hz QHD+',
                    'Processor' => 'Qualcomm Snapdragon 8 Gen 3',
                    'Main Camera' => '200MP + 50MP + 12MP + 10MP',
                    'Battery' => '5000 mAh 45W fast charge',
                    'OS' => 'Android 14, One UI 6.1'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'flagship-smartphones',
                'brand_slug' => 'google',
                'title' => 'Google Pixel 8 Pro 128GB',
                'slug' => 'google-pixel-8-pro-128gb',
                'sku' => 'GOO-PIX8P-128',
                'price' => 112000,
                'sale_price' => 104999,
                'cost_price' => 92000,
                'stock' => 12,
                'weight' => '213g',
                'dimensions' => '162.6 x 76.5 x 8.8 mm',
                'is_featured' => false,
                'is_new_arrival' => true,
                'warranty' => '1 Year Service Warranty',
                'description' => '<p>Pixel 8 Pro is engineered by Google with Google Tensor G3 and advanced AI camera capabilities.</p>',
                'short_description' => 'Google Tensor G3, Super Actua display, Best Take, Audio Magic Eraser.',
                'has_variants' => true,
                'variant_type' => 'storage_color',
                'specs' => [
                    'Display' => '6.7-inch LTPO OLED 120Hz',
                    'Processor' => 'Google Tensor G3 (4nm)',
                    'Main Camera' => '50MP + 48MP + 48MP',
                    'Battery' => '5050 mAh 30W wired',
                    'OS' => 'Android 14 (7 years OS updates)'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'flagship-smartphones',
                'brand_slug' => 'oneplus',
                'title' => 'OnePlus 12 5G 16GB/512GB',
                'slug' => 'oneplus-12-5g-16gb-512gb',
                'sku' => '1PL-12-512',
                'price' => 96999,
                'sale_price' => 89999,
                'cost_price' => 78000,
                'stock' => 15,
                'weight' => '220g',
                'dimensions' => '164.3 x 75.8 x 9.2 mm',
                'is_featured' => false,
                'is_trending' => true,
                'warranty' => '1 Year Official Warranty',
                'description' => '<p>OnePlus 12 features 4th Gen Hasselblad Camera, 2K 120Hz ProXDR display, and 100W SUPERVOOC charging.</p>',
                'short_description' => 'Snapdragon 8 Gen 3, 5400 mAh Battery, 100W SUPERVOOC charge.',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'specs' => [
                    'Display' => '6.82-inch 2K 120Hz ProXDR AMOLED',
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'RAM' => '16GB LPDDR5X',
                    'Storage' => '512GB UFS 4.0',
                    'Battery' => '5400 mAh 100W'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'mid-range-smartphones',
                'brand_slug' => 'xiaomi',
                'title' => 'Xiaomi Redmi Note 13 Pro+ 5G',
                'slug' => 'xiaomi-redmi-note-13-pro-plus-5g',
                'sku' => 'XIA-RN13PP-256',
                'price' => 45999,
                'sale_price' => 42999,
                'cost_price' => 37000,
                'stock' => 35,
                'weight' => '204g',
                'dimensions' => '161.4 x 74.2 x 8.9 mm',
                'is_featured' => true,
                'is_best_seller' => true,
                'warranty' => '1 Year Xiaomi Official Warranty',
                'description' => '<p>Redmi Note 13 Pro+ 5G features 200MP camera with OIS, 1.5K curved AMOLED display, and 120W HyperCharge.</p>',
                'short_description' => '200MP OIS Camera, IP68 water resistance, 120W HyperCharge.',
                'has_variants' => true,
                'variant_type' => 'storage_color',
                'specs' => [
                    'Display' => '6.67-inch 1.5K CrystalRes AMOLED 120Hz',
                    'Processor' => 'MediaTek Dimensity 7200-Ultra',
                    'Camera' => '200MP OIS Ultra-Clear',
                    'Charging' => '120W HyperCharge 100% in 19 mins',
                    'Rating' => 'IP68 Dust & Water Resistant'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'mid-range-smartphones',
                'brand_slug' => 'samsung',
                'title' => 'Samsung Galaxy A55 5G 8GB/256GB',
                'slug' => 'samsung-galaxy-a55-5g-8gb-256gb',
                'sku' => 'SAM-A55-256',
                'price' => 54999,
                'sale_price' => null,
                'cost_price' => 47000,
                'stock' => 20,
                'weight' => '213g',
                'dimensions' => '161.1 x 77.4 x 8.2 mm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '1 Year Official Samsung Warranty',
                'description' => '<p>Galaxy A55 5G with metal frame, Corning Gorilla Glass Victus+, and Nightography camera system.</p>',
                'short_description' => 'Exynos 1480, Super AMOLED 120Hz, IP67 water resistant.',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'specs' => [
                    'Display' => '6.6-inch Super AMOLED 120Hz HDR10+',
                    'Processor' => 'Exynos 1480 (4nm) with AMD Xclipse 530 GPU',
                    'Camera' => '50MP OIS Main + 12MP Ultra-wide',
                    'Battery' => '5000 mAh 25W',
                    'Build' => 'Glass front/back, aluminum frame'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'budget-smartphones',
                'brand_slug' => 'xiaomi',
                'title' => 'Xiaomi Redmi 13C 6GB/128GB',
                'slug' => 'xiaomi-redmi-13c-6gb-128gb',
                'sku' => 'XIA-R13C-128',
                'price' => 15499,
                'sale_price' => 14499,
                'cost_price' => 12500,
                'stock' => 40,
                'weight' => '192g',
                'dimensions' => '168 x 78 x 8.1 mm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '1 Year Official Warranty',
                'description' => '<p>Smooth 6.74" 90Hz display, 50MP AI triple camera, and massive 5000mAh battery.</p>',
                'short_description' => '90Hz 6.74" screen, 50MP triple camera, 5000mAh battery.',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'specs' => [
                    'Display' => '6.74-inch 90Hz IPS LCD',
                    'Processor' => 'MediaTek Helio G85',
                    'Camera' => '50MP AI Dual Camera',
                    'Battery' => '5000 mAh 18W Type-C',
                    'Security' => 'Side fingerprint sensor'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'budget-smartphones',
                'brand_slug' => 'samsung',
                'title' => 'Samsung Galaxy A05s 4GB/64GB',
                'slug' => 'samsung-galaxy-a05s-4gb-64gb',
                'sku' => 'SAM-A05S-64',
                'price' => 17999,
                'sale_price' => 16500,
                'cost_price' => 14000,
                'stock' => 28,
                'weight' => '194g',
                'dimensions' => '168.0 x 77.8 x 8.8 mm',
                'is_featured' => false,
                'is_new_arrival' => false,
                'warranty' => '1 Year Samsung Warranty',
                'description' => '<p>Immerse yourself in the large 6.7-inch FHD+ display with Snapdragon 680 power.</p>',
                'short_description' => 'Snapdragon 680, 50MP Main camera, 6.7" FHD+ 90Hz.',
                'has_variants' => false,
                'specs' => [
                    'Display' => '6.7-inch FHD+ 90Hz PLS LCD',
                    'Processor' => 'Qualcomm Snapdragon 680 4G',
                    'Main Camera' => '50MP + 2MP + 2MP',
                    'Battery' => '5000 mAh 25W Fast Charge'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'budget-smartphones',
                'brand_slug' => 'walton',
                'title' => 'Walton Primo S8 Mini 6GB/64GB',
                'slug' => 'walton-primo-s8-mini-6gb-64gb',
                'sku' => 'WAL-S8M-64',
                'price' => 13999,
                'sale_price' => 12999,
                'cost_price' => 10500,
                'stock' => 16,
                'weight' => '189g',
                'dimensions' => '164 x 76 x 8.6 mm',
                'is_featured' => false,
                'is_best_seller' => false,
                'warranty' => '1 Year Official Walton Warranty',
                'description' => '<p>Proudly Made in Bangladesh with punch-hole display and gaming processor.</p>',
                'short_description' => 'Snapdragon 665, 6GB RAM, punch-hole FHD+ display.',
                'has_variants' => false,
                'specs' => [
                    'Display' => '6.53-inch FHD+ LTPS LCD',
                    'Processor' => 'Qualcomm Snapdragon 665',
                    'Camera' => '16MP Quad Rear Camera',
                    'Battery' => '5000 mAh'
                ]
            ],
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'sub_slug' => 'feature-phones',
                'brand_slug' => 'walton',
                'title' => 'Walton Olvio MM26 Feature Phone',
                'slug' => 'walton-olvio-mm26-feature-phone',
                'sku' => 'WAL-OLV-MM26',
                'price' => 1850,
                'sale_price' => 1699,
                'cost_price' => 1300,
                'stock' => 50,
                'weight' => '95g',
                'dimensions' => '124 x 52 x 13.8 mm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '1 Year Official Warranty',
                'description' => '<p>Long-lasting 1800mAh battery with wireless FM radio, torch, and digital camera.</p>',
                'short_description' => 'Dual SIM, Wireless FM, 1800mAh battery, Loud speaker.',
                'has_variants' => false,
                'specs' => [
                    'Display' => '2.4-inch QVGA Bright Screen',
                    'Battery' => '1800 mAh Li-ion',
                    'Features' => 'Wireless FM, Audio Player, Bluetooth, Flashlight',
                    'SIM' => 'Dual SIM Dual Standby'
                ]
            ],

            // 2. Laptops & Ultrabooks (cat_slug: laptops-ultrabooks)
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'thin-light-ultrabooks',
                'brand_slug' => 'apple',
                'title' => 'Apple MacBook Pro 16 M3 Max',
                'slug' => 'apple-macbook-pro-16-m3-max',
                'sku' => 'APP-MBP16-M3M',
                'price' => 449999,
                'sale_price' => 429999,
                'cost_price' => 390000,
                'stock' => 8,
                'weight' => '2.16 kg',
                'dimensions' => '35.57 x 24.81 x 1.68 cm',
                'is_featured' => true,
                'is_trending' => true,
                'warranty' => '1 Year Apple International Warranty',
                'description' => '<p>The 16-inch MacBook Pro blasts forward with M3 Max, an unimaginably advanced chip that delivers massive performance for extreme workflows.</p>',
                'short_description' => 'M3 Max 16-core CPU, 40-core GPU, 48GB Unified Memory, 1TB SSD.',
                'has_variants' => true,
                'variant_type' => 'laptop_ram_storage',
                'specs' => [
                    'Processor' => 'Apple M3 Max 16-core CPU',
                    'Display' => '16.2-inch Liquid Retina XDR 120Hz ProMotion',
                    'Memory' => '48GB Unified Memory',
                    'Storage' => '1TB High Speed NVMe SSD',
                    'Battery Life' => 'Up to 22 hours video playback'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'thin-light-ultrabooks',
                'brand_slug' => 'apple',
                'title' => 'Apple MacBook Air 13 M3',
                'slug' => 'apple-macbook-air-13-m3',
                'sku' => 'APP-MBA13-M3',
                'price' => 148000,
                'sale_price' => 139999,
                'cost_price' => 125000,
                'stock' => 22,
                'weight' => '1.24 kg',
                'dimensions' => '30.41 x 21.5 x 1.13 cm',
                'is_featured' => true,
                'is_best_seller' => true,
                'warranty' => '1 Year Apple Official Warranty',
                'description' => '<p>Supercharged by the next-generation M3 chip, the redesigned MacBook Air combines incredible performance with up to 18 hours of battery life.</p>',
                'short_description' => 'M3 chip 8-core CPU, 13.6" Liquid Retina display, ultra-thin 11mm unibody.',
                'has_variants' => true,
                'variant_type' => 'laptop_ram_storage',
                'specs' => [
                    'Processor' => 'Apple M3 8-core CPU 10-core GPU',
                    'Display' => '13.6-inch Liquid Retina Display 500 nits',
                    'Memory' => '16GB Unified Memory',
                    'Storage' => '512GB SSD',
                    'Weight' => '1.24 kg fanless silent design'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'gaming-laptops',
                'brand_slug' => 'asus',
                'title' => 'ASUS ROG Zephyrus G16 OLED Gaming Laptop',
                'slug' => 'asus-rog-zephyrus-g16-oled-gaming-laptop',
                'sku' => 'ASU-ROG-G16-4070',
                'price' => 285000,
                'sale_price' => 269999,
                'cost_price' => 240000,
                'stock' => 10,
                'weight' => '1.85 kg',
                'dimensions' => '35.4 x 24.6 x 1.49 cm',
                'is_featured' => true,
                'is_trending' => true,
                'warranty' => '2 Years ASUS Global Warranty',
                'description' => '<p>Ultra-slim aluminum CNC chassis with ROG Nebula 2.5K 240Hz OLED display, Intel Core Ultra 9, and RTX 4070.</p>',
                'short_description' => 'Intel Core Ultra 9 185H, RTX 4070 8GB, 2.5K 240Hz OLED.',
                'has_variants' => true,
                'variant_type' => 'laptop_ram_storage',
                'specs' => [
                    'Processor' => 'Intel Core Ultra 9 185H (16 cores)',
                    'Graphics' => 'NVIDIA GeForce RTX 4070 8GB GDDR6',
                    'Display' => '16-inch 2.5K (2560x1600) 240Hz 0.2ms OLED',
                    'RAM' => '32GB LPDDR5X 7467MHz',
                    'Storage' => '1TB PCIe 4.0 NVMe SSD'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'gaming-laptops',
                'brand_slug' => 'lenovo',
                'title' => 'Lenovo Legion Pro 7i Gen 9',
                'slug' => 'lenovo-legion-pro-7i-gen-9',
                'sku' => 'LEN-LEG-PRO7-4080',
                'price' => 345000,
                'sale_price' => 329000,
                'cost_price' => 295000,
                'stock' => 7,
                'weight' => '2.6 kg',
                'dimensions' => '36.3 x 26.2 x 2.59 cm',
                'is_featured' => false,
                'is_trending' => true,
                'warranty' => '2 Years Lenovo Warranty',
                'description' => '<p>Lenovo Legion Pro 7i powered by Intel Core i9-14900HX and full-powered NVIDIA GeForce RTX 4080 with Legion Coldfront 5.0 vapor chamber.</p>',
                'short_description' => 'Intel i9-14900HX, RTX 4080 12GB 175W TGP, 16" 240Hz PureSight.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i9-14900HX 24 cores',
                    'Graphics' => 'NVIDIA RTX 4080 12GB GDDR6 175W',
                    'Display' => '16-inch WQXGA 240Hz 500 nits 100% DCI-P3',
                    'RAM' => '32GB DDR5 5600MHz',
                    'Storage' => '1TB M.2 PCIe 4.0 NVMe'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'business-laptops',
                'brand_slug' => 'dell',
                'title' => 'Dell XPS 15 9530 Core i7',
                'slug' => 'dell-xps-15-9530-core-i7',
                'sku' => 'DEL-XPS15-9530',
                'price' => 259000,
                'sale_price' => 244999,
                'cost_price' => 220000,
                'stock' => 12,
                'weight' => '1.92 kg',
                'dimensions' => '34.4 x 23.0 x 1.8 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '2 Years Dell ProSupport Warranty',
                'description' => '<p>Stunning 15.6" InfinityEdge display with machined aluminum chassis and carbon fiber palm rest.</p>',
                'short_description' => 'Intel Core i7-13700H, RTX 4050 6GB, 16GB RAM, 512GB SSD.',
                'has_variants' => true,
                'variant_type' => 'laptop_ram_storage',
                'specs' => [
                    'Processor' => 'Intel Core i7-13700H (14 cores)',
                    'Display' => '15.6-inch FHD+ (1920x1200) InfinityEdge 500 nits',
                    'RAM' => '16GB DDR5 4800MHz',
                    'Storage' => '512GB PCIe NVMe SSD',
                    'Audio' => 'Quad-speaker design with Waves Nx 3D audio'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'business-laptops',
                'brand_slug' => 'lenovo',
                'title' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'slug' => 'lenovo-thinkpad-x1-carbon-gen-11',
                'sku' => 'LEN-X1C-GEN11',
                'price' => 218000,
                'sale_price' => 205000,
                'cost_price' => 185000,
                'stock' => 14,
                'weight' => '1.12 kg',
                'dimensions' => '31.5 x 22.2 x 1.5 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '3 Years Onsite Warranty',
                'description' => '<p>The pinnacle of business mobility. Featherlight carbon fiber construction with legendary ThinkPad keyboard.</p>',
                'short_description' => 'Intel Core i7-1365U vPro, 16GB RAM, 512GB SSD, MIL-SPEC tested.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i7-1365U 10-core vPro',
                    'Display' => '14.0-inch WUXGA IPS Low Power Anti-glare',
                    'RAM' => '16GB LPDDR5 6400MHz',
                    'Weight' => 'Just 1.12 kg ultralight',
                    'Security' => 'dTPM 2.0, Fingerprint, IR camera with shutter'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => '2-in-1-convertibles',
                'brand_slug' => 'hp',
                'title' => 'HP Spectre x360 14 2-in-1 OLED',
                'slug' => 'hp-spectre-x360-14-2-in-1-oled',
                'sku' => 'HP-SPEC-14-OLED',
                'price' => 198000,
                'sale_price' => 189999,
                'cost_price' => 170000,
                'stock' => 11,
                'weight' => '1.44 kg',
                'dimensions' => '31.3 x 22.0 x 1.69 cm',
                'is_featured' => true,
                'is_new_arrival' => true,
                'warranty' => '2 Years HP Official Warranty',
                'description' => '<p>Stunning gem-cut design with 2.8K 120Hz OLED touchscreen, stylus pen included, and 9MP AI camera.</p>',
                'short_description' => 'Intel Core Ultra 7 155H, 2.8K 120Hz OLED touch, 360-degree hinge.',
                'has_variants' => true,
                'variant_type' => 'laptop_ram_storage',
                'specs' => [
                    'Processor' => 'Intel Core Ultra 7 155H (16 cores)',
                    'Display' => '14-inch 2.8K (2880x1800) OLED 120Hz Touch',
                    'Memory' => '16GB LPDDR5X RAM',
                    'Storage' => '1TB PCIe Gen4 NVMe M.2 SSD',
                    'Stylus' => 'HP Rechargeable MPP 2.0 Tilt Pen included'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'business-laptops',
                'brand_slug' => 'hp',
                'title' => 'HP Envy 16 Core i7 Laptop',
                'slug' => 'hp-envy-16-core-i7-laptop',
                'sku' => 'HP-ENVY-16-I7',
                'price' => 175000,
                'sale_price' => 165000,
                'cost_price' => 148000,
                'stock' => 15,
                'weight' => '2.3 kg',
                'dimensions' => '35.7 x 25.2 x 1.99 cm',
                'is_featured' => false,
                'is_best_seller' => false,
                'warranty' => '2 Years HP Official Warranty',
                'description' => '<p>Creator powerhouse laptop with RTX 4060 graphics, 120Hz display, and Bang & Olufsen quad speakers.</p>',
                'short_description' => 'Core i7-13700H, RTX 4060 8GB, 16GB DDR5, 1TB SSD.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i7-13700H 14 Cores',
                    'Graphics' => 'NVIDIA GeForce RTX 4060 8GB',
                    'Display' => '16-inch WQXGA (2560 x 1600) 120Hz',
                    'Storage' => '1TB PCIe NVMe SSD'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'gaming-laptops',
                'brand_slug' => 'acer',
                'title' => 'Acer Predator Helios 16 Gaming Laptop',
                'slug' => 'acer-predator-helios-16-gaming-laptop',
                'sku' => 'ACE-PRED-16-4070',
                'price' => 245000,
                'sale_price' => 229999,
                'cost_price' => 205000,
                'stock' => 10,
                'weight' => '2.6 kg',
                'dimensions' => '36.0 x 27.9 x 2.69 cm',
                'is_featured' => false,
                'is_trending' => true,
                'warranty' => '2 Years Acer Official Warranty',
                'description' => '<p>Predator Helios 16 equipped with 5th Gen AeroBlade 3D fan technology and liquid metal thermal grease.</p>',
                'short_description' => 'Intel Core i7-13700HX, RTX 4070 8GB, 16" 240Hz IPS 100% DCI-P3.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i7-13700HX 16 Cores',
                    'Graphics' => 'NVIDIA GeForce RTX 4070 8GB GDDR6',
                    'Display' => '16-inch 2560x1600 240Hz 3ms G-SYNC',
                    'Cooling' => 'Dual custom AeroBlade 3D metal fans'
                ]
            ],
            [
                'cat_slug' => 'laptops-ultrabooks',
                'sub_slug' => 'gaming-laptops',
                'brand_slug' => 'msi',
                'title' => 'MSI Katana 15 Gaming Laptop Core i7',
                'slug' => 'msi-katana-15-gaming-laptop-core-i7',
                'sku' => 'MSI-KAT15-4060',
                'price' => 155000,
                'sale_price' => 146999,
                'cost_price' => 130000,
                'stock' => 18,
                'weight' => '2.25 kg',
                'dimensions' => '35.9 x 25.9 x 2.49 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '2 Years MSI Warranty',
                'description' => '<p>Sharpen your game with the MSI Katana 15, featuring 4-Zone RGB keyboard and Cooler Boost 5.</p>',
                'short_description' => 'Core i7-13620H, RTX 4060 8GB, 15.6" 144Hz FHD IPS.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i7-13620H 10 cores',
                    'Graphics' => 'NVIDIA GeForce RTX 4060 8GB GDDR6',
                    'Display' => '15.6-inch FHD 144Hz IPS-level',
                    'RAM' => '16GB DDR5 5200MHz',
                    'Storage' => '1TB NVMe PCIe Gen4'
                ]
            ],

            // 3. Desktop Computers (cat_slug: desktop-computers)
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'all-in-one-pcs',
                'brand_slug' => 'apple',
                'title' => 'Apple iMac 24 4.5K Retina M3',
                'slug' => 'apple-imac-24-4-5k-retina-m3',
                'sku' => 'APP-IMAC24-M3',
                'price' => 195000,
                'sale_price' => 185000,
                'cost_price' => 165000,
                'stock' => 9,
                'weight' => '4.43 kg',
                'dimensions' => '54.7 x 46.1 x 14.7 cm',
                'is_featured' => true,
                'is_best_seller' => false,
                'warranty' => '1 Year Apple Official Warranty',
                'description' => '<p>The world\'s best all-in-one computer, now supercharged by the M3 chip in an impossibly thin design.</p>',
                'short_description' => 'M3 8-core CPU 10-core GPU, 24" 4.5K Retina display, 1080p FaceTime camera.',
                'has_variants' => false,
                'specs' => [
                    'Display' => '24-inch 4.5K Retina 4480x2520 500 nits',
                    'Chip' => 'Apple M3 8-core CPU 10-core GPU',
                    'Memory' => '8GB Unified Memory',
                    'Storage' => '512GB SSD',
                    'Accessories' => 'Color-matched Magic Keyboard with Touch ID & Magic Mouse'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'mini-pcs',
                'brand_slug' => 'apple',
                'title' => 'Apple Mac mini M2 Pro 16GB/512GB',
                'slug' => 'apple-mac-mini-m2-pro-16gb-512gb',
                'sku' => 'APP-MACMINI-M2P',
                'price' => 165000,
                'sale_price' => 155000,
                'cost_price' => 140000,
                'stock' => 14,
                'weight' => '1.28 kg',
                'dimensions' => '19.7 x 19.7 x 3.58 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '1 Year Apple Official Warranty',
                'description' => '<p>More muscle. More hustle. Mac mini with M2 Pro packs pro-level performance into its iconic mini frame.</p>',
                'short_description' => 'M2 Pro 10-core CPU, 16-core GPU, 16GB Unified RAM, 512GB SSD.',
                'has_variants' => false,
                'specs' => [
                    'Chip' => 'Apple M2 Pro 10-core CPU 16-core GPU',
                    'Memory' => '16GB Unified Memory',
                    'Storage' => '512GB High Speed SSD',
                    'Ports' => '4x Thunderbolt 4, HDMI, 2x USB-A, Gigabit Ethernet'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'custom-gaming-pcs',
                'brand_slug' => 'asus',
                'title' => 'ASUS ROG Strix G16CHR Gaming Desktop',
                'slug' => 'asus-rog-strix-g16chr-gaming-desktop',
                'sku' => 'ASU-ROG-G16CHR',
                'price' => 220000,
                'sale_price' => 209999,
                'cost_price' => 185000,
                'stock' => 6,
                'weight' => '11 kg',
                'dimensions' => '18.0 x 43.0 x 42.8 cm',
                'is_featured' => true,
                'is_trending' => true,
                'warranty' => '2 Years Official Warranty',
                'description' => '<p>Ready-to-game desktop tower with Intel Core i7-14700F, RTX 4070 Dual, and Aura Sync RGB.</p>',
                'short_description' => 'Core i7-14700F, RTX 4070 12GB, 32GB DDR5, 1TB NVMe SSD.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i7-14700F 20 cores',
                    'Graphics' => 'NVIDIA GeForce RTX 4070 12GB',
                    'Memory' => '32GB DDR5 5600MHz',
                    'Storage' => '1TB M.2 NVMe PCIe 4.0 SSD',
                    'Chassis' => 'Airflow optimized with tempered glass panel'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'workstations',
                'brand_slug' => 'dell',
                'title' => 'Dell Precision 3660 Tower Workstation',
                'slug' => 'dell-precision-3660-tower-workstation',
                'sku' => 'DEL-PREC-3660',
                'price' => 275000,
                'sale_price' => null,
                'cost_price' => 245000,
                'stock' => 5,
                'weight' => '8.5 kg',
                'dimensions' => '17.3 x 36.9 x 42.0 cm',
                'is_featured' => false,
                'is_best_seller' => false,
                'warranty' => '3 Years Dell ProSupport Onsite',
                'description' => '<p>Cost-effective tower workstation with VR and AI-ready performance for CAD and 3D modeling.</p>',
                'short_description' => 'Intel Core i9-13900, 32GB ECC RAM, NVIDIA RTX A2000 12GB.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i9-13900 24 cores',
                    'GPU' => 'NVIDIA RTX A2000 12GB Workstation Graphics',
                    'RAM' => '32GB DDR5 ECC memory',
                    'Storage' => '1TB NVMe Class 40 SSD + 2TB 7200RPM HDD',
                    'ISV Certified' => 'Certified for AutoCAD, SolidWorks, Maya'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'all-in-one-pcs',
                'brand_slug' => 'hp',
                'title' => 'HP Pavilion 27 All-in-One PC Core i7',
                'slug' => 'hp-pavilion-27-all-in-one-pc-core-i7',
                'sku' => 'HP-PAV-27-AIO',
                'price' => 145000,
                'sale_price' => 137000,
                'cost_price' => 122000,
                'stock' => 10,
                'weight' => '8.9 kg',
                'dimensions' => '61.4 x 20.8 x 47.1 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '2 Years HP Official Warranty',
                'description' => '<p>Sleek 27-inch micro-edge touchscreen PC with pop-up privacy camera and wireless keyboard/mouse.</p>',
                'short_description' => 'Core i7-13700T, 16GB RAM, 1TB SSD, 27" FHD IPS touch display.',
                'has_variants' => false,
                'specs' => [
                    'Display' => '27-inch FHD IPS three-sided micro-edge Touch',
                    'Processor' => 'Intel Core i7-13700T (16 cores)',
                    'Audio' => 'Audio by B&O with dual 5W speakers',
                    'Accessories' => 'HP wireless white keyboard and optical mouse'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'mini-pcs',
                'brand_slug' => 'asus',
                'title' => 'ASUS ExpertCenter PN64 Mini PC',
                'slug' => 'asus-expertcenter-pn64-mini-pc',
                'sku' => 'ASU-PN64-I5',
                'price' => 68000,
                'sale_price' => 63999,
                'cost_price' => 54000,
                'stock' => 17,
                'weight' => '0.9 kg',
                'dimensions' => '12.0 x 13.0 x 5.8 cm',
                'is_featured' => false,
                'is_new_arrival' => true,
                'warranty' => '3 Years ASUS Warranty',
                'description' => '<p>Ultra-compact mini PC powered by 13th Gen Intel Core i5 with quad-display 4K support.</p>',
                'short_description' => 'Core i5-13500H, 16GB DDR5, 512GB NVMe, Quad 4K support.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i5-13500H 12 cores',
                    'Memory' => '16GB DDR5 4800MHz',
                    'Storage' => '512GB M.2 NVMe PCIe Gen4',
                    'Connectivity' => 'WiFi 6E, 2.5G LAN, 2x HDMI 2.1, 1x DP 1.4'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'workstations',
                'brand_slug' => 'apple',
                'title' => 'Apple Mac Studio M2 Max',
                'slug' => 'apple-mac-studio-m2-max',
                'sku' => 'APP-STUDIO-M2M',
                'price' => 285000,
                'sale_price' => 269999,
                'cost_price' => 245000,
                'stock' => 7,
                'weight' => '2.7 kg',
                'dimensions' => '19.7 x 19.7 x 9.5 cm',
                'is_featured' => true,
                'is_trending' => true,
                'warranty' => '1 Year Apple Official Warranty',
                'description' => '<p>Embraced by studio professionals everywhere, Mac Studio delivers extraordinary power driven by the M2 Max chip.</p>',
                'short_description' => 'M2 Max 12-core CPU 30-core GPU, 32GB Unified Memory, 512GB SSD.',
                'has_variants' => false,
                'specs' => [
                    'Chip' => 'Apple M2 Max 12-core CPU 30-core GPU',
                    'Memory' => '32GB Unified Memory (400GB/s bandwidth)',
                    'Storage' => '512GB High Speed SSD',
                    'Display Support' => 'Supports up to 5 displays simultaneously'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'custom-gaming-pcs',
                'brand_slug' => 'msi',
                'title' => 'MSI MAG Infinite S3 Gaming Desktop',
                'slug' => 'msi-mag-infinite-s3-gaming-desktop',
                'sku' => 'MSI-INF-S3-4060',
                'price' => 165000,
                'sale_price' => 155000,
                'cost_price' => 138000,
                'stock' => 11,
                'weight' => '7.7 kg',
                'dimensions' => '17.3 x 44.7 x 40.7 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '2 Years MSI Warranty',
                'description' => '<p>Compact gaming desktop with Mystic Light RGB and Silent Storm Cooling 2 architecture.</p>',
                'short_description' => 'Core i5-14400F, RTX 4060 8GB, 16GB DDR5, 1TB SSD.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i5-14400F 10 cores',
                    'Graphics' => 'NVIDIA GeForce RTX 4060 8GB',
                    'RAM' => '16GB DDR5',
                    'Storage' => '1TB M.2 PCIe NVMe SSD'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'all-in-one-pcs',
                'brand_slug' => 'lenovo',
                'title' => 'Lenovo IdeaCentre AIO 3 24-inch Core i5',
                'slug' => 'lenovo-ideacentre-aio-3-24-inch-core-i5',
                'sku' => 'LEN-AIO3-24-I5',
                'price' => 84000,
                'sale_price' => 79999,
                'cost_price' => 69000,
                'stock' => 16,
                'weight' => '7.0 kg',
                'dimensions' => '54.1 x 18.5 x 43.3 cm',
                'is_featured' => false,
                'is_best_seller' => true,
                'warranty' => '2 Years Lenovo Warranty',
                'description' => '<p>Family home PC with Harman Kardon stereo speakers, sleek wire management stand, and FHD display.</p>',
                'short_description' => 'Core i5-12450H, 8GB DDR4, 512GB SSD, 23.8" FHD IPS.',
                'has_variants' => false,
                'specs' => [
                    'Display' => '23.8-inch FHD (1920x1080) IPS 250 nits',
                    'Processor' => 'Intel Core i5-12450H 8 cores',
                    'Sound' => '2x 3W stereo speakers tuned by Harman',
                    'Includes' => 'Wireless Calliope keyboard and mouse'
                ]
            ],
            [
                'cat_slug' => 'desktop-computers',
                'sub_slug' => 'mini-pcs',
                'brand_slug' => 'dell',
                'title' => 'Dell OptiPlex 7010 Micro Desktop',
                'slug' => 'dell-optiplex-7010-micro-desktop',
                'sku' => 'DEL-OPT-7010M',
                'price' => 72000,
                'sale_price' => null,
                'cost_price' => 60000,
                'stock' => 20,
                'weight' => '1.34 kg',
                'dimensions' => '18.2 x 3.6 x 17.8 cm',
                'is_featured' => false,
                'is_best_seller' => false,
                'warranty' => '3 Years Dell Basic Onsite',
                'description' => '<p>Ultra-compact enterprise PC with flexible mounting options behind monitors and under desks.</p>',
                'short_description' => 'Intel Core i5-13500T, 16GB DDR4, 512GB PCIe SSD, Windows 11 Pro.',
                'has_variants' => false,
                'specs' => [
                    'Processor' => 'Intel Core i5-13500T 14 cores vPro',
                    'RAM' => '16GB DDR4 3200MHz',
                    'Storage' => '512GB M.2 2230 PCIe NVMe SSD',
                    'OS' => 'Windows 11 Pro 64-bit'
                ]
            ],
        ];
    }
}
