<?php

namespace Database\Seeders;

class ProductCatalogDefinitionPart3
{
    public static function get(): array
    {
        return [
            // 31. Living Room Furniture
            [
                'cat_slug' => 'living-room-furniture',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'IKEA Kivik 3-Seat Sofa with Chaise Lounge', 'brand' => 'ikea', 'sub' => 0, 'price' => 58000, 'sale' => 54000, 'stock' => 8, 'specs' => ['Cover' => 'Removable, machine washable durable fabric cover', 'Comfort' => 'Pocket spring core with memory foam top layer', 'Armrests' => 'Low wide armrests double as comfortable headrests', 'Warranty' => '10-Year IKEA limited guarantee']],
                    ['title' => 'IKEA Besta TV Media Console Storage Unit Oak', 'brand' => 'ikea', 'sub' => 2, 'price' => 24500, 'sale' => 22000, 'stock' => 14, 'specs' => ['Dimensions' => '180 x 42 x 64 cm', 'Management' => 'Integrated cable outlets keep cords out of sight', 'Drawers' => 'Push-open soft closing drawer runners', 'Shelving' => 'Adjustable interior shelves hold gaming consoles and soundbars']],
                    ['title' => 'IKEA Poang Classic Armchair with Leather Cushion', 'brand' => 'ikea', 'sub' => 3, 'price' => 16500, 'sale' => 14999, 'stock' => 18, 'specs' => ['Frame' => 'Layer-glued bent birch wood provides resilient flex', 'Cushion' => 'Supple genuine top-grain dyed cow leather', 'Ergonomics' => 'High back provides pleasant support for neck', 'Design' => 'Iconic Scandinavian silhouette created in 1976']],
                    ['title' => 'Hatil Solid Oak Wood Center Coffee Table', 'brand' => 'apex', 'sub' => 1, 'price' => 14500, 'sale' => 12999, 'stock' => 20, 'specs' => ['Timber' => 'Kiln-dried seasoned imported oak wood and veneered engineered wood', 'Finish' => 'Eco-friendly Italian UV lacquer finish resistant to stains', 'Glass' => '8mm thick beveled tempered glass tabletop', 'Shelf' => 'Lower open slatted shelf for magazines and remotes']],
                    ['title' => 'Hatil Chesterfield Royal Velvet 3-Seater Couch', 'brand' => 'apex', 'sub' => 0, 'price' => 48000, 'sale' => 43500, 'stock' => 6, 'specs' => ['Upholstery' => 'Imported stain-resistant micro velvet fabric', 'Tufting' => 'Deep hand-tufted diamond buttons across back and arms', 'Foam' => 'High-density HR foam with serpentine spring base', 'Legs' => 'Turned solid antique walnut finished wooden legs']],
                    ['title' => 'IKEA Gladom Removable Tray Metal Coffee Table', 'brand' => 'ikea', 'sub' => 1, 'price' => 2800, 'sale' => 2450, 'stock' => 45, 'specs' => ['Versatility' => 'Removable top tray serves as serving platter for drinks', 'Material' => 'Powder coated steel rust-resistant frame', 'Diameter' => '45 cm compact footprint fits anywhere', 'Weight' => 'Lightweight 3.2 kg easily moved around living room']],
                    ['title' => 'Hatil Scandinavian Single Lounge Accent Chair', 'brand' => 'apex', 'sub' => 3, 'price' => 18500, 'sale' => 16500, 'stock' => 12, 'specs' => ['Fabric' => 'Textured bouclé woven designer upholstery', 'Frame' => 'Solid Beechwood tapered splayed legs', 'Comfort' => 'Contoured wraparound barrel wingback profile', 'Pillow' => 'Includes matching lumbar toss cushion']],
                    ['title' => 'Otobi Modern Floating TV Wall Unit Walnut', 'brand' => 'walton', 'sub' => 2, 'price' => 18000, 'sale' => 15999, 'stock' => 15, 'specs' => ['Design' => 'Wall-mounted floating entertainment console', 'Material' => 'High-density melamine faced chipboard (MFC)', 'Panels' => 'Textured walnut woodgrain laminate with black accents', 'Size' => 'Accommodates TVs up to 65 inches']],
                    ['title' => 'Otobi L-Shape Fabric Corner Sectional Sofa', 'brand' => 'walton', 'sub' => 0, 'price' => 42000, 'sale' => 38000, 'stock' => 9, 'specs' => ['Configuration' => 'Reversible modular chaise can be set left or right', 'Fabric' => 'Heavy commercial grade woven linen upholstery', 'Cushions' => 'Zippered removable pillow covers for dry cleaning', 'Seating' => 'Comfortably seats 5 adults']],
                    ['title' => 'Hatil Minimalist Wooden Bookshelf Display Rack', 'brand' => 'apex', 'sub' => 1, 'price' => 12500, 'sale' => 11000, 'stock' => 16, 'specs' => ['Wood' => 'Solid beech and red oak veneered engineered wood', 'Tiers' => '4 open display tiers for books and art objects', 'Structure' => 'Cross-braced back stability bars prevent wobbling', 'Finish' => 'Durable antique natural lacquer finish']],
                ]
            ],
            // 32. Bedroom Furniture
            [
                'cat_slug' => 'bedroom-furniture',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Hatil Solid Oak King Size Bed with Storage', 'brand' => 'apex', 'sub' => 0, 'price' => 48000, 'sale' => 43999, 'stock' => 8, 'specs' => ['Dimensions' => 'Standard King 6.5 x 6.0 feet mattress size', 'Timber' => 'Seasoned Canadian Red Oak with engineered wood sub-structure', 'Storage' => 'Dual side hydraulic lift-up underbed storage chambers', 'Headboard' => 'Cushioned leatherette padded headrest for reading in bed']],
                    ['title' => 'IKEA Malm High Bed Frame with 4 Storage Boxes', 'brand' => 'ikea', 'sub' => 0, 'price' => 38000, 'sale' => 34500, 'stock' => 12, 'specs' => ['Storage' => '4 smooth-gliding spacious drawers on casters underneath', 'Siderails' => 'Adjustable bed sides accommodate mattresses of different thicknesses', 'Base' => 'Luroe arched birch slats absorb body weight', 'Color' => 'Clean white stain oak veneer']],
                    ['title' => 'Hatil 4-Door Wardrobe with Full Dressing Mirror', 'brand' => 'apex', 'sub' => 1, 'price' => 54000, 'sale' => 49500, 'stock' => 6, 'specs' => ['Doors' => '4 hinged doors with center bevel-edged full dressing mirror', 'Layout' => 'Hanging rods for suits, saree hangers, and locked security drawer', 'Hardware' => 'High quality soft-closing metal hinges and magnetic catches', 'Lacquer' => 'Italian polyurethane lacquer finish in dark antique tone']],
                    ['title' => 'IKEA Hemnes 8-Drawer Dresser Chest White', 'brand' => 'ikea', 'sub' => 3, 'price' => 28500, 'sale' => 25999, 'stock' => 14, 'specs' => ['Material' => 'Solid sustainably sourced pine wood with white stain', 'Drawers' => '8 quiet smooth-running drawers with pull-out stops', 'Capacity' => 'Deep bottom drawers hold bulky blankets and sweaters', 'Handles' => 'Traditional black metal drop ring pulls']],
                    ['title' => 'Hatil Contemporary Bedside Nightstand 2-Drawer', 'brand' => 'apex', 'sub' => 2, 'price' => 6500, 'sale' => 5800, 'stock' => 25, 'specs' => ['Drawers' => '2 quiet ball-bearing slider drawers', 'Top' => 'Spacious top surface holds bedside lamp, phone, and books', 'Material' => 'Kiln-dried beechwood and engineered wood', 'Finish' => 'Scratch and stain resistant satin polish']],
                    ['title' => 'IKEA Songesand Bedside Table with Door White', 'brand' => 'ikea', 'sub' => 2, 'price' => 4500, 'sale' => 3999, 'stock' => 30, 'specs' => ['Reversible' => 'Door can be mounted to open from left or right', 'Outlet' => 'Open back slot enables hidden cable management for phone charging', 'Style' => 'Classic framed panel profile', 'Dimensions' => '42 x 40 x 55 cm']],
                    ['title' => 'Otobi 3-Door Wooden Wardrobe with Hanging Rod', 'brand' => 'walton', 'sub' => 1, 'price' => 29500, 'sale' => 26999, 'stock' => 10, 'specs' => ['Board' => 'High density moisture-resistant melamine faced board', 'Security' => 'Center door fitted with safety lock and two keys', 'Storage' => 'Multiple shelves, drawer, and long garment hanging rod', 'Finish' => 'Natural Teak woodgrain finish']],
                    ['title' => 'Hatil Modern Vanity Dressing Table with Stool', 'brand' => 'apex', 'sub' => 3, 'price' => 19500, 'sale' => 17500, 'stock' => 15, 'specs' => ['Mirror' => 'Frameless tall clear silver mirror', 'Cosmetics' => 'Multi-tier side shelves for perfumes and cosmetics jars', 'Stool' => 'Padded leatherette cushioned matching wooden stool included', 'Drawer' => 'Velvet-lined jewelry drawer with dividers']],
                    ['title' => 'Otobi Queen Size Hydraulic Lift Bed Frame', 'brand' => 'walton', 'sub' => 0, 'price' => 34000, 'sale' => 30999, 'stock' => 11, 'specs' => ['Mechanism' => 'German engineered pneumatic gas lift pistons lift mattress with ease', 'Underbed' => 'Dust-proof sealed underbed trunk holds seasonal quilts', 'Frame' => 'Heavy gauge powder-coated tubular steel frame inside', 'Headrest' => 'Contemporary two-tone contrasting wooden headboard']],
                    ['title' => 'IKEA Brimnes Wardrobe with 3 Doors Black', 'brand' => 'ikea', 'sub' => 1, 'price' => 22500, 'sale' => 19999, 'stock' => 14, 'specs' => ['Mirror' => 'Center door features full-length mirror saving room space', 'Interior' => 'Includes 1 clothes rail and 3 adjustable shelves', 'Safety' => 'Wall anchor fittings included to prevent tipping', 'Handles' => 'Minimalist recessed plastic handles']],
                ]
            ],
            // 33. Cookware & Tableware
            [
                'cat_slug' => 'cookware-tableware',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Tefal Ingenio Non-Stick 10-Piece Cookware Set', 'brand' => 'tefal', 'sub' => 0, 'price' => 18500, 'sale' => 16500, 'stock' => 20, 'specs' => ['Handle' => '100% Safe patented removable handle holds up to 10 kg', 'Thermo-Spot' => 'Iconic Thermo-Spot turns full red at optimal cooking heat', 'Coating' => 'Titanium mineral non-stick coating lasts 2x longer', 'Stackable' => 'Space-saving nesting design saves up to 50% cabinet space']],
                    ['title' => 'Tefal Hard Anodized Non-Stick Wok Pan 32cm', 'brand' => 'tefal', 'sub' => 0, 'price' => 5200, 'sale' => 4600, 'stock' => 35, 'specs' => ['Body' => 'Hard Anodized aluminum twice as hard as stainless steel', 'Lid' => 'Glass lid with steam vent and stainless rim', 'Coating' => 'PFOA, Lead, and Cadmium-free Titanium non-stick', 'Compatibility' => 'Suitable for all stovetops including Induction']],
                    ['title' => 'Victorinox Swiss Classic 5-Piece Kitchen Knife Block', 'brand' => 'bosch', 'sub' => 1, 'price' => 12500, 'sale' => 10999, 'stock' => 25, 'specs' => ['Blades' => 'High-carbon Swiss stainless steel laser-tested edge', 'Knives' => 'Chef knife, bread knife, carving, Santoku, and paring knife', 'Block' => 'Compact beechwood angular countertop knife block', 'Handles' => 'Ergonomic non-slip Fibrox dishwasher safe handles']],
                    ['title' => 'Corelle Livingware 16-Piece Ceramic Dinner Set', 'brand' => 'ikea', 'sub' => 2, 'price' => 11500, 'sale' => 9999, 'stock' => 30, 'specs' => ['Glass' => 'Vitrelle triple-layer glass technology resists chips and cracks', 'Profile' => 'Ultra-lightweight and thin stacks in half space of ceramics', 'Safe' => 'Microwave, dishwasher, and preheated oven safe up to 175°C', 'Service' => 'Service for 4: Dinner plates, salad plates, soup bowls, mugs']],
                    ['title' => 'Prestige Deluxe Alpha Stainless Steel Pressure Cooker 5L', 'brand' => 'singer', 'sub' => 0, 'price' => 5800, 'sale' => 5100, 'stock' => 40, 'specs' => ['Base' => 'Alpha induction base spreads heat quickly without hotspots', 'Steel' => 'Heavy gauge 304 food-grade surgical stainless steel', 'Safety' => 'Controlled Gasket Release System (CGRS) & pressure indicator', 'Handles' => 'Sturdy cool-touch Bakelite double screw handles']],
                    ['title' => 'Lodge Cast Iron Skillet 10.25 Inch Pre-Seasoned', 'brand' => 'tefal', 'sub' => 0, 'price' => 4800, 'sale' => 4200, 'stock' => 30, 'specs' => ['Material' => '100% Pure cast iron forged in South Pittsburg, USA', 'Seasoning' => 'Factory pre-seasoned with 100% natural vegetable oil', 'Cooking' => 'Incredible heat retention for searing steaks and baking cornbread', 'Use' => 'Oven, stove, grill, or over an open campfire']],
                    ['title' => 'Hydro Flask 32 oz Wide Mouth Insulated Bottle', 'brand' => 'nike', 'sub' => 3, 'price' => 4500, 'sale' => 3999, 'stock' => 50, 'specs' => ['Insulation' => 'TempShield double-wall vacuum keeps cold 24h, hot 12h', 'Steel' => 'Pro-grade 18/8 stainless steel ensures pure taste zero transfer', 'Finish' => 'Color Last powder coat is sweat-free and dishwasher safe', 'Cap' => 'Leakproof Flex Cap with flexible rubber strap']],
                    ['title' => 'Stanley Quencher H2.0 FlowState Tumbler 40oz', 'brand' => 'adidas', 'sub' => 3, 'price' => 4999, 'sale' => 4499, 'stock' => 45, 'specs' => ['Material' => '90% Recycled 18/8 stainless steel food-grade', 'Lid' => 'FlowState 3-position rotating cover with reusable straw', 'Car' => 'Tapered slim base fits into standard car cup holders', 'Handle' => 'Comfort-grip ergonomic side carry handle']],
                    ['title' => 'Cello Opalware Dazzle Tropical 33-Piece Dinner Set', 'brand' => 'ikea', 'sub' => 2, 'price' => 6500, 'sale' => 5800, 'stock' => 35, 'specs' => ['Material' => 'Bone ash free German technology thermal shock resistant opal glass', 'Hygienic' => '100% Non-porous surface does not absorb curry oils or bacteria', 'Plates' => '6 Dinner, 6 Quarter, 6 Soup bowls, 6 Veg bowls, 2 Serving bowls', 'Durability' => 'Microwave and dishwasher friendly']],
                    ['title' => 'Tefal Comfort 5-Piece Stainless Kitchen Utensil Set', 'brand' => 'tefal', 'sub' => 1, 'price' => 2450, 'sale' => 2100, 'stock' => 60, 'specs' => ['Items' => 'Soup ladle, slotted spoon, pasta fork, pancake spatula, skimmer', 'Material' => 'Reinforced polyamide nylon heat resistant up to 230°C', 'Safe' => 'Will not scratch delicate non-stick pan coatings', 'Hanging' => 'Integrated handle loop for easy wall rack hanging']],
                ]
            ],
            // 34. Home Decor & Lighting
            [
                'cat_slug' => 'home-decor-lighting',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Philips Hue Gradient Signe Floor Smart Lamp', 'brand' => 'philips', 'sub' => 1, 'price' => 32000, 'sale' => 29500, 'stock' => 10, 'specs' => ['Light' => 'Blends multiple colors simultaneously along a single standing light column', 'Lumens' => 'Up to 2550 lumens of brilliant diffused light', 'Design' => 'Slender minimalist architectural aluminum profile', 'Control' => 'Bluetooth app or connect to Hue Bridge for dynamic effects']],
                    ['title' => 'IKEA Fado Minimalist Globe Ambient Table Lamp', 'brand' => 'ikea', 'sub' => 1, 'price' => 2450, 'sale' => 2100, 'stock' => 40, 'specs' => ['Globe' => '25 cm white frosted mouth-blown glass globe', 'Light' => 'Emits soft, cozy glare-free diffuse mood illumination', 'Socket' => 'Standard E27 screw base compatible with LED smart bulbs', 'Cord' => '1.8-meter cord with inline on/off rocker switch']],
                    ['title' => 'Abstract Golden Foil Canvas Wall Art 3-Piece Set', 'brand' => 'ikea', 'sub' => 0, 'price' => 6500, 'sale' => 5800, 'stock' => 25, 'specs' => ['Canvas' => '300gsm waterproof heavyweight cotton canvas', 'Foil' => 'Hand-applied metallic gold leaf textured accents', 'Frames' => 'Floater black PS polymer frames ready to hang', 'Size' => 'Each panel 40 x 60 cm (Total 120 x 60 cm)']],
                    ['title' => 'Nordic Ceramic Ribbed Flower Plant Pot with Tray', 'brand' => 'ikea', 'sub' => 2, 'price' => 1850, 'sale' => 1550, 'stock' => 50, 'specs' => ['Craft' => 'Hand-thrown unglazed matte terracotta stoneware', 'Drainage' => 'Drainage hole at bottom with matching saucer plate', 'Texture' => 'Tactile vertical fluted ribbed aesthetic', 'Diameter' => '20 cm fits standard indoor houseplants']],
                    ['title' => 'Loom & Mill Luxury Velvet Blackout Curtains Pair', 'brand' => 'ikea', 'sub' => 3, 'price' => 5400, 'sale' => 4750, 'stock' => 30, 'specs' => ['Blackout' => 'Blocks 95% sunlight and UV rays with thermal insulation', 'Fabric' => 'Heavyweight 330gsm lush matte velvet drape', 'Hanging' => 'Silver rust-proof metal grommets slide smoothly', 'Dimensions' => 'Each panel 52 x 84 inches (Total 104 x 84 inches)']],
                    ['title' => 'IKEA Ribba Large Black Wall Poster Frame 50x70cm', 'brand' => 'ikea', 'sub' => 0, 'price' => 1950, 'sale' => 1650, 'stock' => 60, 'specs' => ['Mount' => 'Acid-free photo mat mount board included does not discolour photo', 'Protection' => 'Clear plastic front makes frame lighter and safer than glass', 'Profile' => 'Deep box edge frame can hang horizontally or vertically', 'Dimensions' => '50 x 70 cm picture size (or 40 x 50 cm with mount)']],
                    ['title' => 'Philips LED 10W Smart Wi-Fi Ceiling Downlight', 'brand' => 'philips', 'sub' => 1, 'price' => 1800, 'sale' => 1500, 'stock' => 45, 'specs' => ['Colors' => 'Tunable white from warm 2700K to daylight 6500K + 16M RGB', 'Wi-Fi' => 'Wiz connected: Controls directly via smartphone Wi-Fi', 'Cutout' => 'Fits standard 4-inch ceiling recessed cutout', 'Schedules' => 'Circadian rhythm rhythmically adjusts light throughout day']],
                    ['title' => 'Moroccan Geometric Pattern Handwoven Boho Area Rug', 'brand' => 'ikea', 'sub' => 0, 'price' => 8500, 'sale' => 7499, 'stock' => 18, 'specs' => ['Material' => '100% Natural organic cotton flatweave with braided tassels', 'Pattern' => 'Diamond trellis tribal Moroccan Scandinavian lines', 'Washable' => 'Machine washable cold cycle for effortless hygiene', 'Size' => '5 x 7 Feet (150 x 210 cm)']],
                    ['title' => 'Decozen Antique Brass Lotus Tealight Candle Holder', 'brand' => 'fossil', 'sub' => 0, 'price' => 2200, 'sale' => 1850, 'stock' => 35, 'specs' => ['Metal' => 'Handcrafted solid cast brass with antiqued patina', 'Petals' => 'Three tiers of blooming lotus petals cast romantic shadows', 'Base' => 'Heavy stable felt-padded base prevents table scratches', 'Use' => 'Fits standard tealight and votive candles']],
                    ['title' => 'IKEA Fejka Artificial Monstera Potted Plant 90cm', 'brand' => 'ikea', 'sub' => 2, 'price' => 3400, 'sale' => 2999, 'stock' => 30, 'specs' => ['Realism' => 'Lifelike botanical Swiss cheese plant monstera leaves', 'Care' => 'Zero maintenance: never needs water, pruning, or sunlight', 'Height' => '90 cm tall statement greenery for room corners', 'Pot' => 'Weighted black inner nursery pot for stability']],
                ]
            ],
            // 35. Bedding & Mattresses
            [
                'cat_slug' => 'bedding-mattresses',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Apex Sleep Rest Orthopedic Pocket Spring Mattress', 'brand' => 'apex', 'sub' => 0, 'price' => 32000, 'sale' => 28999, 'stock' => 12, 'specs' => ['Springs' => 'Individually wrapped pocket springs isolate motion transfer', 'Foam' => 'High-density memory foam top layer for spinal alignment', 'Fabric' => 'Knitted anti-microbial breathable Jacquard fabric', 'Thickness' => '8-inch luxury profile with 10-year warranty']],
                    ['title' => 'Bombay Dyeing 100% Cotton King Bedsheet Set', 'brand' => 'ikea', 'sub' => 1, 'price' => 3200, 'sale' => 2750, 'stock' => 50, 'specs' => ['Fabric' => '100% Combed pure cotton with soft sateen weave', 'Thread Count' => '300 Thread Count smooth breathable feel', 'Contents' => '1 King bedsheet (274 x 274 cm) + 2 matching pillow covers', 'Colorfast' => 'Reactive dyed guarantees zero fading after repeated washes']],
                    ['title' => 'Spaces All-Season Microfiber Comforter Duvet', 'brand' => 'ikea', 'sub' => 2, 'price' => 4500, 'sale' => 3999, 'stock' => 35, 'specs' => ['Fill' => '300 GSM hypoallergenic down-alternative microfiber fill', 'Stitching' => 'Box-stitch quilting keeps filling evenly dispersed', 'Warmth' => 'All-season warmth keeps comfortable in winter and AC summer', 'Loops' => '4 corner tabs to anchor securely inside duvet covers']],
                    ['title' => 'SleepyCat Ergonomic Memory Foam Contour Pillow', 'brand' => 'apex', 'sub' => 3, 'price' => 2800, 'sale' => 2450, 'stock' => 40, 'specs' => ['Shape' => 'Ergonomic dual-height contour cradles neck and cervical spine', 'Cooling' => 'Infused with cooling gel beads to dissipate head heat', 'Cover' => 'Removable washable bamboo fiber anti-allergy zippered cover', 'Certification' => 'CertiPUR-US certified safe non-toxic foam']],
                    ['title' => 'Hatil Dual Comfort Reversible Orthopedic Mattress', 'brand' => 'apex', 'sub' => 0, 'price' => 24500, 'sale' => 22000, 'stock' => 15, 'specs' => ['Dual Sided' => 'Medium-firm side for spinal support and soft side for plush feel', 'Core' => 'Rebonded orthopedic high-density foam core', 'Cover' => 'Quilted Belgian damask fabric with zipper', 'Size' => 'King Size (78 x 72 x 6 inches)']],
                    ['title' => 'Trident Pure Cotton 400TC Deep Pocket Fitted Sheet', 'brand' => 'ikea', 'sub' => 1, 'price' => 2950, 'sale' => 2550, 'stock' => 45, 'specs' => ['Fit' => 'All-around heavy-duty elastic grips mattresses up to 16" deep', 'Weave' => 'Silky smooth 400 TC long-staple cotton sateen', 'Color' => 'Hotel crisp solid white with subtle sheen', 'Pillows' => 'Includes 2 matching envelope-closure pillowcases']],
                    ['title' => 'Spaces Hydro-Fil Waterproof Mattress Protector', 'brand' => 'ikea', 'sub' => 0, 'price' => 2200, 'sale' => 1899, 'stock' => 50, 'specs' => ['Barrier' => '100% Waterproof TPU breathable membrane protects from spills', 'Surface' => 'Soft terry cotton surface does not make crinkling plastic noises', 'Skirt' => 'Knitted elastic skirt wraps around bed like a fitted sheet', 'Care' => 'Machine washable and tumble dry low']],
                    ['title' => 'Bombay Dyeing Soft Coral Fleece Blanket Floral', 'brand' => 'ikea', 'sub' => 2, 'price' => 2400, 'sale' => 2100, 'stock' => 40, 'specs' => ['Material' => 'Super-soft high-pile microfiber coral fleece 350 GSM', 'Feel' => 'Plush velvet touch with heat-trapping lightweight warmth', 'Print' => 'Vibrant traditional botanical floral embossed pattern', 'Size' => 'Double bed size (220 x 240 cm)']],
                    ['title' => 'Bianca Luxury Microfiber Plush Sleeping Pillow Pair', 'brand' => 'ikea', 'sub' => 3, 'price' => 2100, 'sale' => 1799, 'stock' => 60, 'specs' => ['Pack' => 'Set of 2 luxury hotel pillows (45 x 68 cm)', 'Fill' => 'Siliconized micro poly-fiber stays fluffy and does not flatten', 'Shell' => '100% Breathable cotton casing with double-stitched piped edges', 'Support' => 'Medium-soft support for side and back sleepers']],
                    ['title' => 'IKEA Dvala Pure Cotton Duvet Cover Set Grey', 'brand' => 'ikea', 'sub' => 1, 'price' => 3600, 'sale' => 3100, 'stock' => 38, 'specs' => ['Fabric' => '100% Sustainably grown cotton gets softer with every wash', 'Closure' => 'Concealed snap buttons keep duvet neatly in place', 'Set' => '1 King duvet cover (240 x 220 cm) + 2 pillowcases', 'Yarn' => 'Fine yarn densely woven for long-lasting durability']],
                ]
            ],
            // 36. Skincare & Treatments
            [
                'cat_slug' => 'skincare-treatments',
                'has_variants' => false,
                'items' => [
                    ['title' => 'The Ordinary Niacinamide 10% + Zinc 1% 60ml', 'brand' => 'the-ordinary', 'sub' => 1, 'price' => 1850, 'sale' => 1650, 'stock' => 60, 'specs' => ['Formula' => 'High-strength 10% vitamin and mineral blemish serum', 'Benefits' => 'Reduces appearance of skin blemishes, congestion, and sebum', 'Skin Type' => 'Oily, combination, and acne-prone skin', 'Size' => 'Jumbo 60ml dropper bottle']],
                    ['title' => 'CeraVe Hydrating Facial Cleanser 473ml', 'brand' => 'cerave', 'sub' => 0, 'price' => 2200, 'sale' => 1950, 'stock' => 50, 'specs' => ['Ceramides' => 'Formulated with 3 essential ceramides (1, 3, 6-II)', 'Technology' => 'MVE Delivery technology controlled release for 24h hydration', 'Hyaluronic' => 'Hyaluronic acid retains skin\'s natural moisture', 'Certification' => 'Non-comedogenic, non-drying, accepted by National Eczema Assoc']],
                    ['title' => 'CeraVe Moisturizing Cream for Dry Skin 454g Tub', 'brand' => 'cerave', 'sub' => 3, 'price' => 2600, 'sale' => 2350, 'stock' => 45, 'specs' => ['Texture' => 'Rich, velvety non-greasy fast absorbing barrier cream', 'Action' => 'Restores protective skin barrier on face and body', 'Hydration' => 'Clinically proven 24-hour hydration lock', 'Fragrance' => '100% Fragrance-free and hypoallergenic']],
                    ['title' => 'The Ordinary Hyaluronic Acid 2% + B5 Hydration', 'brand' => 'the-ordinary', 'sub' => 1, 'price' => 1750, 'sale' => 1550, 'stock' => 55, 'specs' => ['Molecules' => 'Combines low, medium and high-molecular weight HA + crosspolymer', 'Vitamin B5' => 'Pro-vitamin B5 enhances surface hydration', 'Result' => 'Plumps skin and smooths appearance of fine lines', 'Usage' => 'Apply few drops to clean face AM and PM before creams']],
                    ['title' => 'Beauty of Joseon Relief Sun Rice + Probiotics SPF50+', 'brand' => 'the-ordinary', 'sub' => 2, 'price' => 1950, 'sale' => 1750, 'stock' => 40, 'specs' => ['Protection' => 'SPF 50+ PA++++ broad spectrum chemical sunscreen', 'Extract' => '30% Rice extract and grain fermented extracts nourish skin', 'Finish' => 'Moist creamy finish zero white cast zero stickiness', 'Safety' => 'Certified gentle for sensitive skin, reef safe']],
                    ['title' => 'The Ordinary Retinol 0.5% in Squalane 30ml', 'brand' => 'the-ordinary', 'sub' => 1, 'price' => 1900, 'sale' => 1699, 'stock' => 35, 'specs' => ['Retinol' => '0.5% Pure active retinol targets signs of aging', 'Base' => 'Formulated in plant-derived squalane to prevent irritation', 'Targets' => 'Fine lines, photo damage, uneven tone, texture', 'Application' => 'Apply small amount in PM as part of nighttime routine']],
                    ['title' => 'Cosrx Advanced Snail 96 Mucin Power Essence 100ml', 'brand' => 'the-ordinary', 'sub' => 3, 'price' => 1850, 'sale' => 1600, 'stock' => 45, 'specs' => ['Snail Mucin' => '96.3% Snail secretion filtrate repairs skin barrier', 'Benefits' => 'Intense hydration, fades dark acne spots, smooths texture', 'Texture' => 'Lightweight viscous essence absorbs quickly', 'Cruelty-Free' => '100% Cruelty-free ethical harvesting']],
                    ['title' => 'CeraVe Foaming Facial Cleanser for Oily Skin 473ml', 'brand' => 'cerave', 'sub' => 0, 'price' => 2200, 'sale' => 1950, 'stock' => 48, 'specs' => ['Foam' => 'Gel cleanser transforms into gentle foamy lather', 'Ingredients' => 'Ceramides, Niacinamide, and Hyaluronic acid', 'Oil Control' => 'Removes excess oil and makeup without stripping moisture barrier', 'Skin Type' => 'Normal to oily sensitive skin']],
                    ['title' => 'Neutrogena Hydro Boost Water Gel Moisturizer 50g', 'brand' => 'cerave', 'sub' => 3, 'price' => 1650, 'sale' => 1450, 'stock' => 50, 'specs' => ['Base' => 'Oil-free water gel instantly quenches dehydrated skin', 'Complex' => 'Purified Hyaluronic acid acts like sponge for dry skin cells', 'Absorption' => 'Absorbs instantly with zero greasy residue', 'Non-Comedogenic' => 'Won\'t clog pores under makeup']],
                    ['title' => 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid', 'brand' => 'the-ordinary', 'sub' => 2, 'price' => 2850, 'sale' => 2550, 'stock' => 30, 'specs' => ['Filter' => 'Mexoryl 400 filter protects against ultra-long UVA rays', 'Texture' => 'Ultra-fluid invisible lightweight finish', 'Resistance' => 'Very water, sweat, and sand resistant', 'Eyes' => 'Anti-eye stinging formula tested under ophthalmological control']],
                ]
            ],
            // 37. Hair Care & Styling
            [
                'cat_slug' => 'hair-care-styling',
                'has_variants' => false,
                'items' => [
                    ['title' => 'L\'Oreal Paris Total Repair 5 Repairing Shampoo 650ml', 'brand' => 'loreal-paris', 'sub' => 0, 'price' => 950, 'sale' => 820, 'stock' => 60, 'specs' => ['Formulation' => 'Infused with Ceramide-Cement and Pro-Keratin', 'Targets' => 'Fights 5 signs of damage: fall, dryness, roughness, dullness, splits', 'Size' => 'Economy 650ml pump dispenser bottle', 'Hair Type' => 'Damaged, chemically treated and dry hair']],
                    ['title' => 'Dyson Supersonic Ionic Hair Dryer Nickel Copper', 'brand' => 'dyson', 'sub' => 3, 'price' => 54000, 'sale' => 49999, 'stock' => 10, 'specs' => ['Motor' => 'V9 digital motor spins up to 110,000 RPM with Air Multiplier', 'Heat Control' => 'Intelligent heat control measures air temperature 40x per second', 'Attachments' => '5 styling magnetic attachments including Flyaway attachment', 'Acoustics' => 'Tuned to produce an inaudible frequency for quiet operation']],
                    ['title' => 'L\'Oreal Professionnel Serie Expert Absolut Repair Mask', 'brand' => 'loreal-paris', 'sub' => 1, 'price' => 2450, 'sale' => 2199, 'stock' => 35, 'specs' => ['Ingredients' => 'Gold Quinoa protein and wheat protein complex', 'Resurfacing' => '77% Less surface damage and 7x shinier hair', 'Texture' => 'Buttery rich golden balm consistency', 'Size' => '250ml professional hair spa salon tub']],
                    ['title' => 'Moroccanoil Treatment Original Hair Oil 100ml', 'brand' => 'loreal-paris', 'sub' => 2, 'price' => 4800, 'sale' => 4350, 'stock' => 25, 'specs' => ['Infusion' => 'Infused with antioxidant-rich Argan oil and linseed extract', 'Benefits' => 'Speeds up blowout time, detangles, deters frizz, boosts shine', 'Non-Greasy' => 'Instant absorption without greasy residue', 'Scent' => 'Signature iconic Mediterranean spicy amber scent']],
                    ['title' => 'Head & Shoulders Cool Menthol Anti-Dandruff 650ml', 'brand' => 'dove', 'sub' => 0, 'price' => 920, 'sale' => 799, 'stock' => 70, 'specs' => ['Active' => 'Clinically proven Zinc Pyrithione formula eliminates 100% visible flakes', 'Menthol' => 'Natural cooling menthol tingles scalp and soothes itch', 'Scalp' => 'pH balanced for everyday use even on color-treated hair', 'Volume' => '650ml mega pump bottle']],
                    ['title' => 'L\'Oreal Paris Extraordinary Oil Hair Serum 100ml', 'brand' => 'loreal-paris', 'sub' => 2, 'price' => 1250, 'sale' => 1050, 'stock' => 50, 'specs' => ['Botanicals' => 'Blend of 6 rare flower oils (Lotus, Chamomile, Tiare, Rose, Flax, Sunflower)', 'Protection' => 'Heat protectant up to 230°C before styling tools', 'Finish' => 'Glossy mirror shine and weightless softness', 'Versatility' => 'Use before shampoo, before blow-dry, or as finishing touch']],
                    ['title' => 'Philips Kerashine Titanium Hair Straightener HP8316', 'brand' => 'philips', 'sub' => 3, 'price' => 3800, 'sale' => 3350, 'stock' => 30, 'specs' => ['Plates' => 'Extra-wide 47mm keratin-infused ceramic titanium plates', 'Ionic' => 'Ionic conditioning gives instant frizz-free shiny hair', 'Heat' => 'Professional styling temperature 210°C ready in 60s', 'Cord' => '1.8m swivel power cord prevents tangles']],
                    ['title' => 'Tresemme Keratin Smooth Deep Smoothing Conditioner', 'brand' => 'dove', 'sub' => 1, 'price' => 750, 'sale' => 640, 'stock' => 55, 'specs' => ['Keratin' => 'Hydrolyzed keratin and marula oil nourishment', 'Anti-Frizz' => 'Controls frizz for up to 72 hours even in high humidity', 'Detangle' => 'Detangles knots effortlessly leaving hair silky smooth', 'Volume' => '390ml squeeze bottle']],
                    ['title' => 'Mamaearth Rosemary Hair Growth Oil with Methi 250ml', 'brand' => 'dove', 'sub' => 2, 'price' => 950, 'sale' => 820, 'stock' => 45, 'specs' => ['Ingredients' => 'Pure Rosemary oil, Methi (Fenugreek), and Castor oil', 'Action' => 'Stimulates scalp micro-circulation and revitalizes hair follicles', 'Toxins' => 'Made Safe Certified: Free from parabens, mineral oil, silicones', 'Applicator' => 'Comes with deep root comb applicator']],
                    ['title' => 'Philips 1200W Compact Foldable Hair Dryer HP8108', 'brand' => 'philips', 'sub' => 3, 'price' => 1850, 'sale' => 1599, 'stock' => 40, 'specs' => ['Power' => '1200W gentle drying for beautiful everyday results', 'Settings' => '2 flexible speed and heat combinations', 'Foldable' => 'Foldable ergonomic handle for compact travel packing', 'Nozzle' => 'Narrow concentrator nozzle for focused airflow']],
                ]
            ],
            // 38. Fragrances & Perfumes
            [
                'cat_slug' => 'fragrances-perfumes',
                'has_variants' => true,
                'variant_type' => 'perfume',
                'items' => [
                    ['title' => 'Dior Sauvage Eau de Parfum 100ml for Men', 'brand' => 'dior', 'sub' => 0, 'price' => 16500, 'sale' => 15200, 'stock' => 20, 'specs' => ['Concentration' => 'Eau de Parfum (EDP) long lasting sillage', 'Top Notes' => 'Calabrian Bergamot and Sichuan Pepper', 'Heart Notes' => 'Star Anise, Nutmeg, Lavender', 'Base Notes' => 'Papua New Guinean Vanilla Absolute and Ambroxan']],
                    ['title' => 'Bleu de Chanel Eau de Parfum 100ml Vaporisateur', 'brand' => 'chanel', 'sub' => 0, 'price' => 18500, 'sale' => 17200, 'stock' => 15, 'specs' => ['Family' => 'Aromatic woody fragrance with captivating trail', 'Top Notes' => 'Grapefruit, Lemon, Mint, Pink Pepper', 'Heart' => 'Ginger, Nutmeg, Jasmine, Iso E Super', 'Base' => 'Incense, Vetiver, Cedar, Sandalwood, Patchouli, White Musk']],
                    ['title' => 'Tom Ford Oud Wood Eau de Parfum 50ml Unisex', 'brand' => 'dior', 'sub' => 2, 'price' => 24500, 'sale' => 22500, 'stock' => 10, 'specs' => ['Class' => 'Tom Ford Private Blend rare and artisanal collection', 'Notes' => 'Rare Oud wood, Rosewood, Cardamom, Sandalwood, Vetiver, Tonka bean, Amber', 'Character' => 'Smoky, exotic, opulent, and distinctively sensual', 'Country' => 'Made in USA']],
                    ['title' => 'Yves Saint Laurent Black Opium EDP 90ml Women', 'brand' => 'chanel', 'sub' => 1, 'price' => 15500, 'sale' => 14200, 'stock' => 18, 'specs' => ['Category' => 'Addictive gourmand floral fragrance', 'Top Notes' => 'Pear, Pink Pepper, Orange Blossom', 'Heart Notes' => 'Adrenaline-rich Black Coffee Accord and Jasmine', 'Base Notes' => 'Vanilla, Patchouli, Cedarwood']],
                    ['title' => 'Giorgio Armani Acqua Di Gio Profondo EDP 75ml', 'brand' => 'dior', 'sub' => 0, 'price' => 13500, 'sale' => 12400, 'stock' => 22, 'specs' => ['Style' => 'Aquatic fougère taking inspiration from the deep sea', 'Top Notes' => 'Marine notes, Aquozone, Green Mandarin, Bergamot', 'Heart' => 'Rosemary, Lavender, Cypress, Mastic', 'Base' => 'Mineral Amber, Patchouli, Musk']],
                    ['title' => 'Creed Aventus Millesime Eau de Parfum 100ml', 'brand' => 'chanel', 'sub' => 0, 'price' => 38000, 'sale' => 35000, 'stock' => 8, 'specs' => ['Heritage' => 'Celebrates strength, power, and success since 2010', 'Top Notes' => 'Bergamot, Blackcurrant leaves, Apple, Pineapple', 'Heart Notes' => 'Pinkberries, Birch, Patchouli, Jasmine', 'Base Notes' => 'Musk, Oakmoss, Ambergris, Vanilla']],
                    ['title' => 'Versace Eros Flame Eau de Parfum 100ml', 'brand' => 'dior', 'sub' => 0, 'price' => 11500, 'sale' => 10200, 'stock' => 25, 'specs' => ['Theme' => 'Passionate, strong, self-confident fiery masculinity', 'Top Notes' => 'Italian chinotto, Lemon, Mandarin, Black Pepper', 'Heart' => 'Rosemary, Pepperwood, Geranium, Rose', 'Base' => 'Texas Cedar, Patchouli, Haitian Vetiver, Tonka Bean']],
                    ['title' => 'Carolina Herrera Good Girl Eau de Parfum 80ml', 'brand' => 'chanel', 'sub' => 1, 'price' => 14500, 'sale' => 13200, 'stock' => 20, 'specs' => ['Flacon' => 'Iconic black stiletto high heel bottle with golden heel', 'Duality' => 'Contrasts sweet tuberose and jasmine with roasted cocoa & tonka', 'Top Notes' => 'Almond, Coffee, Bergamot, Lemon', 'Mood' => 'Daring, sensual, and ultra-feminine evening signature']],
                    ['title' => 'Victoria\'s Secret Pure Seduction Fragrance Mist 250ml', 'brand' => 'dove', 'sub' => 3, 'price' => 2200, 'sale' => 1899, 'stock' => 50, 'specs' => ['Type' => 'Refreshing all-over body fragrance mist spray', 'Fragrance' => 'Fruity floral blend of Juiced Plum and Crushed Freesia', 'Hydration' => 'Infused with conditioning Aloe Vera and calming chamomile', 'Size' => '250ml / 8.4 fl oz full size spray bottle']],
                    ['title' => 'Rasasi Hawas for Men Eau de Parfum 100ml', 'brand' => 'dior', 'sub' => 0, 'price' => 5800, 'sale' => 5200, 'stock' => 30, 'specs' => ['Vibe' => 'Fresh aquatic cinnamon blend with magnetic longevity', 'Top Notes' => 'Apple, Bergamot, Lemon, Cinnamon', 'Heart Notes' => 'Orange Blossom, Cardamom, Plum, Watery notes', 'Base Notes' => 'Ambergris, Musk, Patchouli, Driftwood']],
                ]
            ],
            // 39. Men's Grooming & Shaving
            [
                'cat_slug' => 'mens-grooming-shaving',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Braun Series 9 Pro Electric Foil Shaver 9465cc', 'brand' => 'braun', 'sub' => 1, 'price' => 38000, 'sale' => 34999, 'stock' => 10, 'specs' => ['Head' => 'ProLift trimmer cuts tough 1, 3, or 7-day beards gently', 'Sonic' => 'SyncroSonic technology 40,000 sonic cuts per minute', 'Center' => '5-in-1 SmartCare Center cleans, lubricates, dries & charges', 'Battery' => 'Li-ion battery delivers 60 minutes running time']],
                    ['title' => 'Philips Norelco Multigroom Series 7000 23-Piece', 'brand' => 'philips', 'sub' => 0, 'price' => 7800, 'sale' => 6999, 'stock' => 35, 'specs' => ['Blades' => 'DualCut self-sharpening tempered steel blades never dull', 'Attachments' => '23 pieces for face, head, body, and pubic hair styling', 'Motor' => 'Full metal motor reinforced with tempered steel drive train', 'Runtime' => 'Up to 5 hours runtime from high-capacity rechargeable battery']],
                    ['title' => 'Gillette Labs Razor with Exfoliating Bar Kit', 'brand' => 'gillette', 'sub' => 3, 'price' => 3400, 'sale' => 2999, 'stock' => 45, 'specs' => ['Bar' => 'Built-in exfoliating bar clears dirt and debris before blades pass', 'FlexDisc' => '2D FlexDisc technology contours to face curves', 'Blades' => 'Gillette\'s sharpest 5-blade cartridge system', 'Stand' => 'Heavy magnetic metal dock keeps razor standing dry']],
                    ['title' => 'Panasonic Arc5 Wet & Dry Electric Shaver ES-LV65', 'brand' => 'panasonic', 'sub' => 1, 'price' => 18500, 'sale' => 16999, 'stock' => 15, 'specs' => ['System' => '5-Blade ultra-thin Nanotech cutting system at 30-degree angle', 'Linear Motor' => '14,000 cuts per minute (70,000 cross-cutting actions)', 'Sensor' => 'Active shaving sensor automatically detects beard density', 'Pivoting' => 'Multi-Flex pivoting head traces jawline and neck']],
                    ['title' => 'Philips OneBlade Face + Body Hybrid Trimmer QP2824', 'brand' => 'philips', 'sub' => 0, 'price' => 4200, 'sale' => 3750, 'stock' => 40, 'specs' => ['Technology' => 'Fast moving cutter (12000x per minute) shaves without razor burns', 'Guard' => 'Dual-sided blade with click-on skin guard for body', 'Water' => '100% Waterproof for wet/dry use in the shower', 'Battery' => 'NimH rechargeable battery with USB-A charging']],
                    ['title' => 'Braun All-in-One Styling Kit Series 5 9-in-1', 'brand' => 'braun', 'sub' => 2, 'price' => 5400, 'sale' => 4800, 'stock' => 30, 'specs' => ['Blades' => 'Ultra-sharp lifetime blade trims evenly from root to tip', 'Combs' => 'Precision combs for 0.5mm to 21mm beard and hair lengths', 'Washable' => '100% Waterproof head and combs rinse under running tap', 'Power' => 'Powerful Li-Ion battery with 100 minutes cordless trim']],
                    ['title' => 'Gillette Fusion5 ProGlide Power Men\'s Razor Blades (4 Pack)', 'brand' => 'gillette', 'sub' => 3, 'price' => 1950, 'sale' => 1750, 'stock' => 60, 'specs' => ['Friction' => '5 anti-friction blades for a shave you barely feel', 'Precision' => 'Precision trimmer on the back for hard-to-reach areas and edges', 'Lubrastrip' => 'Enhanced Lubrastrip with more lubricants fades when ready to swap', 'Longevity' => '1 blade refill lasts up to one full month of shaves']],
                    ['title' => 'Proraso Refreshing Eucalyptus Shaving Cream 150ml', 'brand' => 'nivea', 'sub' => 3, 'price' => 1250, 'sale' => 1050, 'stock' => 50, 'specs' => ['Heritage' => 'Authentic Italian barbershop classic formula since 1948', 'Ingredients' => 'Eucalyptus oil purifies and Menthol cools skin', 'Lather' => 'Hot-soap process creates concentrated rich cushioning lather', 'Purity' => 'No parabens, silicones, mineral oils, or artificial colors']],
                    ['title' => 'Nivea Men Sensitive Post Shave Balm 100ml', 'brand' => 'nivea', 'sub' => 3, 'price' => 850, 'sale' => 720, 'stock' => 65, 'specs' => ['Soothe' => 'Instantly relieves 5 signs of shave irritation: burning, redness, dryness, tightness, itch', 'Alcohol-Free' => '0% Ethyl alcohol formula does not sting freshly shaved skin', 'Enriched' => 'Chamomile and Vitamin E soothe and hydrate skin barrier', 'Dermatology' => 'Dermatologically approved for sensitive skin']],
                    ['title' => 'Gillette Series Sensitive Shave Gel with Aloe 200ml', 'brand' => 'gillette', 'sub' => 3, 'price' => 550, 'sale' => 470, 'stock' => 75, 'specs' => ['Formula' => 'Enriched with soothing Aloe Vera extract', 'Glide' => 'Polymer-enriched lubrication formula minimizes razor drag', 'Protection' => '3x Action: Hydrates, protects, and refreshes skin', 'Rust-Proof' => 'Clean rust-free dispenser can bottom']],
                ]
            ],
            // 40. Bath & Body Care
            [
                'cat_slug' => 'bath-body-care',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Dove Deeply Nourishing Body Wash 1000ml Refill', 'brand' => 'dove', 'sub' => 0, 'price' => 1150, 'sale' => 999, 'stock' => 55, 'specs' => ['MicroMoisture' => '24-hour renewing MicroMoisture technology', 'Microbiome' => 'Plant-based moisturizers nourish skin\'s protective microbiome', 'Clean' => '0% Sulfate SLES gentle cleanser formula', 'Economy' => 'Jumbo 1-Liter family pump bottle']],
                    ['title' => 'Nivea Rich Nourishing Deep Moisture Body Milk 400ml', 'brand' => 'nivea', 'sub' => 1, 'price' => 850, 'sale' => 740, 'stock' => 60, 'specs' => ['Serum' => 'Nivea Deep Moisture Serum locks in moisture for 48 hours', 'Almond' => 'Natural almond oil softens rough flaky skin', 'Comfort' => 'Noticeably reduces skin roughness after just 1 application', 'Skin' => 'Specially formulated for very dry skin']],
                    ['title' => 'The Body Shop British Rose Exfoliating Scrub 250ml', 'brand' => 'dove', 'sub' => 2, 'price' => 2450, 'sale' => 2199, 'stock' => 30, 'specs' => ['Texture' => 'Gel body scrub with real rose petals and walnut shell powder', 'Exfoliation' => 'Melts onto skin to gently buff away dead dull surface cells', 'Scent' => 'Fresh floral scent of handpicked English roses', 'Origin' => 'Enriched with community fair trade organic aloe vera']],
                    ['title' => 'Dettol Original Liquid Handwash 900ml Refill Pouch', 'brand' => 'dove', 'sub' => 3, 'price' => 480, 'sale' => 420, 'stock' => 80, 'specs' => ['Germ Protection' => 'Protects against 100 illness-causing germs and bacteria', 'pH-Balanced' => 'Dermatologically tested gentle on hands with added glycerin', 'Fragrance' => 'Iconic Pine fresh Dettol hygiene fragrance', 'Pack' => 'Environmentally friendly eco-refill pouch']],
                    ['title' => 'Cetaphil Ultra Gentle Fragrance-Free Body Wash 500ml', 'brand' => 'cerave', 'sub' => 0, 'price' => 1950, 'sale' => 1750, 'stock' => 40, 'specs' => ['Hydration' => 'Nourishing Marigold flower extract, Aloe vera, and Vitamin B5', 'Barrier' => 'Cleanses without stripping skin of essential natural moisture', 'Hypoallergenic' => 'Dermatologist tested safe for sensitive, eczema-prone skin', 'Formula' => 'Sulfate-free, paraben-free, and fragrance-free']],
                    ['title' => 'Dove White Beauty Bathing Bar Soap 100g (Pack of 4)', 'brand' => 'dove', 'sub' => 3, 'price' => 520, 'sale' => 460, 'stock' => 90, 'specs' => ['Moisturizer' => 'Contains 1/4 moisturizing cream to hydrate while washing', 'Gentle' => 'Milder than ordinary soaps; does not dry out skin', 'Dermatology' => '#1 Dermatologist recommended cleansing bar', 'Form' => 'Classic ergonomic curved white beauty bar']],
                    ['title' => 'Tree Hut Shea Sugar Scrub Moroccan Rose 510g', 'brand' => 'the-ordinary', 'sub' => 2, 'price' => 2200, 'sale' => 1950, 'stock' => 45, 'specs' => ['Sugar' => 'Real natural granulated sugar gently exfoliates and increases circulation', 'Shea Butter' => '100% Pure natural organic Shea butter deeply moisturizes', 'Oils' => '6-Oil blend: Evening Primrose, Avocado, Macadamia, Sweet Almond, Safflower, Orange', 'Paraben-Free' => 'Zero parabens, sulfates, formaldehyde donors']],
                    ['title' => 'Palmolive Naturals Ultra Moist Orchid Shower Milk 750ml', 'brand' => 'dove', 'sub' => 0, 'price' => 880, 'sale' => 760, 'stock' => 50, 'specs' => ['Extracts' => '100% Natural exotic orchid flower and moisturizing milk protein', 'Texture' => 'Rich creamy shower milk foams into luxurious velvet lather', 'pH' => 'Dermatologically tested pH balanced 5.5 body wash', 'Fragrance' => 'Sensual floral orchid fragrance lasts after bath']],
                    ['title' => 'Nivea Cocoa Butter Body Cream with Serum 400ml', 'brand' => 'nivea', 'sub' => 1, 'price' => 920, 'sale' => 810, 'stock' => 55, 'specs' => ['Indulgence' => 'Infused with natural Cocoa butter and nourishing Vitamin E', 'Glow' => 'Provides 48-hour moisture and radiant healthy skin glow', 'Scent' => 'Delicious warm cocoa scent envelops senses', 'Absorption' => 'Melts softly into skin without sticky film']],
                    ['title' => 'Dettol ProFresh Cool Body Wash with Menthol 500ml', 'brand' => 'dove', 'sub' => 0, 'price' => 650, 'sale' => 560, 'stock' => 60, 'specs' => ['Cooling' => 'Crisp menthol formula instantly drops skin temperature by 5°C', 'Protection' => '100% Better germ protection against summer body odor', 'Lather' => 'Foams instantly into refreshing energizing bubbles', 'Dispenser' => 'Easy-to-use flip cap shower bottle']],
                ]
            ],
        ];
    }
}
