<?php

namespace Database\Seeders;

class ProductCatalogDefinitionPart1
{
    public static function get(): array
    {
        return [
            // 1. Smartphones & Mobile Tech
            [
                'cat_slug' => 'smartphones-mobile-tech',
                'has_variants' => true,
                'variant_type' => 'phone',
                'items' => [
                    ['title' => 'Apple iPhone 15 Pro Max 256GB', 'brand' => 'apple', 'sub' => 0, 'price' => 179999, 'sale' => 169999, 'stock' => 24, 'specs' => ['Display' => '6.7" Super Retina XDR OLED 120Hz', 'Chip' => 'A17 Pro', 'Camera' => '48MP Triple OIS', 'Battery' => '4422 mAh']],
                    ['title' => 'Samsung Galaxy S24 Ultra 5G 256GB', 'brand' => 'samsung', 'sub' => 0, 'price' => 164999, 'sale' => 154999, 'stock' => 18, 'specs' => ['Display' => '6.8" Dynamic AMOLED 2X 120Hz', 'Chip' => 'Snapdragon 8 Gen 3', 'Camera' => '200MP Quad OIS', 'Battery' => '5000 mAh']],
                    ['title' => 'Google Pixel 8 Pro 128GB', 'brand' => 'google', 'sub' => 0, 'price' => 112000, 'sale' => 104999, 'stock' => 15, 'specs' => ['Display' => '6.7" LTPO OLED 120Hz', 'Chip' => 'Google Tensor G3', 'Camera' => '50MP Triple AI', 'Battery' => '5050 mAh']],
                    ['title' => 'OnePlus 12 5G 16GB/512GB', 'brand' => 'oneplus', 'sub' => 0, 'price' => 96999, 'sale' => 89999, 'stock' => 20, 'specs' => ['Display' => '6.82" 2K 120Hz AMOLED', 'Chip' => 'Snapdragon 8 Gen 3', 'Camera' => '50MP Hasselblad', 'Battery' => '5400 mAh 100W']],
                    ['title' => 'Xiaomi 14 Pro Leica 512GB', 'brand' => 'xiaomi', 'sub' => 0, 'price' => 99999, 'sale' => 92999, 'stock' => 14, 'specs' => ['Display' => '6.73" 2K AMOLED 120Hz', 'Chip' => 'Snapdragon 8 Gen 3', 'Camera' => '50MP Leica Triple', 'Battery' => '4880 mAh 120W']],
                    ['title' => 'Samsung Galaxy A55 5G 8GB/256GB', 'brand' => 'samsung', 'sub' => 1, 'price' => 54999, 'sale' => 51999, 'stock' => 25, 'specs' => ['Display' => '6.6" Super AMOLED 120Hz', 'Chip' => 'Exynos 1480', 'Camera' => '50MP OIS Triple', 'Battery' => '5000 mAh 25W']],
                    ['title' => 'Xiaomi Redmi Note 13 Pro+ 5G', 'brand' => 'xiaomi', 'sub' => 1, 'price' => 45999, 'sale' => 42999, 'stock' => 30, 'specs' => ['Display' => '6.67" 1.5K Curved AMOLED', 'Chip' => 'Dimensity 7200-Ultra', 'Camera' => '200MP OIS', 'Battery' => '5000 mAh 120W']],
                    ['title' => 'Xiaomi Redmi 13C 6GB/128GB', 'brand' => 'xiaomi', 'sub' => 2, 'price' => 15499, 'sale' => 14499, 'stock' => 40, 'specs' => ['Display' => '6.74" 90Hz Dot Drop', 'Chip' => 'Helio G85', 'Camera' => '50MP AI Dual', 'Battery' => '5000 mAh 18W']],
                    ['title' => 'Samsung Galaxy A05s 4GB/64GB', 'brand' => 'samsung', 'sub' => 2, 'price' => 17999, 'sale' => 16500, 'stock' => 32, 'specs' => ['Display' => '6.7" FHD+ 90Hz PLS LCD', 'Chip' => 'Snapdragon 680', 'Camera' => '50MP Triple', 'Battery' => '5000 mAh 25W']],
                    ['title' => 'Walton Olvio MM26 Feature Phone', 'brand' => 'walton', 'sub' => 3, 'price' => 1850, 'sale' => 1699, 'stock' => 60, 'specs' => ['Display' => '2.4" QVGA', 'Battery' => '1800 mAh', 'SIM' => 'Dual SIM', 'Features' => 'Wireless FM, Flashlight']],
                ]
            ],
            // 2. Laptops & Ultrabooks
            [
                'cat_slug' => 'laptops-ultrabooks',
                'has_variants' => true,
                'variant_type' => 'laptop',
                'items' => [
                    ['title' => 'Apple MacBook Pro 16 M3 Max', 'brand' => 'apple', 'sub' => 1, 'price' => 449999, 'sale' => 429999, 'stock' => 8, 'specs' => ['Display' => '16.2" Liquid Retina XDR 120Hz', 'Chip' => 'M3 Max 16-core CPU', 'RAM' => '48GB Unified', 'SSD' => '1TB NVMe']],
                    ['title' => 'Apple MacBook Air 13 M3 16GB/512GB', 'brand' => 'apple', 'sub' => 1, 'price' => 148000, 'sale' => 139999, 'stock' => 22, 'specs' => ['Display' => '13.6" Liquid Retina 500 nits', 'Chip' => 'Apple M3 8-core', 'RAM' => '16GB', 'SSD' => '512GB']],
                    ['title' => 'ASUS ROG Zephyrus G16 OLED Gaming', 'brand' => 'asus', 'sub' => 0, 'price' => 285000, 'sale' => 269999, 'stock' => 10, 'specs' => ['Display' => '16" 2.5K 240Hz OLED', 'CPU' => 'Intel Core Ultra 9 185H', 'GPU' => 'RTX 4070 8GB', 'RAM' => '32GB LPDDR5X']],
                    ['title' => 'Lenovo Legion Pro 7i Gen 9', 'brand' => 'lenovo', 'sub' => 0, 'price' => 345000, 'sale' => 329000, 'stock' => 6, 'specs' => ['Display' => '16" WQXGA 240Hz 500 nits', 'CPU' => 'Intel Core i9-14900HX', 'GPU' => 'RTX 4080 12GB 175W', 'RAM' => '32GB DDR5']],
                    ['title' => 'Dell XPS 15 9530 Core i7', 'brand' => 'dell', 'sub' => 2, 'price' => 259000, 'sale' => 244999, 'stock' => 12, 'specs' => ['Display' => '15.6" FHD+ InfinityEdge', 'CPU' => 'Intel Core i7-13700H', 'GPU' => 'RTX 4050 6GB', 'SSD' => '512GB NVMe']],
                    ['title' => 'Lenovo ThinkPad X1 Carbon Gen 11', 'brand' => 'lenovo', 'sub' => 2, 'price' => 218000, 'sale' => 205000, 'stock' => 14, 'specs' => ['Display' => '14" WUXGA IPS Low Power', 'CPU' => 'Core i7-1365U vPro', 'RAM' => '16GB LPDDR5', 'Weight' => '1.12 kg']],
                    ['title' => 'HP Spectre x360 14 2-in-1 OLED', 'brand' => 'hp', 'sub' => 3, 'price' => 198000, 'sale' => 189999, 'stock' => 11, 'specs' => ['Display' => '14" 2.8K OLED 120Hz Touch', 'CPU' => 'Core Ultra 7 155H', 'RAM' => '16GB LPDDR5X', 'Stylus' => 'Rechargeable Tilt Pen']],
                    ['title' => 'HP Envy 16 Core i7 Laptop', 'brand' => 'hp', 'sub' => 2, 'price' => 175000, 'sale' => 165000, 'stock' => 15, 'specs' => ['Display' => '16" WQXGA 120Hz', 'CPU' => 'Core i7-13700H', 'GPU' => 'RTX 4060 8GB', 'Storage' => '1TB SSD']],
                    ['title' => 'Acer Predator Helios 16 Gaming', 'brand' => 'acer', 'sub' => 0, 'price' => 245000, 'sale' => 229999, 'stock' => 9, 'specs' => ['Display' => '16" 240Hz 3ms G-SYNC', 'CPU' => 'Core i7-13700HX', 'GPU' => 'RTX 4070 8GB', 'Cooling' => 'AeroBlade 3D Fans']],
                    ['title' => 'MSI Katana 15 Gaming Core i7', 'brand' => 'msi', 'sub' => 0, 'price' => 155000, 'sale' => 146999, 'stock' => 16, 'specs' => ['Display' => '15.6" FHD 144Hz IPS', 'CPU' => 'Core i7-13620H', 'GPU' => 'RTX 4060 8GB', 'RAM' => '16GB DDR5']],
                ]
            ],
            // 3. Desktop Computers
            [
                'cat_slug' => 'desktop-computers',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Apple iMac 24 4.5K Retina M3', 'brand' => 'apple', 'sub' => 1, 'price' => 195000, 'sale' => 185000, 'stock' => 9, 'specs' => ['Display' => '24" 4.5K Retina 4480x2520', 'Chip' => 'M3 8-core CPU 10-core GPU', 'RAM' => '8GB', 'SSD' => '512GB']],
                    ['title' => 'Apple Mac mini M2 Pro 16GB/512GB', 'brand' => 'apple', 'sub' => 3, 'price' => 165000, 'sale' => 155000, 'stock' => 14, 'specs' => ['Chip' => 'M2 Pro 10-core CPU 16-core GPU', 'RAM' => '16GB Unified', 'SSD' => '512GB', 'Ports' => '4x Thunderbolt 4']],
                    ['title' => 'ASUS ROG Strix G16CHR Gaming Desktop', 'brand' => 'asus', 'sub' => 0, 'price' => 220000, 'sale' => 209999, 'stock' => 6, 'specs' => ['CPU' => 'Intel Core i7-14700F', 'GPU' => 'RTX 4070 12GB', 'RAM' => '32GB DDR5', 'SSD' => '1TB NVMe']],
                    ['title' => 'Dell Precision 3660 Tower Workstation', 'brand' => 'dell', 'sub' => 2, 'price' => 275000, 'sale' => null, 'stock' => 5, 'specs' => ['CPU' => 'Intel Core i9-13900', 'GPU' => 'NVIDIA RTX A2000 12GB', 'RAM' => '32GB ECC DDR5', 'Storage' => '1TB SSD + 2TB HDD']],
                    ['title' => 'HP Pavilion 27 All-in-One PC Core i7', 'brand' => 'hp', 'sub' => 1, 'price' => 145000, 'sale' => 137000, 'stock' => 10, 'specs' => ['Display' => '27" FHD Touchscreen', 'CPU' => 'Core i7-13700T', 'RAM' => '16GB DDR4', 'Sound' => 'B&O Audio']],
                    ['title' => 'ASUS ExpertCenter PN64 Mini PC', 'brand' => 'asus', 'sub' => 3, 'price' => 68000, 'sale' => 63999, 'stock' => 17, 'specs' => ['CPU' => 'Core i5-13500H 12 cores', 'RAM' => '16GB DDR5', 'SSD' => '512GB NVMe', 'Video' => 'Quad 4K Display Support']],
                    ['title' => 'Apple Mac Studio M2 Max', 'brand' => 'apple', 'sub' => 2, 'price' => 285000, 'sale' => 269999, 'stock' => 7, 'specs' => ['Chip' => 'M2 Max 12-core CPU 30-core GPU', 'RAM' => '32GB Unified (400GB/s)', 'SSD' => '512GB', 'Display Support' => 'Up to 5 displays']],
                    ['title' => 'MSI MAG Infinite S3 Gaming Desktop', 'brand' => 'msi', 'sub' => 0, 'price' => 165000, 'sale' => 155000, 'stock' => 11, 'specs' => ['CPU' => 'Core i5-14400F', 'GPU' => 'RTX 4060 8GB', 'RAM' => '16GB DDR5', 'Storage' => '1TB M.2 PCIe NVMe']],
                    ['title' => 'Lenovo IdeaCentre AIO 3 24-inch Core i5', 'brand' => 'lenovo', 'sub' => 1, 'price' => 84000, 'sale' => 79999, 'stock' => 16, 'specs' => ['Display' => '23.8" FHD IPS', 'CPU' => 'Core i5-12450H', 'RAM' => '8GB DDR4', 'Speakers' => 'Harman Kardon 2x3W']],
                    ['title' => 'Dell OptiPlex 7010 Micro Desktop', 'brand' => 'dell', 'sub' => 3, 'price' => 72000, 'sale' => null, 'stock' => 20, 'specs' => ['CPU' => 'Core i5-13500T vPro', 'RAM' => '16GB DDR4', 'SSD' => '512GB NVMe', 'OS' => 'Windows 11 Pro']],
                ]
            ],
            // 4. Computer Components
            [
                'cat_slug' => 'computer-components',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Intel Core i9-14900K Desktop Processor', 'brand' => 'intel', 'sub' => 0, 'price' => 69000, 'sale' => 64999, 'stock' => 12, 'specs' => ['Cores' => '24 Cores (8P + 16E)', 'Threads' => '32', 'Max Clock' => '6.0 GHz', 'Socket' => 'LGA1700']],
                    ['title' => 'AMD Ryzen 7 7800X3D Gaming Processor', 'brand' => 'amd', 'sub' => 0, 'price' => 52000, 'sale' => 48999, 'stock' => 18, 'specs' => ['Cores' => '8 Cores / 16 Threads', 'Cache' => '96MB 3D V-Cache', 'Socket' => 'AM5', 'TDP' => '120W']],
                    ['title' => 'NVIDIA GeForce RTX 4090 24GB Founders', 'brand' => 'nvidia', 'sub' => 1, 'price' => 245000, 'sale' => 235000, 'stock' => 4, 'specs' => ['Memory' => '24GB GDDR6X 384-bit', 'CUDA Cores' => '16384', 'Architecture' => 'Ada Lovelace', 'Power' => '450W TDP']],
                    ['title' => 'MSI GeForce RTX 4070 Ti SUPER Gaming', 'brand' => 'msi', 'sub' => 1, 'price' => 118000, 'sale' => 112000, 'stock' => 10, 'specs' => ['Memory' => '16GB GDDR6X 256-bit', 'Cooling' => 'TRI FROZR 3', 'Ray Tracing' => '3rd Gen Cores', 'DLSS' => 'DLSS 3.5']],
                    ['title' => 'ASUS ROG Maximus Z790 Dark Hero', 'brand' => 'asus', 'sub' => 2, 'price' => 78000, 'sale' => 74000, 'stock' => 8, 'specs' => ['Socket' => 'LGA1700 for 14th Gen', 'VRM' => '20+1+2 Power Stages', 'PCIe' => 'PCIe 5.0 x16', 'Networking' => 'WiFi 7 + 2.5Gb LAN']],
                    ['title' => 'ASUS TUF Gaming B650-Plus WiFi', 'brand' => 'asus', 'sub' => 2, 'price' => 265000 / 10, 'sale' => 24999, 'stock' => 15, 'specs' => ['Socket' => 'AM5 for Ryzen 7000/8000', 'Power' => '12+2 DrMOS', 'RAM' => '4x DDR5 up to 7600+', 'M.2' => 'PCIe 5.0 M.2 slot']],
                    ['title' => 'Kingston FURY Beast 32GB (2x16GB) DDR5 6000', 'brand' => 'kingston', 'sub' => 3, 'price' => 14500, 'sale' => 13500, 'stock' => 30, 'specs' => ['Capacity' => '32GB (2x16GB Kit)', 'Speed' => 'DDR5 6000MT/s', 'Profile' => 'Intel XMP 3.0 & AMD EXPO', 'Latency' => 'CL36']],
                    ['title' => 'Kingston FURY Renegade 64GB DDR5 6400MHz', 'brand' => 'kingston', 'sub' => 3, 'price' => 28000, 'sale' => 25999, 'stock' => 14, 'specs' => ['Capacity' => '64GB (2x32GB)', 'Speed' => 'DDR5 6400MT/s', 'Heatsink' => 'Aluminum heat spreader', 'Latency' => 'CL32']],
                    ['title' => 'AMD Ryzen 5 7600X Desktop Processor', 'brand' => 'amd', 'sub' => 0, 'price' => 26500, 'sale' => 24500, 'stock' => 25, 'specs' => ['Cores' => '6 Cores / 12 Threads', 'Base/Boost' => '4.7 GHz / 5.3 GHz', 'Cache' => '38MB Total', 'Socket' => 'AM5']],
                    ['title' => 'ASUS ROG Thor 1000W Platinum II PSU', 'brand' => 'asus', 'sub' => 2, 'price' => 39500, 'sale' => 36999, 'stock' => 10, 'specs' => ['Wattage' => '1000W', 'Efficiency' => '80 PLUS Platinum', 'PCIe 5.0' => '16-pin 12VHPWR cable', 'Display' => 'OLED Power Display']],
                ]
            ],
            // 5. Computer Storage
            [
                'cat_slug' => 'computer-storage',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Samsung 990 PRO 2TB NVMe M.2 SSD', 'brand' => 'samsung', 'sub' => 0, 'price' => 24500, 'sale' => 22999, 'stock' => 25, 'specs' => ['Read Speed' => 'Up to 7450 MB/s', 'Write Speed' => 'Up to 6900 MB/s', 'Interface' => 'PCIe Gen 4.0 x4', 'DRAM' => '2GB LPDDR4']],
                    ['title' => 'Western Digital Black SN850X 1TB NVMe', 'brand' => 'western-digital', 'sub' => 0, 'price' => 13500, 'sale' => 12499, 'stock' => 30, 'specs' => ['Speed' => '7300 MB/s Read', 'Form Factor' => 'M.2 2280', 'Endurance' => '600 TBW', 'Gaming' => 'Game Mode 2.0']],
                    ['title' => 'Kingston KC3000 2TB PCIe 4.0 NVMe SSD', 'brand' => 'kingston', 'sub' => 0, 'price' => 19800, 'sale' => 18500, 'stock' => 20, 'specs' => ['Read/Write' => '7000 / 7000 MB/s', 'Controller' => 'Phison E18', 'Heatsink' => 'Graphene aluminum heat spreader', 'TBW' => '1600 TBW']],
                    ['title' => 'SanDisk Extreme Portable SSD 1TB V2', 'brand' => 'sandisk', 'sub' => 1, 'price' => 14500, 'sale' => 13200, 'stock' => 35, 'specs' => ['Speed' => '1050 MB/s Read, 1000 MB/s Write', 'Durability' => 'IP55 water & dust resistance', 'Interface' => 'USB 3.2 Gen 2 Type-C', 'Drop' => 'Up to 2-meter drop protection']],
                    ['title' => 'Western Digital My Passport 4TB External HDD', 'brand' => 'western-digital', 'sub' => 1, 'price' => 13800, 'sale' => 12500, 'stock' => 28, 'specs' => ['Capacity' => '4TB', 'Interface' => 'USB 3.2 Gen 1', 'Security' => '256-bit AES hardware encryption', 'Warranty' => '3-Year Limited']],
                    ['title' => 'Samsung T7 Shield 2TB Portable SSD', 'brand' => 'samsung', 'sub' => 1, 'price' => 22000, 'sale' => 20500, 'stock' => 18, 'specs' => ['Speed' => '1050 MB/s', 'Rugged' => 'IP65 Water/Dust resistant', 'Build' => 'Elastomer outer shell', 'Compatibility' => 'PC, Mac, Android, iPhone 15']],
                    ['title' => 'Samsung 870 EVO 1TB 2.5-inch SATA SSD', 'brand' => 'samsung', 'sub' => 2, 'price' => 11500, 'sale' => 10499, 'stock' => 32, 'specs' => ['Sequential Read' => '560 MB/s', 'Sequential Write' => '530 MB/s', 'Interface' => 'SATA 6 Gb/s', 'Reliability' => 'Up to 600 TBW']],
                    ['title' => 'Kingston A400 480GB 2.5-inch SATA SSD', 'brand' => 'kingston', 'sub' => 2, 'price' => 4500, 'sale' => 3999, 'stock' => 50, 'specs' => ['Form Factor' => '2.5-inch 7mm', 'Read/Write' => '500MB/s / 450MB/s', 'Controller' => '2Ch', 'Ideal for' => 'Budget system boot drive']],
                    ['title' => 'SanDisk Ultra Dual Drive Luxe 128GB Type-C', 'brand' => 'sandisk', 'sub' => 3, 'price' => 2200, 'sale' => 1950, 'stock' => 60, 'specs' => ['Connectors' => 'Reversible USB Type-C & Type-A', 'Speed' => 'Up to 400 MB/s read', 'Body' => 'All-metal swivel design', 'Capacity' => '128GB']],
                    ['title' => 'SanDisk Ultra Flair 64GB USB 3.0 Flash Drive', 'brand' => 'sandisk', 'sub' => 3, 'price' => 950, 'sale' => 850, 'stock' => 70, 'specs' => ['Speed' => 'Up to 150 MB/s', 'Casing' => 'Durable sleek metal', 'Interface' => 'USB 3.0 (backward compatible)', 'Capacity' => '64GB']],
                ]
            ],
            // 6. Monitors & Displays
            [
                'cat_slug' => 'monitors-displays',
                'has_variants' => false,
                'items' => [
                    ['title' => 'ASUS ROG Swift OLED PG27AQDM Gaming Monitor', 'brand' => 'asus', 'sub' => 0, 'price' => 135000, 'sale' => 126999, 'stock' => 8, 'specs' => ['Panel' => '27" 1440p QHD OLED', 'Refresh Rate' => '240Hz', 'Response Time' => '0.03ms (GTG)', 'G-SYNC' => 'G-SYNC Compatible']],
                    ['title' => 'Dell UltraSharp U2723QE 27-inch 4K USB-C Hub', 'brand' => 'dell', 'sub' => 1, 'price' => 78000, 'sale' => 73500, 'stock' => 15, 'specs' => ['Panel' => '27" 4K IPS Black Technology', 'Contrast' => '2000:1 contrast ratio', 'Color' => '98% DCI-P3, HDR 400', 'Hub' => '90W USB-C Power Delivery + RJ45']],
                    ['title' => 'Samsung Odyssey G9 49-inch Curved DQHD 240Hz', 'brand' => 'samsung', 'sub' => 2, 'price' => 185000, 'sale' => 174999, 'stock' => 5, 'specs' => ['Aspect Ratio' => '32:9 Super Ultrawide', 'Curvature' => '1000R deep curve', 'Resolution' => '5120 x 1440 Dual QHD', 'Refresh' => '240Hz 1ms']],
                    ['title' => 'LG UltraGear 27GP850-B Nano IPS 165Hz', 'brand' => 'lg', 'sub' => 0, 'price' => 45000, 'sale' => 41999, 'stock' => 20, 'specs' => ['Display' => '27" QHD (2560 x 1440) Nano IPS', 'Speed' => '1ms (GtG) 165Hz (O/C 180Hz)', 'HDR' => 'VESA DisplayHDR 400', 'Sync' => 'NVIDIA G-SYNC & AMD FreeSync Premium']],
                    ['title' => 'Acer Predator XB273U V3 180Hz Gaming Monitor', 'brand' => 'acer', 'sub' => 0, 'price' => 38000, 'sale' => 34999, 'stock' => 22, 'specs' => ['Size' => '27" WQHD Agile-Splendor IPS', 'Refresh' => '180Hz 0.5ms', 'Color' => '95% DCI-P3 Delta E < 1', 'Speakers' => 'Dual 2W built-in']],
                    ['title' => 'ASUS ProArt Display PA278CV Professional', 'brand' => 'asus', 'sub' => 1, 'price' => 46000, 'sale' => 42500, 'stock' => 14, 'specs' => ['Size' => '27" WQHD IPS', 'Accuracy' => 'Calman Verified Delta E < 2', 'Gamut' => '100% sRGB and 100% Rec. 709', 'Port' => 'USB-C with 65W charging']],
                    ['title' => 'MSI Optix MAG342CQR 34-inch Ultrawide Curved', 'brand' => 'msi', 'sub' => 2, 'price' => 59000, 'sale' => 54999, 'stock' => 11, 'specs' => ['Panel' => '34" UWQHD (3440 x 1440) VA', 'Curve' => '1500R Curved', 'Refresh' => '144Hz 1ms', 'RGB' => 'Mystic Light ambient rear glow']],
                    ['title' => 'ASUS ZenScreen MB16AH Portable Monitor', 'brand' => 'asus', 'sub' => 3, 'price' => 26000, 'sale' => 23999, 'stock' => 16, 'specs' => ['Panel' => '15.6" Full HD IPS Anti-glare', 'Weight' => '0.73 kg ultra-portable', 'Ports' => 'USB Type-C and Micro-HDMI', 'Case' => 'Foldable smart kickstand case']],
                    ['title' => 'Dell P2422H 24-inch FHD IPS Office Monitor', 'brand' => 'dell', 'sub' => 1, 'price' => 23500, 'sale' => 21999, 'stock' => 30, 'specs' => ['Display' => '23.8" FHD 1080p IPS 60Hz', 'Ergonomics' => 'Height, pivot, tilt, swivel adjustable', 'Bezel' => 'Three-sided ultrathin bezel', 'Eye Care' => 'ComfortView Plus low blue light']],
                    ['title' => 'Samsung 32-inch Smart Monitor M7 4K UHD', 'brand' => 'samsung', 'sub' => 1, 'price' => 42000, 'sale' => 38999, 'stock' => 15, 'specs' => ['Size' => '32" 4K UHD (3840 x 2160) VA', 'Smart OS' => 'Tizen OS with Netflix, YouTube built-in', 'Remote' => 'SolarCell Voice Remote', 'Hub' => 'IoT SmartThings Hub']],
                ]
            ],
            // 7. PC Peripherals & Accessories
            [
                'cat_slug' => 'pc-peripherals-accessories',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Logitech MX Master 3S Wireless Performance Mouse', 'brand' => 'logitech', 'sub' => 1, 'price' => 12500, 'sale' => 11499, 'stock' => 35, 'specs' => ['Sensor' => '8000 DPI Darkfield glass tracking', 'Clicks' => 'Quiet Clicks 90% noise reduction', 'Scroll' => 'MagSpeed Electromagnetic 1000 lines/sec', 'Battery' => 'Up to 70 days rechargeable']],
                    ['title' => 'Razer BlackWidow V4 Pro Mechanical Keyboard', 'brand' => 'razer', 'sub' => 0, 'price' => 24500, 'sale' => 22999, 'stock' => 12, 'specs' => ['Switches' => 'Razer Green Mechanical (Tactile & Clicky)', 'Lighting' => 'Per-key Chroma RGB + 3-side underglow', 'Control' => 'Razer Command Dial + 8 macro keys', 'Wrist Rest' => 'Magnetic plush leatherette']],
                    ['title' => 'Logitech G PRO X Superlight 2 Wireless Gaming Mouse', 'brand' => 'logitech', 'sub' => 1, 'price' => 17500, 'sale' => 15999, 'stock' => 20, 'specs' => ['Weight' => 'Ultra-lightweight 60 grams', 'Sensor' => 'HERO 2 32000 DPI 500+ IPS', 'Polling' => '4000Hz wireless polling rate', 'Feet' => 'Zero-additive PTFE']],
                    ['title' => 'Razer DeathAdder V3 Pro Wireless Gaming Mouse', 'brand' => 'razer', 'sub' => 1, 'price' => 16000, 'sale' => 14800, 'stock' => 22, 'specs' => ['Form' => 'Ergonomic 63g featherweight', 'Sensor' => 'Focus Pro 30K Optical Sensor', 'Switches' => 'Optical Mouse Switches Gen-3 90M clicks', 'Battery' => 'Up to 90 hours battery']],
                    ['title' => 'Logitech Brio 4K Ultra HD Webcam with HDR', 'brand' => 'logitech', 'sub' => 3, 'price' => 19500, 'sale' => 17999, 'stock' => 18, 'specs' => ['Resolution' => '4K Ultra HD at 30 fps or 1080p at 60 fps', 'Lighting' => 'RightLight 3 with HDR', 'FOV' => 'Adjustable 65°, 78°, 90° field of view', 'Security' => 'Windows Hello facial recognition']],
                    ['title' => 'Anker 575 USB-C Triple Display 13-in-1 Dock', 'brand' => 'anker', 'sub' => 3, 'price' => 18500, 'sale' => 16999, 'stock' => 15, 'specs' => ['Ports' => '13 ports (dual HDMI, DP, 85W pass-through)', 'Display' => 'Triple display 4K output support', 'Charging' => '85W high-speed laptop charging', 'Data' => '10 Gbps USB-C and USB-A ports']],
                    ['title' => 'SteelSeries QcK Heavy XXL Gaming Mousepad', 'brand' => 'razer', 'sub' => 2, 'price' => 3800, 'sale' => 3400, 'stock' => 45, 'specs' => ['Dimensions' => '900 x 400 x 4 mm', 'Surface' => 'Exclusive QcK micro-woven cloth', 'Base' => 'Extra thick non-slip rubber base', 'Edge' => 'Durable stitched edges']],
                    ['title' => 'Logitech MX Mechanical Wireless Illuminated Keyboard', 'brand' => 'logitech', 'sub' => 0, 'price' => 18900, 'sale' => 17500, 'stock' => 16, 'specs' => ['Switches' => 'Low Profile Tactile Quiet switches', 'Backlit' => 'Smart illumination auto hand detection', 'Multi-Device' => 'Pair up to 3 devices via Bluetooth/Bolt', 'Battery' => '15 days or up to 10 months backlighting off']],
                    ['title' => 'Razer Gigantus V2 Large Gaming Mouse Pad', 'brand' => 'razer', 'sub' => 2, 'price' => 2200, 'sale' => 1950, 'stock' => 50, 'specs' => ['Size' => '450 x 400 x 3 mm Large', 'Fabric' => 'Textured micro-weave cloth surface', 'Speed' => 'Optimized across all mouse sensors', 'Rubber' => 'High-density rubber foam with anti-slip base']],
                    ['title' => 'Anker 7-in-1 USB-C Hub with 4K HDMI', 'brand' => 'anker', 'sub' => 3, 'price' => 4999, 'sale' => 4499, 'stock' => 40, 'specs' => ['Connectivity' => '4K HDMI, 100W Power Delivery, SD/TF Card, 2x USB 3.0', 'HDMI' => 'Up to 4K @ 60Hz', 'Housing' => 'Sleek aluminum alloy body', 'Weight' => '75g pocket sized']],
                ]
            ],
            // 8. Networking & WiFi
            [
                'cat_slug' => 'networking-wifi',
                'has_variants' => false,
                'items' => [
                    ['title' => 'TP-Link Archer AXE75 Tri-Band WiFi 6E Router', 'brand' => 'tp-link', 'sub' => 0, 'price' => 19500, 'sale' => 18200, 'stock' => 20, 'specs' => ['Speed' => 'AXE5400 Tri-Band (2402 + 2402 + 574 Mbps)', 'Band' => 'New 6GHz band zero interference', 'Processor' => '1.7 GHz Quad-Core CPU', 'Antennas' => '6x high gain external antennas']],
                    ['title' => 'ASUS ROG Rapture GT-AXE16000 Quad-Band Router', 'brand' => 'asus', 'sub' => 0, 'price' => 65000, 'sale' => 61000, 'stock' => 6, 'specs' => ['Class' => 'World first Quad-band WiFi 6E 16000 Mbps', 'Ports' => 'Dual 10G ports and 2.5G WAN port', 'Gaming' => 'Triple-level game acceleration', 'Coverage' => 'RangeBoost Plus extreme range']],
                    ['title' => 'TP-Link Deco X50 Whole Home Mesh WiFi 6 (3-Pack)', 'brand' => 'tp-link', 'sub' => 1, 'price' => 24500, 'sale' => 22999, 'stock' => 16, 'specs' => ['Speed' => 'AX3000 Dual Band (2402 + 574 Mbps)', 'Coverage' => 'Up to 6500 sq ft seamless roaming', 'Capacity' => 'Connect over 150 devices', 'AI Mesh' => 'Intelligent algorithm learns network environment']],
                    ['title' => 'TP-Link Archer AX73 Dual-Band Gigabit WiFi 6', 'brand' => 'tp-link', 'sub' => 0, 'price' => 12500, 'sale' => 11499, 'stock' => 28, 'specs' => ['Speed' => 'AX5400 (4804 Mbps 5GHz + 574 Mbps 2.4GHz)', 'Streams' => '6 simultaneous streams with 4x4 MU-MIMO', 'USB' => 'USB 3.0 port for easy media sharing', 'Security' => 'HomeShield advanced IoT protection']],
                    ['title' => 'TP-Link RE705X AX3000 WiFi 6 Range Extender', 'brand' => 'tp-link', 'sub' => 2, 'price' => 7500, 'sale' => 6999, 'stock' => 30, 'specs' => ['Speed' => 'Dual Band AX3000 (2402 + 574 Mbps)', 'Mesh' => 'Compatible with OneMesh routers', 'Ethernet' => 'Gigabit Ethernet port for wired devices', 'Signal' => 'Adaptive path selection']],
                    ['title' => 'TP-Link TL-SG108 8-Port Gigabit Desktop Switch', 'brand' => 'tp-link', 'sub' => 3, 'price' => 2800, 'sale' => 2499, 'stock' => 45, 'specs' => ['Ports' => '8x 10/100/1000Mbps Auto-Negotiation RJ45', 'Case' => 'Sturdy steel desktop housing', 'Green' => 'Green Ethernet technology saves power', 'QoS' => '802.1p/DSCP QoS and IGMP Snooping']],
                    ['title' => 'TP-Link Deco S7 AC1900 Whole Home Mesh (2-Pack)', 'brand' => 'tp-link', 'sub' => 1, 'price' => 10500, 'sale' => 9700, 'stock' => 25, 'specs' => ['Speed' => 'AC1900 (1300 Mbps on 5GHz + 600 Mbps on 2.4GHz)', 'Coverage' => 'Up to 3800 sq ft dead-zone killer', 'Ports' => '3x Gigabit Ethernet ports per unit', 'Parental' => 'Robust parental control filters']],
                    ['title' => 'ASUS RT-AX86U Pro Dual-Band WiFi 6 Gaming Router', 'brand' => 'asus', 'sub' => 0, 'price' => 28000, 'sale' => 25999, 'stock' => 12, 'specs' => ['Speed' => 'AX5700 up to 5700 Mbps', 'Port' => '2.5G port for ultra-fast multi-gigabit connections', 'Mobile Gaming' => 'Mobile Game Mode minimizes lag in ASUS app', 'Security' => 'AiProtection Pro powered by Trend Micro']],
                    ['title' => 'TP-Link RE315 AC1200 OneMesh WiFi Range Extender', 'brand' => 'tp-link', 'sub' => 2, 'price' => 3200, 'sale' => 2899, 'stock' => 40, 'specs' => ['Speed' => 'AC1200 Dual Band (867 Mbps 5GHz + 300 Mbps 2.4GHz)', 'Indicator' => 'Smart signal indicator helps find optimal placement', 'Mode' => 'AP mode transforms wired connection into wireless', 'OneMesh' => 'Creates seamless mesh network']],
                    ['title' => 'TP-Link TL-SG105 5-Port Gigabit Desktop Switch', 'brand' => 'tp-link', 'sub' => 3, 'price' => 1950, 'sale' => 1750, 'stock' => 50, 'specs' => ['Ports' => '5x Gigabit RJ45 Shielded ports', 'Design' => 'Fanless quiet metal chassis', 'Setup' => 'Plug and play, no configuration needed', 'Buffer' => 'Non-blocking architecture']],
                ]
            ],
            // 9. Tablets & E-Readers
            [
                'cat_slug' => 'tablets-e-readers',
                'has_variants' => true,
                'variant_type' => 'tablet',
                'items' => [
                    ['title' => 'Apple iPad Pro 12.9 M2 Wi-Fi 256GB', 'brand' => 'apple', 'sub' => 0, 'price' => 155000, 'sale' => 146999, 'stock' => 12, 'specs' => ['Display' => '12.9" Liquid Retina XDR Mini-LED 120Hz', 'Chip' => 'Apple M2 8-core CPU 10-core GPU', 'Storage' => '256GB', 'Camera' => '12MP Wide + 10MP Ultra-Wide LiDAR']],
                    ['title' => 'Samsung Galaxy Tab S9 Ultra 5G 512GB', 'brand' => 'samsung', 'sub' => 1, 'price' => 165000, 'sale' => 154999, 'stock' => 8, 'specs' => ['Display' => '14.6" Dynamic AMOLED 2X 120Hz', 'Chip' => 'Snapdragon 8 Gen 2 for Galaxy', 'Pen' => 'IP68 S Pen included with bi-directional charging', 'Water' => 'IP68 water and dust resistant']],
                    ['title' => 'Apple iPad Air 11 M2 128GB Wi-Fi', 'brand' => 'apple', 'sub' => 0, 'price' => 86000, 'sale' => 81999, 'stock' => 20, 'specs' => ['Display' => '11" Liquid Retina display True Tone', 'Chip' => 'Apple M2 chip', 'Camera' => 'Landscape 12MP Ultra Wide front camera', 'Weight' => '462 grams']],
                    ['title' => 'Apple iPad 10th Gen 10.9 Wi-Fi 64GB', 'brand' => 'apple', 'sub' => 0, 'price' => 52000, 'sale' => 48999, 'stock' => 28, 'specs' => ['Display' => '10.9" Liquid Retina display', 'Chip' => 'A14 Bionic chip 6-core CPU', 'Port' => 'USB-C for versatile accessories', 'Colors' => 'Silver, Blue, Pink, Yellow']],
                    ['title' => 'Xiaomi Pad 6 8GB/256GB Tablet', 'brand' => 'xiaomi', 'sub' => 1, 'price' => 38000, 'sale' => 35500, 'stock' => 24, 'specs' => ['Display' => '11" 2.8K 144Hz 7-gear variable refresh', 'Chip' => 'Snapdragon 870 Flagship 7nm', 'Audio' => 'Quad stereo speakers Dolby Atmos', 'Battery' => '8840 mAh with 33W fast charge']],
                    ['title' => 'Samsung Galaxy Tab A9+ 8GB/128GB Wi-Fi', 'brand' => 'samsung', 'sub' => 1, 'price' => 28500, 'sale' => 26999, 'stock' => 25, 'specs' => ['Display' => '11.0" 90Hz WQXGA Display', 'Processor' => 'Qualcomm Snapdragon 695 5G', 'Speakers' => 'Quad speakers with Dolby 3D sound', 'DeX' => 'Samsung DeX multitasking support']],
                    ['title' => 'Amazon Kindle Paperwhite 16GB 6.8-inch', 'brand' => 'google', 'sub' => 3, 'price' => 18500, 'sale' => 16999, 'stock' => 30, 'specs' => ['Display' => '6.8" 300 ppi glare-free E-ink screen', 'Light' => 'Adjustable warm light 17 LEDs', 'Battery' => 'Up to 10 weeks battery life on single charge', 'Waterproof' => 'IPX8 withstands immersion in water']],
                    ['title' => 'Apple iPad mini 6th Gen 64GB Wi-Fi', 'brand' => 'apple', 'sub' => 0, 'price' => 64000, 'sale' => 59999, 'stock' => 15, 'specs' => ['Display' => '8.3" Liquid Retina compact display', 'Chip' => 'A15 Bionic with Neural Engine', 'Pencil' => 'Supports Apple Pencil 2nd gen magnetically', 'Design' => 'Edge-to-edge screen with Touch ID on top']],
                    ['title' => 'Wacom One 13.3-inch Pen Drawing Display', 'brand' => 'asus', 'sub' => 2, 'price' => 45000, 'sale' => 41999, 'stock' => 10, 'specs' => ['Screen' => '13.3" Full HD 1920x1080 paper-like friction', 'Pen' => 'Battery-free pen with 4096 pressure levels', 'Tilt' => '60-degree natural tilt recognition', 'OS' => 'Compatible with Windows, Mac, and Android']],
                    ['title' => 'BOOX Note Air3 B&W 10.3 E-Ink Tablet', 'brand' => 'xiaomi', 'sub' => 3, 'price' => 58000, 'sale' => 54000, 'stock' => 8, 'specs' => ['Display' => '10.3" Carta 1200 glass screen with flat-cover', 'OS' => 'Android 12 open system with Google Play Store', 'Stylus' => 'Magnetic stylus with digital eraser', 'Chassis' => 'Solid aluminum casing 5.8mm thin']],
                ]
            ],
            // 10. Smartwatches & Wearables
            [
                'cat_slug' => 'smartwatches-wearables',
                'has_variants' => true,
                'variant_type' => 'watch',
                'items' => [
                    ['title' => 'Apple Watch Ultra 2 GPS + Cellular 49mm', 'brand' => 'apple', 'sub' => 1, 'price' => 115000, 'sale' => 108999, 'stock' => 10, 'specs' => ['Case' => '49mm aerospace titanium case', 'Display' => '3000 nits Always-On Retina OLED', 'Chip' => 'S9 SiP with Double Tap gesture', 'Battery' => 'Up to 72 hours in low power mode']],
                    ['title' => 'Samsung Galaxy Watch 6 Classic 47mm LTE', 'brand' => 'samsung', 'sub' => 1, 'price' => 42000, 'sale' => 38999, 'stock' => 18, 'specs' => ['Bezel' => 'Physical rotating stainless steel bezel', 'Screen' => '1.5" Sapphire Crystal Super AMOLED', 'Health' => 'BIA body composition, ECG, blood pressure', 'OS' => 'Wear OS Powered by Samsung']],
                    ['title' => 'Apple Watch Series 9 GPS 45mm Aluminum', 'brand' => 'apple', 'sub' => 1, 'price' => 58000, 'sale' => 54999, 'stock' => 20, 'specs' => ['Display' => '2000 nits edge-to-edge Retina display', 'Gesture' => 'Double Tap gesture for one-hand control', 'Sensors' => 'Blood Oxygen, ECG, Temperature sensing', 'Eco' => 'First carbon neutral Apple product']],
                    ['title' => 'Xiaomi Smart Band 8 Active Fitness Tracker', 'brand' => 'xiaomi', 'sub' => 0, 'price' => 2850, 'sale' => 2499, 'stock' => 50, 'specs' => ['Display' => '1.47" TFT vibrant color display', 'Battery' => 'Up to 14 days normal usage', 'Tracking' => 'All-day SpO2, heart rate, sleep tracking', 'Sports' => '50+ fitness workout modes']],
                    ['title' => 'Xiaomi Watch 2 Pro Wear OS Smartwatch', 'brand' => 'xiaomi', 'sub' => 1, 'price' => 28500, 'sale' => 26000, 'stock' => 15, 'specs' => ['OS' => 'Google Wear OS with Google Assistant & Maps', 'Chip' => 'Snapdragon W5+ Gen 1 4nm processor', 'Display' => '1.43" AMOLED with rotatable crown', 'Body' => 'Classic stainless steel casing']],
                    ['title' => 'Garmin Forerunner 265 GPS Running Watch', 'brand' => 'sony', 'sub' => 2, 'price' => 56000, 'sale' => 52500, 'stock' => 9, 'specs' => ['Screen' => '1.3" Colorful AMOLED touchscreen display', 'Battery' => 'Up to 13 days in smartwatch mode', 'Metrics' => 'Training readiness, HRV status, VO2 max', 'GPS' => 'Multi-band GNSS with SatIQ technology']],
                    ['title' => 'Fitbit Charge 6 Advanced Fitness Tracker', 'brand' => 'google', 'sub' => 0, 'price' => 19500, 'sale' => 17999, 'stock' => 22, 'specs' => ['Integration' => 'Google Maps, Google Wallet & YouTube Music', 'Sensor' => 'EDA Scan for stress, ECG heart rhythm app', 'Battery' => '7-day battery life, 50m water resistant', 'Heart Rate' => '60% more accurate tracking during intense workouts']],
                    ['title' => 'Amazfit GTR 4 Smartwatch 14-Day Battery', 'brand' => 'xiaomi', 'sub' => 1, 'price' => 22000, 'sale' => 19999, 'stock' => 16, 'specs' => ['Display' => '1.43" HD AMOLED anti-glare glass bezel', 'GPS' => 'Dual-band circularly-polarized GPS tracking', 'Sports' => '150+ sports modes with smart recognition', 'Calls' => 'Bluetooth phone calls with speaker and mic']],
                    ['title' => 'Oura Ring Gen 3 Horizon Heritage Smart Ring', 'brand' => 'apple', 'sub' => 3, 'price' => 45000, 'sale' => 42000, 'stock' => 8, 'specs' => ['Form' => 'Sleek seamless circular titanium ring', 'Sensors' => 'Research-grade sensors: Sleep, Readiness, Activity', 'Battery' => 'Up to 7 days battery with wireless fast dock', 'Water' => 'Water resistant up to 100 meters']],
                    ['title' => 'Huawei Watch Fit 3 AMOLED Ultra-Slim', 'brand' => 'xiaomi', 'sub' => 0, 'price' => 15500, 'sale' => 13999, 'stock' => 25, 'specs' => ['Screen' => '1.82" AMOLED 1500 nits peak brightness', 'Profile' => '9.9mm ultra-thin lightweight body 26g', 'Management' => 'Comprehensive Calorie and Diet Management', 'Battery' => 'Up to 10 days max battery life']],
                ]
            ],
            // 11. Headphones & Audio
            [
                'cat_slug' => 'headphones-audio',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Sony WH-1000XM5 Wireless Noise Cancelling', 'brand' => 'sony', 'sub' => 1, 'price' => 38000, 'sale' => 34999, 'stock' => 20, 'specs' => ['ANC' => 'Auto NC Optimizer with 8 microphones & dual processors', 'Driver' => 'Specially designed 30mm carbon fiber driver', 'Calls' => '4 beamforming mics with AI noise reduction', 'Battery' => '30 hours with quick 3-min charge for 3 hours']],
                    ['title' => 'Apple AirPods Pro 2nd Gen USB-C MagSafe', 'brand' => 'apple', 'sub' => 0, 'price' => 28500, 'sale' => 26500, 'stock' => 30, 'specs' => ['Chip' => 'Apple H2 headphone chip with Adaptive Audio', 'ANC' => 'Up to 2x more Active Noise Cancellation', 'Audio' => 'Personalized Spatial Audio with dynamic head tracking', 'Case' => 'MagSafe Case (USB-C) with speaker & lanyard loop']],
                    ['title' => 'Bose QuietComfort Ultra Wireless Headphones', 'brand' => 'bose', 'sub' => 1, 'price' => 46000, 'sale' => 42999, 'stock' => 12, 'specs' => ['Immersion' => 'Bose Immersive Audio spatial sound stage', 'ANC' => 'World-class Quiet, Aware and Immersion modes', 'CustomTune' => 'Personalizes audio performance to ear shape', 'Battery' => 'Up to 24 hours battery life']],
                    ['title' => 'Sony WF-1000XM5 True Wireless Earbuds', 'brand' => 'sony', 'sub' => 0, 'price' => 29500, 'sale' => 27500, 'stock' => 18, 'specs' => ['ANC' => 'Integrated Processor V2 and HD Noise Cancelling QN2e', 'Driver' => 'Dynamic Driver X for wide frequency reproduction', 'Hi-Res' => 'LDAC Hi-Res Audio Wireless certified', 'Fit' => 'Noise isolation earbud tips for snug fit']],
                    ['title' => 'Audio-Technica ATH-M50x Professional Monitor', 'brand' => 'sony', 'sub' => 3, 'price' => 18500, 'sale' => 16999, 'stock' => 22, 'specs' => ['Drivers' => 'Proprietary 45mm large-aperture drivers', 'Magnets' => 'Rare earth magnets and copper-clad aluminum wire', 'Clarity' => 'Exceptional clarity with deep accurate bass response', 'Design' => '90-degree swiveling earcups for one-ear monitoring']],
                    ['title' => 'Anker Soundcore Liberty 4 NC Wireless Earbuds', 'brand' => 'anker', 'sub' => 0, 'price' => 8500, 'sale' => 7499, 'stock' => 40, 'specs' => ['ANC' => 'Reduces noise by up to 98.5% with high sensitivity sensor', 'Hi-Res' => '11mm custom drivers with LDAC Hi-Res sound', 'Playtime' => '10H playtime / 50H total with charging case', 'Calls' => '6-mic AI clear voice call algorithm']],
                    ['title' => 'JBL Live 660NC Wireless Over-Ear Headphones', 'brand' => 'jbl', 'sub' => 1, 'price' => 14500, 'sale' => 12999, 'stock' => 25, 'specs' => ['Sound' => 'JBL Signature Sound with 40mm drivers', 'ANC' => 'Adaptive Noise Cancelling with Ambient Aware', 'Battery' => 'Up to 50 hours battery (40H with ANC on)', 'Assistant' => 'Voice assistant integration via Hey Google']],
                    ['title' => 'Razer BlackShark V2 Pro Wireless Gaming Headset', 'brand' => 'razer', 'sub' => 2, 'price' => 21000, 'sale' => 18999, 'stock' => 16, 'specs' => ['Drivers' => 'Razer TriForce Titanium 50mm Drivers', 'Mic' => 'Razer HyperClear Super Wideband Mic', 'Wireless' => 'Razer HyperSpeed Wireless 2.4GHz + Bluetooth', 'Battery' => 'Up to 70 hours with Type-C fast charging']],
                    ['title' => 'Apple AirPods 3rd Gen with Lightning Case', 'brand' => 'apple', 'sub' => 0, 'price' => 21000, 'sale' => 19500, 'stock' => 28, 'specs' => ['Sound' => 'Personalized Spatial Audio with dynamic head tracking', 'EQ' => 'Adaptive EQ automatically tunes music to ears', 'Design' => 'Contoured design with force sensor controls', 'Resistance' => 'IPX4 sweat and water resistant']],
                    ['title' => 'Shure SE215 PRO Sound Isolating Earphones', 'brand' => 'sony', 'sub' => 3, 'price' => 13500, 'sale' => 12200, 'stock' => 20, 'specs' => ['Sound' => 'Clear sound and deep bass from single dynamic MicroDriver', 'Isolation' => 'Blocks up to 37 dB of ambient stage noise', 'Cable' => 'Detachable Kevlar-reinforced MMCX 3.5mm wire', 'Fit' => 'Secure over-the-ear configuration']],
                ]
            ],
            // 12. Speakers & Home Audio
            [
                'cat_slug' => 'speakers-home-audio',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'JBL Charge 5 Waterproof Portable Speaker', 'brand' => 'jbl', 'sub' => 0, 'price' => 17500, 'sale' => 15999, 'stock' => 30, 'specs' => ['Sound' => 'JBL Original Pro Sound with separate tweeter and dual bass radiators', 'Battery' => '20 hours of playtime with built-in powerbank', 'Durability' => 'IP67 waterproof and dustproof', 'PartyBoost' => 'Pair multiple compatible JBL speakers']],
                    ['title' => 'JBL PartyBox 310 Portable Bluetooth Party Speaker', 'brand' => 'jbl', 'sub' => 3, 'price' => 64000, 'sale' => 59999, 'stock' => 8, 'specs' => ['Power' => '240 Watts of powerful JBL Pro Sound', 'Lights' => 'Dynamic light show synced to the beat', 'Battery' => '18-hour battery life with smooth-glide wheels and handle', 'Inputs' => 'Mic and guitar inputs with built-in vocal tuning']],
                    ['title' => 'Sony HT-A7000 7.1.2ch Dolby Atmos Soundbar', 'brand' => 'sony', 'sub' => 1, 'price' => 125000, 'sale' => 115000, 'stock' => 6, 'specs' => ['Channels' => '7.1.2ch 500W total output with 360 Spatial Sound', 'Technology' => 'S-Force PRO Front Surround and Vertical Surround Engine', 'Passthrough' => '8K and 4K 120Hz HDMI 2.1 passthrough for gaming', 'Integration' => 'BRAVIA Acoustic Center Sync compatible']],
                    ['title' => 'Bose SoundLink Flex Bluetooth Speaker', 'brand' => 'bose', 'sub' => 0, 'price' => 16500, 'sale' => 14999, 'stock' => 22, 'specs' => ['Tech' => 'PositionIQ technology automatically optimizes sound orientation', 'Water' => 'IP67 waterproof and floats in water', 'Build' => 'Steel grille and powder-coated silicone exterior', 'Battery' => 'Up to 12 hours playtime per charge']],
                    ['title' => 'JBL Flip 6 Portable Waterproof Bluetooth Speaker', 'brand' => 'jbl', 'sub' => 0, 'price' => 12500, 'sale' => 11200, 'stock' => 35, 'specs' => ['Acoustics' => '2-way speaker system with racetrack woofer and separate tweeter', 'Rating' => 'IP67 waterproof and dustproof construction', 'Playtime' => '12 hours of portable party playtime', 'App' => 'JBL Portable app for equalizer tuning']],
                    ['title' => 'JBL Bar 500 5.1-Channel Soundbar with Multibeam', 'brand' => 'jbl', 'sub' => 1, 'price' => 58000, 'sale' => 53999, 'stock' => 10, 'specs' => ['Output' => '590W Total System Power with 10" wireless subwoofer', 'Surround' => 'MultiBeam technology and Dolby Atmos 3D audio', 'Voice' => 'PureVoice dialogue enhancement technology', 'Streaming' => 'AirPlay, Alexa Multi-Room Music and Chromecast built-in']],
                    ['title' => 'Anker Soundcore Motion Boom Plus Outdoor Speaker', 'brand' => 'anker', 'sub' => 0, 'price' => 18000, 'sale' => 15999, 'stock' => 20, 'specs' => ['Output' => '80W Booming Stereo Sound with dual 30W woofers & 10W tweeters', 'Bass' => 'BassUp technology with titanium drivers', 'Waterproof' => 'IP67 waterproof, dustproof and floats', 'Battery' => 'Up to 20 hours playtime with powerbank charge out']],
                    ['title' => 'Sony SRS-XE300 X-Series Wireless Speaker', 'brand' => 'sony', 'sub' => 0, 'price' => 19500, 'sale' => 17500, 'stock' => 18, 'specs' => ['Diffuser' => 'Line-Shape Diffuser sends music across wider soundstage', 'Drivers' => 'X-Balanced Speaker Unit for rich, powerful sound', 'Durability' => 'IP67 waterproof, dustproof, and shockproof', 'Battery' => '24 hours battery with ambient noise sensing']],
                    ['title' => 'Sony HT-S20R 5.1ch Dolby Digital Soundbar', 'brand' => 'sony', 'sub' => 2, 'price' => 24500, 'sale' => 22500, 'stock' => 25, 'specs' => ['Setup' => 'Real 5.1ch surround sound with rear speakers & subwoofer', 'Power' => '400W total power output fills room with sound', 'Connectivity' => 'HDMI ARC, Optical, Analog and USB audio playback', 'Modes' => 'Auto Sound, Cinema, Music, Voice, Night modes']],
                    ['title' => 'JBL PartyBox Encore Essential with Mic', 'brand' => 'jbl', 'sub' => 3, 'price' => 34000, 'sale' => 31000, 'stock' => 14, 'specs' => ['Power' => '100W JBL Original Pro Sound with deep bass', 'Light' => 'Dynamic light show with fun ring strobe light', 'Playtime' => '6 hours battery life with splash-proof IPX4 design', 'Karaoke' => 'Wired microphone input with gain control']],
                ]
            ],
            // 13. Cameras & Photography
            [
                'cat_slug' => 'cameras-photography',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Sony Alpha A7 IV Full-Frame Mirrorless Camera', 'brand' => 'sony', 'sub' => 0, 'price' => 265000, 'sale' => 249999, 'stock' => 8, 'specs' => ['Sensor' => '33MP Full-Frame Exmor R CMOS BSI Sensor', 'Video' => '4K 60p 10-bit 4:2:2 video with S-Cinetone', 'AF' => 'Real-time Eye AF for humans, animals, birds', 'Stabilization' => '5-axis optical in-body image stabilization']],
                    ['title' => 'Canon EOS R6 Mark II Mirrorless Camera Body', 'brand' => 'canon', 'sub' => 0, 'price' => 255000, 'sale' => 239999, 'stock' => 7, 'specs' => ['Sensor' => '24.2MP full-frame CMOS sensor', 'Burst' => 'Up to 40 fps electronic shutter shooting', 'Video' => '6K oversampled uncropped 4K 60p video', 'AF' => 'Dual Pixel CMOS AF II with AI deep learning']],
                    ['title' => 'Nikon Z8 Full-Frame Professional Mirrorless', 'brand' => 'nikon', 'sub' => 0, 'price' => 415000, 'sale' => 395000, 'stock' => 4, 'specs' => ['Sensor' => '45.7MP stacked BSI CMOS sensor', 'Shutter' => 'Electronic shutter only with blackout-free EVF', 'Video' => '8.3K 60p N-RAW internal recording', 'Body' => 'Fully weather-sealed pro magnesium alloy chassis']],
                    ['title' => 'DJI Mini 4 Pro Drone with RC 2 Controller', 'brand' => 'dji', 'sub' => 1, 'price' => 118000, 'sale' => 109999, 'stock' => 10, 'specs' => ['Weight' => 'Under 249 grams regulation-friendly', 'Video' => '4K 60fps HDR True Vertical Shooting', 'Sensing' => 'Omnidirectional obstacle sensing with APAS 5.0', 'Transmission' => 'DJI O4 video transmission up to 20 km']],
                    ['title' => 'DJI Osmo Action 4 Standard Combo 4K Camera', 'brand' => 'dji', 'sub' => 1, 'price' => 39500, 'sale' => 36999, 'stock' => 15, 'specs' => ['Sensor' => '1/1.3-inch large image sensor for low-light mastery', 'Color' => '10-bit & D-Log M color performance', 'Waterproof' => 'Native waterproof down to 18 meters without case', 'Stabilization' => 'RockSteady 3.0+ and 360-degree HorizonSteady']],
                    ['title' => 'Canon RF 24-70mm f/2.8L IS USM Lens', 'brand' => 'canon', 'sub' => 2, 'price' => 245000, 'sale' => null, 'stock' => 5, 'specs' => ['Aperture' => 'Bright constant f/2.8 maximum aperture', 'Stabilization' => 'Optical image stabilizer with up to 5 stops', 'Optics' => '3 Aspherical and 3 UD elements with ASC coating', 'Motor' => 'Nano USM motor for fast, smooth and silent AF']],
                    ['title' => 'Sony FE 70-200mm f/2.8 GM OSS II Lens', 'brand' => 'sony', 'sub' => 2, 'price' => 295000, 'sale' => null, 'stock' => 5, 'specs' => ['Weight' => '29% lighter than predecessor (1045 grams)', 'Aperture' => 'Constant f/2.8 with 11-blade circular aperture', 'Motors' => '4 XD Linear Motors for 4x faster autofocus', 'Optics' => 'XA, Super ED and ED elements for extreme corner sharpness']],
                    ['title' => 'DJI RS 3 Pro Handheld Gimbal Stabilizer', 'brand' => 'dji', 'sub' => 3, 'price' => 95000, 'sale' => 88000, 'stock' => 8, 'specs' => ['Payload' => 'Tested 4.5 kg payload for cinema cameras', 'Arms' => 'Extended carbon fiber axis arms', 'Locks' => 'Automated axis locks for rapid balancing', 'LiDAR' => 'Supports LiDAR focusing system for manual lenses']],
                    ['title' => 'DJI Osmo Mobile 6 Smartphone Gimbal', 'brand' => 'dji', 'sub' => 3, 'price' => 17500, 'sale' => 15999, 'stock' => 25, 'specs' => ['Stabilization' => '3-axis smartphone stabilization', 'Extension' => 'Built-in 215mm extension rod for high/low angles', 'Tracking' => 'ActiveTrack 6.0 keeps subjects centered', 'Display' => 'Status panel displays battery and gimbal mode']],
                    ['title' => 'Sony Alpha A6700 APS-C Mirrorless Camera', 'brand' => 'sony', 'sub' => 0, 'price' => 158000, 'sale' => 148000, 'stock' => 11, 'specs' => ['Sensor' => '26MP APS-C Exmor R BSI CMOS Sensor', 'AI' => 'Dedicated AI processing unit for subject recognition', 'Video' => '4K 120p and 4K 60p oversampled from 6K', 'Body' => 'Comfortable grip with dust and moisture resistance']],
                ]
            ],
            // 14. Smart Home & IoT
            [
                'cat_slug' => 'smart-home-iot',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Philips Hue White & Color Ambiance Starter Kit', 'brand' => 'philips', 'sub' => 0, 'price' => 18500, 'sale' => 16999, 'stock' => 15, 'specs' => ['Bulbs' => '3x E27 16-million color LED bulbs', 'Bridge' => 'Hue Bridge included for whole-home control', 'Control' => 'Compatible with Alexa, Apple HomeKit, Google Home', 'Lumens' => '1100 lumens per bulb (75W equivalent)']],
                    ['title' => 'Xiaomi Smart Camera C400 2.5K Ultra-Clear', 'brand' => 'xiaomi', 'sub' => 1, 'price' => 4800, 'sale' => 4299, 'stock' => 35, 'specs' => ['Resolution' => '4MP 2.5K (2560 x 1440) high resolution', 'Night Vision' => 'Infrared night vision with no visible red glow', 'Audio' => 'Two-way voice calling with smart noise reduction', 'Tracking' => 'AI human detection and tracking']],
                    ['title' => 'TP-Link Tapo P110 Mini Smart Energy Monitoring Plug', 'brand' => 'tp-link', 'sub' => 2, 'price' => 1650, 'sale' => 1450, 'stock' => 60, 'specs' => ['Energy' => 'Real-time energy consumption monitoring and breakdown', 'Control' => 'Remote control from anywhere with Tapo app', 'Schedule' => 'Schedule and timer to automate appliances', 'Voice' => 'Hands-free voice control with Alexa & Google']],
                    ['title' => 'Google Nest Doorbell (Battery) Smart Video', 'brand' => 'google', 'sub' => 3, 'price' => 21000, 'sale' => 18999, 'stock' => 14, 'specs' => ['Camera' => 'HD video with HDR and night vision', 'Intelligence' => 'Differentiates between people, packages, animals, vehicles', 'Aspect' => '3:4 vertical field of view to see head-to-toe', 'Power' => 'Rechargeable built-in battery or wire to existing chime']],
                    ['title' => 'TP-Link Tapo C320WS Outdoor Security Camera', 'brand' => 'tp-link', 'sub' => 1, 'price' => 5800, 'sale' => 5200, 'stock' => 28, 'specs' => ['Resolution' => '2K QHD (2560x1440) crystal clear video', 'Night' => 'Full-color night vision with F1.6 starlight sensor', 'Weather' => 'IP66 weatherproof withstands rain and harsh dust', 'Alarm' => 'Custom sound and light alarm triggers']],
                    ['title' => 'Xiaomi Smart Air Purifier 4 with True HEPA', 'brand' => 'xiaomi', 'sub' => 0, 'price' => 21500, 'sale' => 19999, 'stock' => 18, 'specs' => ['CADR' => 'Up to 400 m³/h particle CADR cleans 48m² room', 'Filter' => 'Three-in-one filtration removes 99.97% 0.3μm particles', 'Sensors' => 'High-precision laser sensors detect PM2.5', 'Display' => 'OLED touch display showing air quality indicators']],
                    ['title' => 'TP-Link Tapo L530E Smart Multicolour Light Bulb', 'brand' => 'tp-link', 'sub' => 0, 'price' => 1450, 'sale' => 1250, 'stock' => 70, 'specs' => ['Color' => '16 million colors with 1%-100% dimming range', 'Hub-Free' => 'Connects directly to secure home WiFi network', 'Scenes' => 'Preset favorite lighting atmospheres for movies and reading', 'Power' => '8.7W LED equivalent to 60W incandescent']],
                    ['title' => 'Xiaomi Smart Door Lock E10 Fingerprint', 'brand' => 'xiaomi', 'sub' => 3, 'price' => 16500, 'sale' => 14999, 'stock' => 12, 'specs' => ['Unlock' => 'Fingerprint, password, NFC, Bluetooth, emergency key', 'Sensor' => 'High-precision semiconductor fingerprint scanner', 'Cylinder' => 'Class C straight ferrule lock cylinder for anti-pick security', 'Alert' => 'Integrated doorbell with tamper alarm notification']],
                    ['title' => 'Philips Hue Bridge Smart Light Hub', 'brand' => 'philips', 'sub' => 0, 'price' => 7200, 'sale' => 6499, 'stock' => 20, 'specs' => ['Capacity' => 'Connect and control up to 50 lights and 12 accessories', 'Automations' => 'Create timers, routines and sunrise/sunset schedules', 'Matter' => 'Matter-ready update for universal smart home ecosystem', 'Zigbee' => 'Ultra-reliable Zigbee mesh protocol']],
                    ['title' => 'Google Nest Hub 2nd Gen Smart Display', 'brand' => 'google', 'sub' => 0, 'price' => 11500, 'sale' => 9999, 'stock' => 22, 'specs' => ['Screen' => '7-inch touchscreen smart home command center', 'Speaker' => 'Enhanced speaker with 50% more bass', 'Sensing' => 'Soli radar sleep sensing technology', 'Control' => 'Control thousands of compatible smart lights and cameras']],
                ]
            ],
            // 15. Televisions & Video
            [
                'cat_slug' => 'televisions-video',
                'has_variants' => false,
                'items' => [
                    ['title' => 'LG C3 65-inch 4K OLED evo Smart TV', 'brand' => 'lg', 'sub' => 0, 'price' => 235000, 'sale' => 219999, 'stock' => 6, 'specs' => ['Screen' => '65" 4K OLED evo with Brightness Booster', 'Processor' => 'α9 AI Processor Gen6 with 4K AI Upscaling', 'Gaming' => '4x HDMI 2.1, 120Hz, VRR, G-SYNC, FreeSync', 'OS' => 'webOS 23 with Magic Remote']],
                    ['title' => 'Samsung 65-inch S90C OLED 4K Smart TV', 'brand' => 'samsung', 'sub' => 0, 'price' => 225000, 'sale' => 209999, 'stock' => 7, 'specs' => ['Display' => '65" Quantum HDR OLED with Pantone validation', 'Processor' => 'Neural Quantum Processor 4K', 'Sound' => 'Dolby Atmos and Object Tracking Sound Lite', 'Refresh' => 'Motion Xcelerator Turbo Pro 144Hz for PC gaming']],
                    ['title' => 'Sony BRAVIA XR A80L 55-inch 4K OLED TV', 'brand' => 'sony', 'sub' => 0, 'price' => 195000, 'sale' => 185000, 'stock' => 8, 'specs' => ['Processor' => 'Cognitive Processor XR understands human hearing & vision', 'Audio' => 'Acoustic Surface Audio+ turns entire screen into speaker', 'Gaming' => 'Perfect for PlayStation 5 Auto HDR Tone Mapping', 'Platform' => 'Google TV with hands-free voice search']],
                    ['title' => 'Xiaomi TV A Pro 55-inch 4K UHD Smart Google TV', 'brand' => 'xiaomi', 'sub' => 1, 'price' => 54000, 'sale' => 49999, 'stock' => 20, 'specs' => ['Display' => '55" 4K UHD 3840x2160 with Dolby Vision', 'Bezel' => 'Metallic frame with premium bezel-less design', 'Audio' => '2x 12W speakers with Dolby Audio & DTS-X', 'OS' => 'Google TV with Google Assistant & Chromecast built-in']],
                    ['title' => 'Samsung 55-inch Q60C QLED 4K Smart TV', 'brand' => 'samsung', 'sub' => 1, 'price' => 88000, 'sale' => 82000, 'stock' => 14, 'specs' => ['Color' => '100% Color Volume with Quantum Dot', 'Backlight' => 'Dual LED dedicated warm and cool backlight', 'Design' => 'AirSlim design blends into wall seamlessly', 'Hub' => 'Built-in SmartThings Hub for home automation']],
                    ['title' => 'Apple TV 4K 128GB Wi-Fi + Ethernet (3rd Gen)', 'brand' => 'apple', 'sub' => 3, 'price' => 23500, 'sale' => 21999, 'stock' => 25, 'specs' => ['Processor' => 'A15 Bionic chip for blazing-fast navigation & games', 'Video' => '4K Dolby Vision, HDR10+, and Dolby Atmos audio', 'Remote' => 'Siri Remote with touch-enabled clickpad (USB-C)', 'Networking' => 'Gigabit Ethernet, Wi-Fi 6, and Thread networking']],
                    ['title' => 'Anker Nebula Capsule 3 Laser Mini Projector', 'brand' => 'anker', 'sub' => 2, 'price' => 85000, 'sale' => 79999, 'stock' => 9, 'specs' => ['Light' => 'Laser-bright 300 ANSI Lumens in 1080p FHD', 'Size' => 'Projects up to 120 inches anywhere in home or camp', 'Battery' => 'Built-in 52Wh battery delivers 2.5 hours playtime', 'Audio' => '8W Dolby Digital speaker fills room']],
                    ['title' => 'Google Chromecast with Google TV 4K Snow', 'brand' => 'google', 'sub' => 3, 'price' => 6500, 'sale' => 5750, 'stock' => 45, 'specs' => ['Resolution' => 'Up to 4K HDR at 60 fps with Dolby Vision & HDR10+', 'Interface' => 'Google TV groups content from all subscription apps', 'Remote' => 'Voice remote with dedicated Google Assistant button', 'Connectivity' => 'Wi-Fi 802.11ac and Bluetooth']],
                    ['title' => 'LG 50-inch UR7500 4K Smart TV with webOS', 'brand' => 'lg', 'sub' => 1, 'price' => 56000, 'sale' => 51999, 'stock' => 16, 'specs' => ['Screen' => '50" Real 4K display with HDR10 Pro', 'Processor' => 'α5 AI Processor 4K Gen6', 'Audio' => 'AI Sound with virtual 5.1 up-mix', 'Smart' => 'webOS 23 with Apple AirPlay 2 and HomeKit']],
                    ['title' => 'BenQ TK700STi 4K HDR Short Throw Gaming Projector', 'brand' => 'dell', 'sub' => 2, 'price' => 175000, 'sale' => 165000, 'stock' => 5, 'specs' => ['Resolution' => 'True 4K UHD 8.3 million pixels', 'Throw' => 'Short throw projects 100" screen from just 6.5 feet', 'Gaming' => 'World-leading low input lag 16ms at 4K 60Hz', 'Brightness' => '3000 ANSI Lumens for bright-room viewing']],
                ]
            ],
            // 16. Gaming Consoles & Gear
            [
                'cat_slug' => 'gaming-consoles-accessories',
                'has_variants' => false,
                'items' => [
                    ['title' => 'Sony PlayStation 5 Slim Disc Edition Console', 'brand' => 'sony', 'sub' => 0, 'price' => 69000, 'sale' => 64999, 'stock' => 14, 'specs' => ['Storage' => '1TB High-speed NVMe PCIe 4.0 SSD', 'Drive' => 'Ultra HD Blu-ray disc drive', 'Graphics' => 'Ray tracing support up to 120 fps with 4K output', 'Audio' => 'Tempest 3D AudioTech immersion']],
                    ['title' => 'Microsoft Xbox Series X 1TB Console', 'brand' => 'asus', 'sub' => 1, 'price' => 66000, 'sale' => 62500, 'stock' => 10, 'specs' => ['Power' => '12 Teraflops of raw graphic processing power', 'Architecture' => 'Xbox Velocity Architecture with 1TB custom SSD', 'Frame Rates' => 'True 4K gaming at up to 120 frames per second', 'Resume' => 'Quick Resume seamlessly switches between games']],
                    ['title' => 'Nintendo Switch OLED Model with White Joy-Con', 'brand' => 'sony', 'sub' => 2, 'price' => 38000, 'sale' => 34999, 'stock' => 20, 'specs' => ['Screen' => 'Vibrant 7-inch OLED screen with deep blacks', 'Kickstand' => 'Wide adjustable stand for comfortable tabletop mode', 'Dock' => 'Wired LAN port built into the TV dock', 'Storage' => '64GB internal storage with enhanced audio']],
                    ['title' => 'Sony PlayStation 5 DualSense Wireless Controller', 'brand' => 'sony', 'sub' => 3, 'price' => 8500, 'sale' => 7600, 'stock' => 40, 'specs' => ['Feedback' => 'Haptic feedback brings in-game actions alive', 'Triggers' => 'Dynamic adaptive triggers with variable tension', 'Mic' => 'Built-in microphone and 3.5mm headset jack', 'Battery' => 'Rechargeable built-in battery via USB Type-C']],
                    ['title' => 'Xbox Elite Wireless Controller Series 2 Black', 'brand' => 'asus', 'sub' => 3, 'price' => 21500, 'sale' => 19999, 'stock' => 12, 'specs' => ['Customization' => 'Adjustable-tension thumbsticks & interchangeable paddles', 'Triggers' => 'Shorter hair trigger locks for rapid fire', 'Battery' => 'Up to 40 hours of rechargeable battery life', 'Profiles' => 'Save up to 3 custom profiles directly on controller']],
                    ['title' => 'Logitech G29 Driving Force Racing Wheel & Pedals', 'brand' => 'logitech', 'sub' => 3, 'price' => 36000, 'sale' => 33500, 'stock' => 9, 'specs' => ['Force' => 'Dual-motor force feedback realistically simulates tires', 'Pedals' => 'Nonlinear brake pedal mimics pressure-sensitive system', 'Rotation' => '900-degree lock-to-lock steering rotation', 'Grip' => 'Hand-stitched genuine automotive leather']],
                    ['title' => 'Sony PlayStation VR2 Virtual Reality Headset', 'brand' => 'sony', 'sub' => 0, 'price' => 72000, 'sale' => 67000, 'stock' => 7, 'specs' => ['Display' => 'Dual 2000 x 2040 OLED displays with HDR up to 120Hz', 'Eye Tracking' => 'Intelligent eye tracking with foveated rendering', 'Headset' => 'Headset feedback subtle vibrations for realism', 'Controllers' => 'PlayStation VR2 Sense controllers with finger touch']],
                    ['title' => 'Sony DualSense Edge Wireless Controller', 'brand' => 'sony', 'sub' => 3, 'price' => 24500, 'sale' => 22999, 'stock' => 11, 'specs' => ['Modularity' => 'Replaceable stick modules and changeable stick caps', 'Buttons' => 'Mappable back buttons and custom button mapping profiles', 'Stops' => 'Adjustable trigger travel distance stops', 'Case' => 'Carrying case with braided USB-C cable & lockable connector']],
                    ['title' => 'Razer Wolverine V2 Pro Wireless Controller for PS5', 'brand' => 'razer', 'sub' => 3, 'price' => 29500, 'sale' => 26999, 'stock' => 8, 'specs' => ['Wireless' => 'Razer HyperSpeed Wireless 2.4GHz ultra-fast connection', 'Switches' => 'Razer Mecha-Tactile Action Buttons with 3M click lifecycle', 'D-Pad' => '8-way microswitch D-pad for precise directional input', 'Custom' => '6 additional remappable triggers and bumpers']],
                    ['title' => 'Nintendo Switch Pro Controller Black', 'brand' => 'sony', 'sub' => 2, 'price' => 7800, 'sale' => 6999, 'stock' => 25, 'specs' => ['Grip' => 'Premium ergonomic grip for extended play sessions', 'Sensors' => 'Motion controls and HD rumble built-in', 'NFC' => 'Built-in amiibo functionality on NFC touchpoint', 'Battery' => 'Up to 40 hours battery life on single charge']],
                ]
            ],
            // 17. Men's Formal Wear
            [
                'cat_slug' => 'mens-formal-wear',
                'has_variants' => true,
                'variant_type' => 'clothing',
                'items' => [
                    ['title' => 'Zara Man Classic Navy Slim Fit Suit Blazer', 'brand' => 'zara', 'sub' => 0, 'price' => 14500, 'sale' => 12999, 'stock' => 20, 'specs' => ['Material' => '68% Polyester, 28% Viscose, 4% Elastane', 'Fit' => 'Slim Fit tailored silhouette', 'Lapel' => 'Notch lapel with buttonhole', 'Pockets' => 'Flap hip pockets and interior chest pocket']],
                    ['title' => 'Zara Tailored Charcoal Grey Dress Trousers', 'brand' => 'zara', 'sub' => 2, 'price' => 5800, 'sale' => 4999, 'stock' => 28, 'specs' => ['Fabric' => 'Breathable stretch wool-blend', 'Closure' => 'Concealed hook-and-eye with zip fly', 'Crease' => 'Sharp pressed front and back center crease', 'Wash Care' => 'Dry clean recommended']],
                    ['title' => 'H&M Premium Selection White Egyptian Cotton Shirt', 'brand' => 'hm', 'sub' => 1, 'price' => 3999, 'sale' => 3499, 'stock' => 35, 'specs' => ['Fabric' => '100% Long-staple Egyptian cotton', 'Collar' => 'Structured spread collar with collar stays', 'Weave' => 'Fine poplin weave with subtle sheen', 'Cuffs' => 'Adjustable button barrel cuffs']],
                    ['title' => 'Zara Man Royal Black Two-Button Tuxedo Blazer', 'brand' => 'zara', 'sub' => 0, 'price' => 16500, 'sale' => 14999, 'stock' => 15, 'specs' => ['Lapel' => 'Satin peak lapel for formal galas', 'Buttons' => 'Satin covered front buttons', 'Lining' => 'Fully lined with silky jacquard fabric', 'Fit' => 'Modern tailored evening fit']],
                    ['title' => 'H&M Easy-Iron Slim Fit Light Blue Formal Shirt', 'brand' => 'hm', 'sub' => 1, 'price' => 2450, 'sale' => 2199, 'stock' => 40, 'specs' => ['Fabric' => '65% Polyester, 35% Cotton easy-iron blend', 'Collar' => 'Turn-down collar with back yoke', 'Fit' => 'Slim fit with darted back seams', 'Color' => 'Crisp pastel light blue']],
                    ['title' => 'Levi\'s Men\'s Executive Stretch Chino Trousers', 'brand' => 'levis', 'sub' => 2, 'price' => 4800, 'sale' => 4200, 'stock' => 30, 'specs' => ['Fabric' => '98% Cotton, 2% Elastane twill', 'Rise' => 'Mid rise with straight leg cut', 'Pockets' => 'Welt back pockets with button closure', 'Comfort' => 'All-day comfort flex waistband']],
                    ['title' => 'Zara 100% Silk Jacquard Formal Necktie & Square', 'brand' => 'zara', 'sub' => 3, 'price' => 2850, 'sale' => 2499, 'stock' => 45, 'specs' => ['Material' => '100% Pure mulberry silk', 'Pattern' => 'Micro geometric diamond weave', 'Width' => 'Contemporary 7.5cm blade width', 'Set' => 'Includes matching pocket square']],
                    ['title' => 'H&M Slim Fit Structured Blazer in Dark Blue', 'brand' => 'hm', 'sub' => 0, 'price' => 9500, 'sale' => 8499, 'stock' => 22, 'specs' => ['Fabric' => 'Textured birdseye woven fabric', 'Vents' => 'Double back vents for ease of movement', 'Buttons' => 'Two-button front fastening', 'Care' => 'Dry clean only']],
                    ['title' => 'Zara Man Herringbone Pattern Formal Shirt', 'brand' => 'zara', 'sub' => 1, 'price' => 4200, 'sale' => 3700, 'stock' => 32, 'specs' => ['Weave' => 'Subtle tonal herringbone weave', 'Material' => '100% Mercerized cotton', 'Collar' => 'Cutaway collar suitable for wide tie knots', 'Fit' => 'Regular tailored fit']],
                    ['title' => 'Fossil Steel & Onyx Cufflinks and Tie Clip Set', 'brand' => 'fossil', 'sub' => 3, 'price' => 4500, 'sale' => 3999, 'stock' => 25, 'specs' => ['Material' => 'Solid 316L stainless steel', 'Inlay' => 'Polished black natural onyx stone', 'Closure' => 'Bullet-back toggle clasp', 'Packaging' => 'Luxe velvet presentation gift box']],
                ]
            ],
            // 18. Men's Casual Wear
            [
                'cat_slug' => 'mens-casual-wear',
                'has_variants' => true,
                'variant_type' => 'clothing',
                'items' => [
                    ['title' => 'Levi\'s 501 Original Fit Men\'s Denim Jeans', 'brand' => 'levis', 'sub' => 2, 'price' => 6500, 'sale' => 5800, 'stock' => 40, 'specs' => ['Style' => 'Iconic straight leg with signature button fly', 'Denim' => '100% Heavyweight non-stretch cotton denim 14oz', 'Wash' => 'Stonewashed medium indigo blue', 'Pockets' => 'Classic 5-pocket styling with copper rivets']],
                    ['title' => 'Nike Sportswear Club Fleece Pullover Hoodie', 'brand' => 'nike', 'sub' => 3, 'price' => 6200, 'sale' => 5499, 'stock' => 35, 'specs' => ['Fleece' => 'Brushed-back fleece is soft and smooth against skin', 'Hood' => 'Drawstring adjustable jersey-lined hood', 'Pouch' => 'Kangaroo hand pocket in front', 'Branding' => 'Embroidered Nike Futura logo on chest']],
                    ['title' => 'Puma Essentials Pique Polo Shirt Classic', 'brand' => 'puma', 'sub' => 1, 'price' => 2800, 'sale' => 2399, 'stock' => 45, 'specs' => ['Material' => '96% Cotton, 4% Elastane breathable pique', 'Collar' => 'Ribbed collar with two-button placket', 'Fit' => 'Regular comfortable fit', 'Logo' => 'Puma No. 1 rubber print logo on chest']],
                    ['title' => 'Adidas Originals Trefoil Heavyweight T-Shirt', 'brand' => 'adidas', 'sub' => 0, 'price' => 3200, 'sale' => 2750, 'stock' => 50, 'specs' => ['Cotton' => '100% Single jersey organic cotton 210gsm', 'Neck' => 'Ribbed crewneck holds shape after washing', 'Graphic' => 'Classic contrast Trefoil rubber print', 'Fit' => 'Standard streetwear relaxed fit']],
                    ['title' => 'Levi\'s Barstow Western Denim Snap Shirt', 'brand' => 'levis', 'sub' => 1, 'price' => 5200, 'sale' => 4600, 'stock' => 30, 'specs' => ['Details' => 'Original western yoke front and back', 'Snaps' => 'Pearlized snap button closures down front and cuffs', 'Pockets' => 'Double chest snap flap pockets with Red Tab', 'Fabric' => '100% Durable cotton denim']],
                    ['title' => 'H&M Regular Fit Heavyweight Cotton T-Shirt', 'brand' => 'hm', 'sub' => 0, 'price' => 1450, 'sale' => 1250, 'stock' => 60, 'specs' => ['Fabric' => '100% Heavyweight cotton jersey 240gsm', 'Texture' => 'Clean dry-hand feel vintage aesthetic', 'Fit' => 'Boxy casual regular cut', 'Neck' => 'Durable 2.5cm ribbed collar']],
                    ['title' => 'Zara Relaxed Fit Acid Wash Denim Jacket', 'brand' => 'zara', 'sub' => 2, 'price' => 7800, 'sale' => 6999, 'stock' => 22, 'specs' => ['Style' => 'Trucker jacket silhouette with dropped shoulders', 'Wash' => 'Retro 90s vintage acid wash treatment', 'Closure' => 'Metal button front fastening and cuffs', 'Pockets' => 'Flap chest pockets and side welt pockets']],
                    ['title' => 'Nike Dri-FIT Legend Short Sleeve Training Tee', 'brand' => 'nike', 'sub' => 0, 'price' => 2450, 'sale' => 2100, 'stock' => 55, 'specs' => ['Technology' => 'Dri-FIT technology wicks sweat for quick drying', 'Odor' => 'Anti-odor finish keeps garment fresher', 'Material' => '100% Lightweight polyester jersey', 'Feel' => 'Soft poly-cotton feel with athletic stretch']],
                    ['title' => 'Puma Evostripe Full-Zip Men\'s Track Jacket', 'brand' => 'puma', 'sub' => 3, 'price' => 5400, 'sale' => 4799, 'stock' => 28, 'specs' => ['Cut' => 'Evostripe articulated cutline for maximum flexibility', 'Fabric' => '77% Cotton, 23% Recycled polyester double knit', 'dryCELL' => 'Moisture-wicking dryCELL technology', 'Storage' => 'Concealed zip pockets for secure storage']],
                    ['title' => 'Levi\'s 511 Slim Fit Stretch Twill Chino Pants', 'brand' => 'levis', 'sub' => 2, 'price' => 5800, 'sale' => 5100, 'stock' => 32, 'specs' => ['Fit' => 'Modern slim with room to move', 'Stretch' => 'Levi\'s Flex advanced stretch technology', 'Rise' => 'Sits below waist, slim from hip to ankle', 'Versatility' => 'Perfect alternative to traditional blue jeans']],
                ]
            ],
            // 19. Men's Traditional Wear
            [
                'cat_slug' => 'mens-traditional-wear',
                'has_variants' => true,
                'variant_type' => 'clothing',
                'items' => [
                    ['title' => 'Aarong Men\'s Hand-Embroidered Silk Panjabi', 'brand' => 'apex', 'sub' => 0, 'price' => 7800, 'sale' => 6999, 'stock' => 25, 'specs' => ['Fabric' => 'Pure Endi Silk with delicate embroidery on placket', 'Collar' => 'Structured band collar with metal snap buttons', 'Length' => 'Calf length traditional cut with side slits', 'Occasion' => 'Eid, Wedding, and Festive celebrations']],
                    ['title' => 'Manyavar Royal Jacquard Silk Kurta Pajama Set', 'brand' => 'bata', 'sub' => 1, 'price' => 9500, 'sale' => 8499, 'stock' => 18, 'specs' => ['Set' => 'Includes self-design kurta and matching churidar pajama', 'Fabric' => 'Art silk jacquard with floral self-weave', 'Pockets' => 'Two deep side pockets', 'Care' => 'Gentle dry clean only']],
                    ['title' => 'Lubnan Exclusive Platinum Embroidered Panjabi', 'brand' => 'apex', 'sub' => 0, 'price' => 8900, 'sale' => 7900, 'stock' => 16, 'specs' => ['Fabric' => '100% Giza combed Egyptian cotton with satin finish', 'Work' => 'Fine metallic zardosi embroidery along neckline', 'Fit' => 'Semi-fitted festive silhouette', 'Buttons' => 'Enamel and brass luxury buttons']],
                    ['title' => 'Fabindia Fine Linen Long Kurta White', 'brand' => 'bata', 'sub' => 1, 'price' => 4500, 'sale' => 3999, 'stock' => 30, 'specs' => ['Fabric' => '100% Pure woven linen keeps cool in summer', 'Sleeves' => 'Full sleeves with roll-up tab styling', 'Cut' => 'Straight relaxed hem with side vents', 'Origin' => 'Handcrafted by artisan weavers']],
                    ['title' => 'Manyavar Brocade Silk Nehru Koti Waistcoat', 'brand' => 'bata', 'sub' => 3, 'price' => 5200, 'sale' => 4600, 'stock' => 22, 'specs' => ['Fabric' => 'Woven Banarasi brocade silk blend', 'Neckline' => 'Mandarin stand collar with button-front placket', 'Buttons' => 'Carved antique metallic buttons', 'Styling' => 'Layers elegantly over plain kurtas and shirts']],
                    ['title' => 'Aarong Tangail Handloom Cotton Lungi Green', 'brand' => 'apex', 'sub' => 2, 'price' => 1450, 'sale' => 1250, 'stock' => 40, 'specs' => ['Fabric' => '100% Pure Tangail handloom combed cotton', 'Weave' => 'Fine 80 count soft breathable weave', 'Border' => 'Traditional woven zari temple border', 'Length' => 'Standard 2.25 meters stitched tube']],
                    ['title' => 'Cats Eye Festive Embroidered Black Panjabi', 'brand' => 'apex', 'sub' => 0, 'price' => 4800, 'sale' => 4200, 'stock' => 28, 'specs' => ['Color' => 'Deep midnight black with tonal threadwork', 'Fabric' => 'Cotton rich blend with comfort stretch', 'Details' => 'Geometric motif embroidery across chest', 'Care' => 'Machine wash cold inside out']],
                    ['title' => 'Anjan\'s Handloom Khadi Cotton Kurta Mustard', 'brand' => 'bata', 'sub' => 1, 'price' => 2850, 'sale' => 2499, 'stock' => 35, 'specs' => ['Fabric' => 'Natural handspun khadi cotton', 'Texture' => 'Authentic earthy slub texture', 'Buttons' => 'Natural coconut shell buttons', 'Season' => 'Year-round breathable everyday wear']],
                    ['title' => 'Aarong Premium Jacquard Festive Koti Navy', 'brand' => 'apex', 'sub' => 3, 'price' => 4200, 'sale' => 3700, 'stock' => 24, 'specs' => ['Design' => 'Self-patterned floral jacquard weave', 'Pockets' => 'Two welt pockets and chest pocket for handkerchief', 'Lining' => 'Fully lined with smooth satin interior', 'Closure' => 'Five front brass button fastening']],
                    ['title' => 'Apex Handcrafted Leather Nagra Khussa Shoes', 'brand' => 'apex', 'sub' => 0, 'price' => 3990, 'sale' => 3490, 'stock' => 30, 'specs' => ['Upper' => 'Supple genuine crust leather with ethnic threadwork', 'Sole' => 'Flexible handcrafted leather sole with rubber heel tip', 'Insole' => 'Cushioned leather footbed for wedding comfort', 'Style' => 'Curved traditional toe nagra silhouette']],
                ]
            ],
            // 20. Women's Traditional Wear
            [
                'cat_slug' => 'womens-traditional-wear',
                'has_variants' => true,
                'variant_type' => 'color_only',
                'items' => [
                    ['title' => 'Dhakai Muslin Traditional Jamdani Saree', 'brand' => 'apex', 'sub' => 0, 'price' => 14500, 'sale' => 12999, 'stock' => 15, 'specs' => ['Fabric' => '100% Fine count cotton muslin', 'Weave' => 'Handcrafted authentic supplementary weft Jamdani motifs', 'Aanchal' => 'Rich floral geometric ornamental pallu', 'Blouse' => 'Includes 80cm unstitched running blouse piece']],
                    ['title' => 'Benarasi Pure Katan Silk Saree Maroon Gold', 'brand' => 'bata', 'sub' => 0, 'price' => 18500, 'sale' => 16500, 'stock' => 12, 'specs' => ['Fabric' => 'Pure Katan silk with rich body luster', 'Zari' => 'Heavy golden metallic zari jaal weave throughout', 'Border' => 'Broad regal temple motif zari border', 'Occasion' => 'Bridal wear, receptions, and major festivals']],
                    ['title' => 'Manyavar Mohey Crimson Velvet Bridal Lehenga', 'brand' => 'bata', 'sub' => 3, 'price' => 38000, 'sale' => 34500, 'stock' => 6, 'specs' => ['Set' => 'Semi-stitched lehenga, unstitched choli, net dupatta', 'Fabric' => 'Plush micro velvet with heavy cancan underlayer', 'Work' => 'Intricate dori, sequins, and zardozi threadwork', 'Flare' => 'Grand 4.2-meter circular flare']],
                    ['title' => 'Aarong Hand-Embroidered Silk Salwar Kameez', 'brand' => 'apex', 'sub' => 1, 'price' => 8500, 'sale' => 7650, 'stock' => 20, 'specs' => ['Fabric' => 'Pure Silk kameez with georgette dupatta & cotton pants', 'Work' => 'Authentic Nakshi Kantha hand-needle embroidery', 'Neckline' => 'Boat neck with embroidered yoke', 'Length' => 'Calf length 44 inches']],
                    ['title' => 'Biba Floral Print Anarkali Three-Piece Suit', 'brand' => 'bata', 'sub' => 1, 'price' => 6800, 'sale' => 5999, 'stock' => 22, 'specs' => ['Silhouette' => 'Floor length flared Anarkali silhouette', 'Material' => '100% Viscose rayon with cotton lining', 'Dupatta' => 'Chiffon printed dupatta with gota patti borders', 'Sleeves' => 'Three-quarter sleeves with piping details']],
                    ['title' => 'W for Woman Designer Embroidered Festive Kurti', 'brand' => 'hm', 'sub' => 2, 'price' => 3200, 'sale' => 2799, 'stock' => 35, 'specs' => ['Fabric' => 'Chanderi silk blend with soft lining', 'Details' => 'Mirror-work foil print along neck and hemline', 'Cut' => 'A-line contemporary cut with side slits', 'Pairing' => 'Pairs effortlessly with churidars or palazzos']],
                    ['title' => 'Aarong Half Silk Dual-Tone Festive Saree', 'brand' => 'apex', 'sub' => 0, 'price' => 5400, 'sale' => 4800, 'stock' => 25, 'specs' => ['Fabric' => 'Lightweight half silk with dual-tone sheen', 'Zari' => 'Delicate contrast golden border and striped pallu', 'Drape' => 'Soft flowing drape easy to carry all day', 'Care' => 'Dry clean only']],
                    ['title' => 'Fabindia Tussar Silk Saree Hand Block Printed', 'brand' => 'bata', 'sub' => 0, 'price' => 9800, 'sale' => 8800, 'stock' => 14, 'specs' => ['Fabric' => 'Pure wild Tussar silk certified Silk Mark', 'Print' => 'Natural dye traditional wooden block prints', 'Texture' => 'Rich porous textured handfeel', 'Color' => 'Warm mustard beige and terracotta']],
                    ['title' => 'Libas Georgette Embroidered Kurta & Palazzo Set', 'brand' => 'zara', 'sub' => 1, 'price' => 4200, 'sale' => 3650, 'stock' => 28, 'specs' => ['Material' => 'Flowy poly-georgette with full inner lining', 'Bottom' => 'Matching flared wide-leg palazzo pants with elastic waist', 'Work' => 'Resham thread and sequin embroidery across front', 'Wash' => 'Gentle hand wash cold']],
                    ['title' => 'Aarong Embroidered Cotton Kurti Tunic Olive', 'brand' => 'apex', 'sub' => 2, 'price' => 2650, 'sale' => 2300, 'stock' => 40, 'specs' => ['Fabric' => '100% Combed handloom cotton', 'Work' => 'Ethnic floral embroidery on chest panel', 'Neck' => 'Mandarin collar with subtle keyhole slit', 'Fit' => 'Comfortable daily wear regular fit']],
                ]
            ],
            // 21. Women's Western Wear
            [
                'cat_slug' => 'womens-western-wear',
                'has_variants' => true,
                'variant_type' => 'clothing',
                'items' => [
                    ['title' => 'Zara Floral Print Belted Midi Shirt Dress', 'brand' => 'zara', 'sub' => 0, 'price' => 6800, 'sale' => 5999, 'stock' => 25, 'specs' => ['Material' => '100% Flowy viscose fabric', 'Length' => 'Midi length with side seam slit', 'Belt' => 'Matching self-fabric belt with covered buckle', 'Collar' => 'Lapel collar with front button fastening']],
                    ['title' => 'Levi\'s 721 High Rise Skinny Women\'s Jeans', 'brand' => 'levis', 'sub' => 2, 'price' => 5800, 'sale' => 5100, 'stock' => 35, 'specs' => ['Rise' => 'High rise (10.25 inches) holds and flatters waist', 'Leg' => 'Skinny from hip through leg opening', 'Stretch' => 'Levi\'s Sculpt with 4-way hyperstretch denim', 'Pockets' => 'Signature 5-pocket styling']],
                    ['title' => 'H&M Ribbed Knit Long Sleeve Mock Neck Top', 'brand' => 'hm', 'sub' => 1, 'price' => 1950, 'sale' => 1650, 'stock' => 45, 'specs' => ['Material' => 'Soft fine-knit cotton-viscose rib', 'Neck' => 'Chic standing mock turtleneck collar', 'Fit' => 'Fitted body-skimming silhouette', 'Sleeves' => 'Full length fitted sleeves']],
                    ['title' => 'Zara Double-Breasted Tailored Cream Blazer', 'brand' => 'zara', 'sub' => 3, 'price' => 9800, 'sale' => 8700, 'stock' => 20, 'specs' => ['Style' => 'Structured power blazer with pronounced shoulders', 'Buttons' => 'Contrast tortoiseshell double-breasted buttons', 'Lapel' => 'Peak lapel with front flap pockets', 'Lining' => 'Tonal full polyester lining']],
                    ['title' => 'H&M Pleated A-Line Midi Skirt Black', 'brand' => 'hm', 'sub' => 0, 'price' => 2950, 'sale' => 2550, 'stock' => 30, 'specs' => ['Waist' => 'High elasticated grosgrain waistband', 'Pleating' => 'Permanent accordion plissé knife pleats', 'Fabric' => 'Lightweight woven fabric with elegant sway', 'Length' => 'Mid-calf midi length 78cm']],
                    ['title' => 'Zara Poplin Oversized Crisp Cotton Shirt', 'brand' => 'zara', 'sub' => 1, 'price' => 3800, 'sale' => 3300, 'stock' => 32, 'specs' => ['Fabric' => '100% Crisp cotton poplin', 'Cut' => 'Boyfriend oversized silhouette with dropped shoulders', 'Hem' => 'Curved high-low hemline', 'Pockets' => 'Patch chest pocket']],
                    ['title' => 'Levi\'s Original Trucker Denim Jacket Women', 'brand' => 'levis', 'sub' => 3, 'price' => 6500, 'sale' => 5800, 'stock' => 24, 'specs' => ['Denim' => '100% Non-stretch denim with vintage fade', 'Fit' => 'Classic straight silhouette hits at hip', 'Buttons' => 'Shank button front and button-flap chest pockets', 'Tabs' => 'Adjustable back waist tabs']],
                    ['title' => 'Zara Wide-Leg High Waist Flowy Trousers', 'brand' => 'zara', 'sub' => 2, 'price' => 4800, 'sale' => 4200, 'stock' => 28, 'specs' => ['Waist' => 'Extra high-waist with belt loops', 'Cut' => 'Wide palazzo leg with front pleats', 'Fabric' => 'Drapey wrinkle-resistant twill', 'Pockets' => 'Side slit pockets and false rear welts']],
                    ['title' => 'H&M Sleeveless Satin Slip Midi Dress Emerald', 'brand' => 'hm', 'sub' => 0, 'price' => 3450, 'sale' => 2999, 'stock' => 22, 'specs' => ['Material' => 'Heavy fluid satin with lustrous glossy sheen', 'Neckline' => 'Cowl draped neckline with adjustable spaghetti straps', 'Cut' => 'Bias cut hugs curves naturally', 'Care' => 'Machine wash delicate']],
                    ['title' => 'Zara Striped Knit Boatneck Top Navy White', 'brand' => 'zara', 'sub' => 1, 'price' => 2800, 'sale' => 2400, 'stock' => 38, 'specs' => ['Style' => 'Timeless French Breton nautical stripes', 'Neck' => 'Wide bateau boatneck collar', 'Fabric' => 'Breathable 100% cotton knit', 'Sleeves' => 'Three-quarter sleeves with side vents']],
                ]
            ],
            // 22. Women's Activewear & Lounge
            [
                'cat_slug' => 'womens-activewear-lounge',
                'has_variants' => true,
                'variant_type' => 'clothing',
                'items' => [
                    ['title' => 'Nike Dri-FIT One High-Waisted 7/8 Leggings', 'brand' => 'nike', 'sub' => 0, 'price' => 4500, 'sale' => 3999, 'stock' => 35, 'specs' => ['Fabric' => 'Non-sheer fabric passes squat test with confidence', 'Waist' => 'Seamless sides and contoured V-shape back waistband', 'Pockets' => '2 hidden pockets in the high waistband', 'Technology' => 'Dri-FIT wicks moisture to keep cool']],
                    ['title' => 'Nike Swoosh Medium-Support Padded Sports Bra', 'brand' => 'nike', 'sub' => 1, 'price' => 3400, 'sale' => 2999, 'stock' => 40, 'specs' => ['Support' => 'Medium support ideal for gym workouts, spin, and running', 'Padding' => '1-piece removable pad resists shifting and folding', 'Straps' => 'Racerback straps allow natural range of motion', 'Fabric' => '72% Recycled polyester, 28% Spandex']],
                    ['title' => 'Adidas Techfit 3-Stripes Training Tights', 'brand' => 'adidas', 'sub' => 0, 'price' => 4200, 'sale' => 3700, 'stock' => 30, 'specs' => ['Compression' => 'Techfit focuses muscles\' energy for long-term endurance', 'AEROREADY' => 'Moisture-absorbing technology keeps dry', 'Waist' => 'High-rise curved elastic waistband', 'Detail' => 'Iconic 3-Stripes running down outer thighs']],
                    ['title' => 'Puma High-Impact Front-Zip Fast Sports Bra', 'brand' => 'puma', 'sub' => 1, 'price' => 3800, 'sale' => 3299, 'stock' => 28, 'specs' => ['Closure' => 'Front center zip closure with safety hook inside', 'Support' => 'High impact support bounce control for running', 'Breathability' => 'Mesh racerback insert for maximum airflow', 'Technology' => 'dryCELL performance fabric']],
                    ['title' => 'Zara Soft Touch Modal Lounge Joggers Grey', 'brand' => 'zara', 'sub' => 2, 'price' => 3600, 'sale' => 3100, 'stock' => 32, 'specs' => ['Fabric' => 'Ultra-soft brushed modal-cotton fleece blend', 'Waist' => 'Elastic waistband with adjustable drawstring cord', 'Cuffs' => 'Ribbed ankle cuffs lock in warmth', 'Fit' => 'Relaxed tapered lounging silhouette']],
                    ['title' => 'H&M Cotton Poplin Striped Pajama Set Pink', 'brand' => 'hm', 'sub' => 3, 'price' => 2850, 'sale' => 2499, 'stock' => 35, 'specs' => ['Set' => 'Includes button-front pajama shirt and matching pants', 'Fabric' => '100% Breathable crisp cotton poplin', 'Piping' => 'White contrast satin piping along notch collar and cuffs', 'Waist' => 'Comfortable elasticized waistband with ribbon tie']],
                    ['title' => 'Puma Studio Foundation Seamless Yoga Leggings', 'brand' => 'puma', 'sub' => 0, 'price' => 4600, 'sale' => 4100, 'stock' => 25, 'specs' => ['Knit' => 'Engineered seamless circular knit eliminates chafing', 'Stretch' => '4-way super stretch for uninterrupted yoga poses', 'Waistband' => 'Ribbed wide compressive high tummy waistband', 'Material' => '89% Nylon, 11% Elastane']],
                    ['title' => 'H&M Cozy Waffle-Knit Hoodie & Shorts Lounge Set', 'brand' => 'hm', 'sub' => 2, 'price' => 3200, 'sale' => 2799, 'stock' => 30, 'specs' => ['Texture' => 'Lightweight thermal waffle honeycomb knit', 'Top' => 'Cropped slouchy long-sleeve hoodie', 'Bottom' => 'Elastic waist matching lounge shorts with pockets', 'Fabric' => '60% Cotton, 40% Polyester blend']],
                    ['title' => 'Zara Silk-Blend Lace Trim Cami & Shorts Pajamas', 'brand' => 'zara', 'sub' => 3, 'price' => 3999, 'sale' => 3499, 'stock' => 20, 'specs' => ['Material' => 'Luxurious silk-satin blend with delicate eyelash lace', 'Top' => 'V-neck camisole with adjustable cross back straps', 'Bottom' => 'Flirty mini sleep shorts with scalloped lace hem', 'Care' => 'Hand wash recommended']],
                    ['title' => 'Adidas Essentials Linear French Terry Sweatpants', 'brand' => 'adidas', 'sub' => 2, 'price' => 3800, 'sale' => 3350, 'stock' => 35, 'specs' => ['Fabric' => '100% Cotton French terry soft interior', 'Logo' => 'Linear Adidas wordmark printed down lower left leg', 'Pockets' => 'Front slip-in hand pockets', 'Fit' => 'Slim tapered athletic fit']],
                ]
            ],
            // 23. Men's Footwear
            [
                'cat_slug' => 'mens-footwear',
                'has_variants' => true,
                'variant_type' => 'shoes',
                'items' => [
                    ['title' => 'Nike Air Zoom Pegasus 40 Men\'s Running Shoes', 'brand' => 'nike', 'sub' => 0, 'price' => 13500, 'sale' => 12499, 'stock' => 25, 'specs' => ['Foam' => 'Nike React technology with dual Zoom Air units', 'Upper' => 'Single-layer engineered mesh for lightweight breathability', 'Midfoot' => 'Redesigned midfoot band for a more forgiving fit', 'Weight' => '288g (Men\'s size 10)']],
                    ['title' => 'Adidas Ultraboost Light Men\'s Running Shoes', 'brand' => 'adidas', 'sub' => 0, 'price' => 18500, 'sale' => 16999, 'stock' => 20, 'specs' => ['Boost' => 'Light BOOST 30% lighter with epic energy return', 'Upper' => 'adidas PRIMEKNIT+ textile foot-hugging upper', 'System' => 'Linear Energy Push system increases stiffness', 'Outsole' => 'Continental Better Rubber outsole grip']],
                    ['title' => 'Apex Handcrafted Leather Penny Loafers Tan', 'brand' => 'apex', 'sub' => 1, 'price' => 5490, 'sale' => 4990, 'stock' => 30, 'specs' => ['Leather' => 'Full-grain cow crust polished leather upper', 'Stitching' => 'Handcrafted moccasin toe contrast stitching', 'Insole' => 'Memory foam cushioned leather footbed', 'Outsole' => 'Non-slip grooved TPR flexible sole']],
                    ['title' => 'Bata Comfit Classic Black Leather Oxford Shoes', 'brand' => 'bata', 'sub' => 2, 'price' => 4490, 'sale' => 3990, 'stock' => 35, 'specs' => ['Style' => 'Timeless closed-lacing cap-toe formal Oxford', 'Leather' => 'High-shine polished genuine leather', 'Footbed' => 'Bata Comfit ergonomic arch support cushion', 'Occasion' => 'Corporate boardroom, interviews, and black-tie events']],
                    ['title' => 'Nike Air Force 1 \'07 Triple White Sneakers', 'brand' => 'nike', 'sub' => 0, 'price' => 11500, 'sale' => 10500, 'stock' => 40, 'specs' => ['Heritage' => 'Original 1982 basketball court silhouette', 'Cushioning' => 'Encapsulated Nike Air-Sole unit', 'Collar' => 'Padded low-cut collar looks sleek and feels great', 'Tread' => 'Pivot circle rubber outsole for traction']],
                    ['title' => 'Puma Velocity Nitro 2 Men\'s Running Shoes', 'brand' => 'puma', 'sub' => 0, 'price' => 11000, 'sale' => 9800, 'stock' => 22, 'specs' => ['Foam' => 'NITRO FOAM nitrogen-infused lightweight cushion', 'Grip' => 'PUMAGRIP all-surface durable rubber compound', 'Reflective' => 'Strategically placed reflective accents for night runs', 'Drop' => '10mm heel-to-toe drop']],
                    ['title' => 'Apex Royal Crown Derby Leather Dress Shoes', 'brand' => 'apex', 'sub' => 2, 'price' => 6990, 'sale' => 6290, 'stock' => 18, 'specs' => ['Construction' => 'Blake stitched premium dress shoe construction', 'Finish' => 'Hand-burnished Italian patina finish on toe', 'Lining' => 'Breathable sheepskin leather interior', 'Sole' => 'Genuine leather sole with rubber traction island']],
                    ['title' => 'Bata Executive Slip-On Tassel Loafers Burgundy', 'brand' => 'bata', 'sub' => 1, 'price' => 4990, 'sale' => 4490, 'stock' => 26, 'specs' => ['Design' => 'Elegant dual front tassels with woven apron detail', 'Upper' => 'Supple polished box leather in deep burgundy', 'Sole' => 'Lightweight shock-absorbing EVA rubber outsole', 'Fit' => 'Easy slip-on with dual hidden elastic side gores']],
                    ['title' => 'Apex Men\'s Casual Genuine Leather Cross Sandals', 'brand' => 'apex', 'sub' => 3, 'price' => 2990, 'sale' => 2690, 'stock' => 45, 'specs' => ['Straps' => 'Wide crisscross oil-tanned leather straps', 'Footbed' => 'Molded anatomical cork footbed with suede cover', 'Sole' => 'Durable ribbed rubber tread for summer traction', 'Durability' => 'Double-stitched stress points for longevity']],
                    ['title' => 'Bata Power Walking Athletic Sneakers Navy', 'brand' => 'bata', 'sub' => 0, 'price' => 3290, 'sale' => 2890, 'stock' => 38, 'specs' => ['Upper' => 'Breathable air-mesh with synthetic support overlays', 'Midsole' => 'Ultra-cushioned Phylon foam absorbs road shock', 'Insole' => 'Removable memory-tech anti-odor footbed', 'Weight' => '220g featherweight daily walking shoe']],
                ]
            ],
            // 24. Women's Footwear
            [
                'cat_slug' => 'womens-footwear',
                'has_variants' => true,
                'variant_type' => 'shoes',
                'items' => [
                    ['title' => 'Bata Red Label Pointed Toe Stiletto Pumps Black', 'brand' => 'bata', 'sub' => 0, 'price' => 3990, 'sale' => 3490, 'stock' => 28, 'specs' => ['Heel Height' => '3.5-inch classic slender stiletto heel', 'Upper' => 'Glossy faux patent leather easy to wipe clean', 'Insole' => 'Extra cushioned ball-of-foot padding', 'Toe' => 'Sharp sleek pointed-toe silhouette']],
                    ['title' => 'Nike Air Max 270 Women\'s Casual Sneakers', 'brand' => 'nike', 'sub' => 2, 'price' => 14500, 'sale' => 13200, 'stock' => 20, 'specs' => ['Air Unit' => 'Max Air 270 unit delivers 270 degrees of clear air', 'Upper' => 'Woven and synthetic breathable mesh upper', 'Bootie' => 'Stretchy inner sleeve creates a sock-like fit', 'Colorway' => 'Rose White with contrast air bubble']],
                    ['title' => 'Apex Marie Claire Block Heel Ankle Strap Sandals', 'brand' => 'apex', 'sub' => 0, 'price' => 3490, 'sale' => 2990, 'stock' => 32, 'specs' => ['Heel' => '2.5-inch sturdy block heel for comfortable balance', 'Closure' => 'Delicate ankle strap with adjustable metallic buckle', 'Material' => 'Soft faux suede leather upper', 'Occasion' => 'Parties, dinners, and semi-formal gatherings']],
                    ['title' => 'Puma Carina 2.0 Women\'s Platform Sneakers', 'brand' => 'puma', 'sub' => 2, 'price' => 6500, 'sale' => 5800, 'stock' => 35, 'specs' => ['Inspiration' => '80s California beach lifestyle aesthetic', 'Sole' => 'Chunky textured platform rubber cupsole', 'SoftFoam' => 'SoftFoam+ sockliner provides superior step-in cushion', 'Upper' => 'Premium genuine leather with Puma Formstrip']],
                    ['title' => 'Bata Comfit Bow Detail Ballet Flats Nude', 'brand' => 'bata', 'sub' => 1, 'price' => 2490, 'sale' => 2190, 'stock' => 45, 'specs' => ['Design' => 'Classic rounded toe with mini grosgrain bow accent', 'Cushion' => 'Comfit multi-density foam insole prevents fatigue', 'Flexibility' => 'Foldable ultra-flexible rubber slip-resistant sole', 'Color' => 'Versatile neutral nude beige']],
                    ['title' => 'Apex Handcrafted Leather Slip-On Loafers Women', 'brand' => 'apex', 'sub' => 1, 'price' => 4290, 'sale' => 3790, 'stock' => 25, 'specs' => ['Upper' => 'Supple grain leather softens with each wear', 'Hardware' => 'Polished gold-tone equestrian horsebit buckle', 'Lining' => 'Breathable genuine leather lining', 'Comfort' => 'Padded collar protects heel from blisters']],
                    ['title' => 'Zara Leather Pointed Ankle Boots Block Heel', 'brand' => 'zara', 'sub' => 3, 'price' => 8500, 'sale' => 7499, 'stock' => 18, 'specs' => ['Upper' => '100% Genuine cowhide leather', 'Heel' => '6.5cm angular block heel for confident stride', 'Fastening' => 'Side zipper closure with metal pull tab', 'Shaft' => 'Fitted ankle shaft looks great under jeans']],
                    ['title' => 'Adidas Stan Smith Women\'s Originals Sneaker', 'brand' => 'adidas', 'sub' => 2, 'price' => 10500, 'sale' => 9499, 'stock' => 26, 'specs' => ['Upper' => 'Synthetic Primegreen upper with minimum 50% recycled', 'Perforations' => 'Perforated 3-Stripes along sides for ventilation', 'Heel Tab' => 'Signature green heel patch with Trefoil logo', 'Outsole' => 'Low-profile rubber cupsole']],
                    ['title' => 'Bata Comfit Everyday Wedge Comfort Sandals', 'brand' => 'bata', 'sub' => 0, 'price' => 2990, 'sale' => 2590, 'stock' => 40, 'specs' => ['Wedge' => '2-inch gradual wedge platform provides elevation', 'Footbed' => 'Contoured footbed cradles arch and heel', 'Upper' => 'Dual soft synthetic leather cross straps', 'Closure' => 'Elastic backstrap for secure effortless on/off']],
                    ['title' => 'Zara Suede Flat Chelsea Boots with Lug Sole', 'brand' => 'zara', 'sub' => 3, 'price' => 7800, 'sale' => 6999, 'stock' => 16, 'specs' => ['Upper' => '100% Split suede leather with water-repellent finish', 'Sole' => 'Heavy-duty track lug sole for bold urban look', 'Gores' => 'Elastic side panels and rear pull loop', 'Color' => 'Sandy camel beige']],
                ]
            ],
            // 25. Watches & Horology
            [
                'cat_slug' => 'watches-horology',
                'has_variants' => true,
                'variant_type' => 'watch',
                'items' => [
                    ['title' => 'Seiko 5 Sports Automatic SRPD55K1 Diver Watch', 'brand' => 'seiko', 'sub' => 0, 'price' => 28500, 'sale' => 26500, 'stock' => 15, 'specs' => ['Movement' => 'Caliber 4R36 automatic with manual winding & hack', 'Power Reserve' => 'Approx. 41 hours power reserve (24 jewels)', 'Case' => '42.5mm stainless steel with Hardlex crystal', 'Water Resistance' => '10 bar (100 meters) with see-through case back']],
                    ['title' => 'Casio G-Shock GA-2100-1A1ER "CasiOak" All Black', 'brand' => 'casio', 'sub' => 3, 'price' => 12500, 'sale' => 10999, 'stock' => 35, 'specs' => ['Structure' => 'Carbon Core Guard shock resistant structure', 'Display' => 'Analog-digital dual display with Double LED light', 'Water' => '200 meters (20 bar) water resistance', 'Profile' => 'Slimmest G-Shock case at only 11.8mm thin']],
                    ['title' => 'Tissot PRX Powermatic 80 Blue Dial Automatic', 'brand' => 'seiko', 'sub' => 0, 'price' => 78000, 'sale' => 72500, 'stock' => 8, 'specs' => ['Movement' => 'Powermatic 80.111 with 80 hours power reserve', 'Dial' => 'Embossed waffle chequered pattern blue dial', 'Glass' => 'Scratch-resistant sapphire crystal with anti-reflective coating', 'Bracelet' => 'Integrated satin-finish stainless steel bracelet']],
                    ['title' => 'Casio Vintage Digital A168WA-1 ElectroLuminescence', 'brand' => 'casio', 'sub' => 3, 'price' => 3400, 'sale' => 2999, 'stock' => 50, 'specs' => ['Illumination' => 'ElectroLuminescent blue backlight panel', 'Features' => '1/100-second stopwatch, daily alarm, hourly chime', 'Band' => 'Adjustable self-clasp stainless steel band', 'Battery' => 'Approx. 7 years battery life on CR2016']],
                    ['title' => 'Fossil Neutra Chronograph Brown Leather Watch', 'brand' => 'fossil', 'sub' => 1, 'price' => 14500, 'sale' => 12999, 'stock' => 24, 'specs' => ['Movement' => 'Quartz chronograph movement with date window', 'Case' => '44mm round stainless steel case', 'Dial' => 'Cream dial with Roman numeral indices', 'Strap' => 'Interchangeable 22mm genuine leather strap']],
                    ['title' => 'Seiko Prospex Speedtimer Solar Chronograph', 'brand' => 'seiko', 'sub' => 1, 'price' => 64000, 'sale' => 59500, 'stock' => 10, 'specs' => ['Movement' => 'Caliber V192 Solar powered by any light source', 'Power' => 'Approx. 6 months reserve when fully charged', 'Glass' => 'Curved sapphire crystal with anti-reflective coating', 'Dial' => 'Sand-textured panda dial with tachymeter bezel']],
                    ['title' => 'Casio Edifice EFV-550D Chronograph Watch', 'brand' => 'casio', 'sub' => 1, 'price' => 11000, 'sale' => 9750, 'stock' => 28, 'specs' => ['Case' => 'Solid stainless steel case with screw-lock back', 'Chronograph' => '1/10-second stopwatch with split time', 'Water' => '100-meter water resistance suitable for swimming', 'Hands' => 'Neo-display luminous coating on hands & markers']],
                    ['title' => 'Orient Bambino Version 4 Automatic Dress Watch', 'brand' => 'seiko', 'sub' => 0, 'price' => 22000, 'sale' => 19999, 'stock' => 14, 'specs' => ['Movement' => 'Japanese automatic in-house caliber F6724', 'Crystal' => 'Vintage domed mineral crystal', 'Dial' => 'Sunburst ombre dial with slender polished hands', 'Case' => '42mm polished stainless steel with exhibition back']],
                    ['title' => 'Fossil Minimalist Slim Three-Hand Watch Black', 'brand' => 'fossil', 'sub' => 2, 'price' => 11500, 'sale' => 9999, 'stock' => 30, 'specs' => ['Case' => '44mm ultra-slim 8mm profile black plated case', 'Dial' => 'Matte black minimalist dial with clean stick indices', 'Strap' => '22mm black stainless steel mesh bracelet', 'Water' => '50-meter water resistance']],
                    ['title' => 'Casio G-Shock Mudmaster Twin Sensor GG-1000', 'brand' => 'casio', 'sub' => 3, 'price' => 32000, 'sale' => 28999, 'stock' => 12, 'specs' => ['Sensors' => 'Twin sensor: Digital compass and thermometer', 'Protection' => 'Mud Resistant gasket buttons prevent sand intrusion', 'Structure' => 'Heavy-duty resin and steel reinforced case', 'Light' => 'Super Illuminator auto high-brightness LED']],
                ]
            ],
        ];
    }
}
